# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import ExtendedCombatantData


class AdultBlackDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Black Dragon",
            hp=195,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={
                "Str": 23,
                "Dex": 14,
                "Con": 21,
                "Int": 14,
                "Wis": 13,
                "Cha": 19,
            },
            saving_throws={},
            spell_slots={},
            cr="14",
            monster_type="Huge Dragon (Chromatic), Chaotic Evil",
            ac_note="",
            hp_formula="17d12 + 85",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 21",
            languages="Common, Draconic",
            traits=[
                {
                    "name": "Amphibious",
                    "description": "The dragon can breathe air and water.",
                },
                {
                    "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
                    "description": "If the dragon fails a saving throw, it can choose to succeed instead.",
                },
            ],
            actions=[
                {
                    "name": "Multiattack",
                    "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Melf's Acid Arrow (level 3 version).",
                },
                {
                    "name": "Rend",
                    "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 13 (2d6 + 6) Slashing damage plus 4 (1d8) Acid damage.",
                },
                {
                    "name": "Acid Breath (Recharge 5–6)",
                    "description": "Dexterity Saving Throw: DC 18, each creature in a 60-foot-long, 5-foot-wide Line. Failure: 54 (12d8) Acid damage. Success: Half damage.",
                },
                {
                    "name": "Spellcasting",
                    "description": "The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 17, +9 to hit with spell attacks):",
                },
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
                {
                    "name": "Cloud of Insects",
                    "description": "Dexterity Saving Throw: DC 17, one creature the dragon can see within 120 feet. Failure: 22 (4d10) Poison damage, and the target has Disadvantage on saving throws to maintain Concentration until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
                },
                {
                    "name": "Frightful Presence",
                    "description": "The dragon uses Spellcasting to cast Fear. The dragon can't take this action again until the start of its next turn.",
                },
                {
                    "name": "Pounce",
                    "description": "The dragon moves up to half its Speed, and it makes one Rend attack.",
                },
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class AdultCopperDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Copper Dragon",
            hp=184,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                "Str": 23,
                "Dex": 12,
                "Con": 21,
                "Int": 18,
                "Wis": 15,
                "Cha": 18,
            },
            saving_throws={},
            spell_slots={},
            cr="14",
            monster_type="Huge Dragon (Metallic), Chaotic Good",
            ac_note="",
            hp_formula="16d12 + 80",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 22",
            languages="Common, Draconic",
            traits=[
                {
                    "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
                    "description": "If the dragon fails a saving throw, it can choose to succeed instead.",
                },
            ],
            actions=[
                {
                    "name": "Multiattack",
                    "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Slowing Breath or (B) Spellcasting to cast Mind Spike (level 4 version).",
                },
                {
                    "name": "Rend",
                    "description": "Melee Attack Roll: +11, reach 10 ft. Hit: 17 (2d10 + 6) Slashing damage plus 4 (1d8) Acid damage.",
                },
                {
                    "name": "Acid Breath (Recharge 5–6)",
                    "description": "Dexterity Saving Throw: DC 18, each creature in an 60-foot-long, 5-foot-wide Line. Failure: 54 (12d8) Acid damage. Success: Half damage.",
                },
                {
                    "name": "Slowing Breath",
                    "description": "Constitution Saving Throw: DC 18, each creature in a 60-foot Cone. Failure: The target can't take Reactions; its Speed is halved; and it can take either an action or a Bonus Action on its turn, not both. This effect lasts until the end of its next turn.",
                },
                {
                    "name": "Spellcasting",
                    "description": "The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 17):",
                },
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
                {
                    "name": "Giggling Magic",
                    "description": "Charisma Saving Throw: DC 17, one creature the dragon can see within 90 feet. Failure: 24 (7d6) Psychic damage. Until the end of its next turn, the target rolls 1d6 whenever it makes an ability check or attack roll and subtracts the number rolled from the D20 Test. Failure or Success: The dragon can't take this action again until the start of its next turn.",
                },
                {
                    "name": "Mind Jolt",
                    "description": "The dragon uses Spellcasting to cast Mind Spike (level 4 version). The dragon can't take this action again until the start of its next turn.",
                },
                {
                    "name": "Pounce",
                    "description": "The dragon moves up to half its Speed, and it makes one Rend attack.",
                },
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class DeathTyrant(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Death Tyrant",
            hp=195,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={
                "Str": 18,
                "Dex": 14,
                "Con": 14,
                "Int": 19,
                "Wis": 15,
                "Cha": 19,
            },
            saving_throws={},
            spell_slots={},
            cr="14",
            monster_type="Large Undead (Beholder), Lawful Evil",
            ac_note="",
            hp_formula="26d10 + 52",
            speed="5 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 22",
            languages="Deep Speech, Undercommon",
            traits=[
                {
                    "name": "Legendary Resistance (3/Day, or 4/Day in Lair)",
                    "description": "If the death tyrant fails a saving throw, it can choose to succeed instead.",
                },
            ],
            actions=[
                {
                    "name": "Multiattack",
                    "description": "The death tyrant uses Eye Rays three times.",
                },
                {
                    "name": "Bite",
                    "description": "Melee Attack Roll: +9, reach 5 ft. Hit: 13 (2d8 + 4) Piercing damage.",
                },
                {
                    "name": "Eye Rays",
                    "description": "The death tyrant randomly shoots one of the following magical rays at a target it can see within 120 feet of itself (roll 1d10; reroll if the death tyrant has already used that ray during this turn):",
                },
                {
                    "name": "1: Charm Ray",
                    "description": ". Wisdom Saving Throw: DC 17. Failure: 13 (3d8) Psychic damage, and the target has the Charmed condition for 1 hour or until it takes damage. Success: Half damage only.",
                },
                {
                    "name": "2: Paralyzing Ray",
                    "description": ". Constitution Saving Throw: DC 17. Failure: The target has the Paralyzed condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.",
                },
                {
                    "name": "3: Fear Ray",
                    "description": ". Wisdom Saving Throw: DC 17. Failure: 10 (3d6) Psychic damage, and the target has the Frightened condition until the end of its next turn. Success: Half damage only.",
                },
                {
                    "name": "4: Slowing Ray",
                    "description": ". Constitution Saving Throw: DC 17. Failure: 18 (4d8) Necrotic damage. Until the end of the target's next turn, the target can't take Reactions; its Speed is halved; and it can take either an action or a Bonus Action on its turn, not both. Success: Half damage only.",
                },
                {
                    "name": "5: Enervation Ray",
                    "description": ". Constitution Saving Throw: DC 17. Failure: 16 (3d10) Poison damage, and the target has the Poisoned condition until the end of its next turn. While Poisoned, the target can't regain Hit Points. Success: Half damage only.",
                },
                {
                    "name": "6: Telekinetic Ray",
                    "description": ". Strength Saving Throw: DC 17 (the target succeeds automatically if it is Gargantuan). Failure: The death tyrant moves the target up to 30 feet in any direction. The target has the Restrained condition until the start of the death tyrant's next turn or until the death tyrant has the Incapacitated condition. The death tyrant can also exert fine control on objects with this ray, such as manipulating a tool or opening a door or container.",
                },
                {
                    "name": "7: Sleep Ray",
                    "description": ". Wisdom Saving Throw: DC 17 (the target succeeds automatically if it is a Construct or an Undead). Failure: The target has the Unconscious condition for 1 minute. The condition ends if the target takes damage or a creature within 5 feet of it takes an action to wake it.",
                },
                {
                    "name": "8: Petrification Ray",
                    "description": ". Constitution Saving Throw: DC 17. First Failure: The target has the Restrained condition and repeats the save at the end of its next turn if it is still Restrained, ending the effect on itself on a success. Second Failure: The target has the Petrified condition instead of the Restrained condition.",
                },
                {
                    "name": "9: Disintegration Ray",
                    "description": ". Dexterity Saving Throw: DC 17. Failure: 36 (8d8) Force damage. If the target is a nonmagical object or a creation of magical force, a 10-foot Cube of it disintegrates into dust. Success: Half damage. Failure or Success: If the target is a creature and this damage reduces it to 0 Hit Points, it disintegrates into dust.",
                },
                {
                    "name": "10: Death Ray",
                    "description": ". Dexterity Saving Throw: DC 17. Failure: 55 (10d10) Necrotic damage. Success: Half damage. Failure or Success: The target dies if the ray reduces it to 0 Hit Points.",
                },
            ],
            bonus_actions=[
                {
                    "name": "Negative Energy Cone",
                    "description": "The death tyrant's central eye emits an imperceptible, magical wave of negative energy in a 150-foot Cone. Creatures in that area can't regain Hit Points until the start of the death tyrant's next turn. An intact Humanoid corpse there instantly rises as a Zombie under the death tyrant's control and takes its turn immediately after the death tyrant on the same initiative count.",
                },
            ],
            reactions=[],
            legendary_actions=[
                {
                    "name": "Chomp",
                    "description": "The death tyrant makes two Bite attacks.",
                },
                {"name": "Glare", "description": "The death tyrant uses Eye Rays."},
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class IceDevil(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ice Devil",
            hp=228,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                "Str": 21,
                "Dex": 14,
                "Con": 18,
                "Int": 18,
                "Wis": 15,
                "Cha": 18,
            },
            saving_throws={},
            spell_slots={},
            cr="14",
            monster_type="Large Fiend (Devil), Lawful Evil",
            ac_note="",
            hp_formula="24d10 + 96",
            speed="decreases by 10 feet, and it can move or take one action on its turn, not both.",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 120 ft., Passive Perception 17",
            languages="Infernal; telepathy 120 ft.",
            traits=[
                {
                    "name": "Diabolical Restoration",
                    "description": "If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells.",
                },
                {
                    "name": "Magic Resistance",
                    "description": "The devil has Advantage on saving throws against spells and other magical effects.",
                },
            ],
            actions=[
                {
                    "name": "Multiattack",
                    "description": "The devil makes three Ice Spear attacks. It can replace one attack with a Tail attack.",
                },
                {
                    "name": "Ice Spear",
                    "description": "Melee or Ranged Attack Roll: +10, reach 5 ft. or range 30/120 ft. Hit: 14 (2d8 + 5) Piercing damage plus 10 (3d6) Cold damage. Until the end of its next turn, the target can't take a Bonus Action or Reaction, its Speed decreases by 10 feet, and it can move or take one action on its turn, not both. Hit or Miss: The spear magically returns to the devil's hand immediately after a ranged attack.",
                },
                {
                    "name": "Tail",
                    "description": "Melee Attack Roll: +10, reach 10 ft. Hit: 15 (3d6 + 5) Bludgeoning damage plus 18 (4d8) Cold damage.",
                },
                {
                    "name": "Ice Wall (Recharge 6)",
                    "description": "The devil casts Wall of Ice (level 8 version), requiring no spell components and using Intelligence as the spellcasting ability (spell save DC 17).",
                },
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ["AdultBlackDragon", "AdultCopperDragon", "DeathTyrant", "IceDevil"]
