# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    Skill,
)
from Definitions import Ability


class AbominableYeti(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Abominable Yeti",
            hp=137,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 24, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 22, Ability.INTELLIGENCE.short_name: 9, Ability.WISDOM.short_name: 13, Ability.CHARISMA.short_name: 9},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Huge Monstrosity, Chaotic Evil",
            ac_note="",
            hp_formula="11d12 + 66",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 19",
            languages="Yeti",
            traits=[
            MonsterAbility(name='Fear of Fire', description='If the yeti takes Fire damage, it has Disadvantage on attack rolls and ability checks until the end of its next turn.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The yeti can use its Chilling Gaze and makes two attacks, using Claw or Ice Throw in any combination.'),
            MonsterAbility(name='Claw', description='Melee Attack Roll: +11, reach 5 ft. Hit: 14 (2d6 + 7) Slashing damage plus 7 (2d6) Cold damage.'),
            MonsterAbility(name='Ice Throw', description='Ranged Attack Roll: +11, range 60/240 ft. Hit: 12 (2d4 + 7) Bludgeoning damage plus 7 (2d6) Cold damage.'),
            MonsterAbility(name='Chilling Gaze', description="Constitution Saving Throw: DC 18, one creature the yeti can see within 30 feet. Failure: 21 (6d6) Cold damage, and the target has the Paralyzed condition until the start of the yeti's next turn unless the target has Immunity to Cold damage. Success: The target is immune to this yeti's Chilling Gaze for 1 hour."),
            MonsterAbility(name='Cold Breath (Recharge 6)', description='Constitution Saving Throw: DC 18, each creature in a 30-foot Cone. Failure: 45 (10d8) Cold damage. Success: Half damage.'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class BoneDevil(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Bone Devil",
            hp=161,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 18, Ability.DEXTERITY.short_name: 16, Ability.CONSTITUTION.short_name: 18, Ability.INTELLIGENCE.short_name: 13, Ability.WISDOM.short_name: 14, Ability.CHARISMA.short_name: 16},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Fiend (Devil), Lawful Evil",
            ac_note="",
            hp_formula="17d10 + 68",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft. (unimpeded by magical Darkness), Passive Perception 12",
            languages="Infernal; telepathy 120 ft.",
            traits=[
            MonsterAbility(name='Diabolical Restoration', description='If the devil dies outside the Nine Hells, its body disappears in sulfurous smoke, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells.'),
            MonsterAbility(name='Magic Resistance', description='The devil has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The devil makes two Claw attacks and one Infernal Sting attack.'),
            MonsterAbility(name='Claw', description='Melee Attack Roll: +8, reach 10 ft. Hit: 13 (2d8 + 4) Slashing damage.'),
            MonsterAbility(name='Infernal Sting', description="Melee Attack Roll: +8, reach 10 ft. Hit: 15 (2d10 + 4) Piercing damage plus 18 (4d8) Poison damage, and the target has the Poisoned condition until the start of the devil's next turn. While Poisoned, the target can't regain Hit Points."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class BrazenGorgon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Brazen Gorgon",
            hp=161,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 18, Ability.DEXTERITY.short_name: 14, Ability.CONSTITUTION.short_name: 19, Ability.INTELLIGENCE.short_name: 2, Ability.WISDOM.short_name: 14, Ability.CHARISMA.short_name: 7},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Construct, Unaligned",
            ac_note="",
            hp_formula="17d10 + 68",
            speed="without provoking",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 20",
            languages="—",
            traits=[
            MonsterAbility(name='Flame Aura', description="At the end of each of the gorgon's turns, each creature in a 5-foot Emanation originating from the gorgon takes 13 (3d8) Fire damage."),
            MonsterAbility(name='Illumination', description='The gorgon sheds Bright Light in a 10-foot radius and Dim Light for an additional 10 feet.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The gorgon makes two Gore attacks.'),
            MonsterAbility(name='Gore', description='Melee Attack Roll: +8, reach 5 ft. Hit: 11 (2d6 + 4) Piercing damage plus 10 (3d6) Fire damage.'),
            MonsterAbility(name='Smelting Charge (Recharge 5–6)', description="The gorgon moves up to its Speed without provoking Opportunity Attacks and can move through the spaces of Medium or smaller creatures. Each time the gorgon enters a creature's space for the first time during this move, that target is subjected to the following effect. Dexterity Saving Throw: DC 16. Failure: 13 (2d8 + 4) Piercing damage plus 13 (3d8) Fire damage, and the target is pulled into the gorgon's space and has the Grappled condition (escape DC 14); if the gorgon already has a creature Grappled, the target has the Prone condition instead. Until the grapple ends, the target has the Restrained condition. When the gorgon moves, the Grappled target moves with it, costing no extra movement."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class ClayGolem(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Clay Golem",
            hp=123,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 20, Ability.DEXTERITY.short_name: 9, Ability.CONSTITUTION.short_name: 18, Ability.INTELLIGENCE.short_name: 3, Ability.WISDOM.short_name: 8, Ability.CHARISMA.short_name: 1},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Construct, Unaligned",
            ac_note="",
            hp_formula="13d10 + 52",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 9",
            languages="Common plus one other language",
            traits=[
            MonsterAbility(name='Acid Absorption', description='Whenever the golem is subjected to Acid damage, it takes no damage and instead regains a number of Hit Points equal to the Acid damage dealt.'),
            MonsterAbility(name='Berserk', description='Whenever the golem starts its turn Bloodied, roll 1d6. On a 6, the golem goes berserk. On each of its turns while berserk, the golem attacks the nearest creature it can see. If no creature is near enough to move to and attack, the golem attacks an object. Once the golem goes berserk, it continues to be berserk until it is destroyed or it is no longer Bloodied.'),
            MonsterAbility(name='Immutable Form', description="The golem can't shape-shift."),
            MonsterAbility(name='Magic Resistance', description='The golem has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The golem makes two Slam attacks, or it makes three Slam attacks if it used Hasten this turn.'),
            MonsterAbility(name='Slam', description="Melee Attack Roll: +9, reach 5 ft. Hit: 10 (1d10 + 5) Bludgeoning damage plus 6 (1d12) Acid damage, and the target's Hit Point maximum decreases by an amount equal to the Acid damage taken."),
        ],
            bonus_actions=[
            MonsterAbility(name='Hasten (Recharge 5–6)', description='The golem takes the Dash and Disengage actions.'),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class CloudGiant(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Cloud Giant",
            hp=200,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 27, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 22, Ability.INTELLIGENCE.short_name: 12, Ability.WISDOM.short_name: 16, Ability.CHARISMA.short_name: 16},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Huge Giant, Neutral",
            ac_note="",
            hp_formula="16d12 + 96",
            speed="40 ft.,",
            skills={Skill.INSIGHT: 7, Skill.PERCEPTION: 11},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 21",
            languages="Common, Giant",
            traits=[],
            actions=[
            MonsterAbility(name='Multiattack', description='The giant makes two attacks, using Thunderous Mace or Thundercloud in any combination. It can replace one attack with a use of Spellcasting to cast Fog Cloud.'),
            MonsterAbility(name='Thunderous Mace', description='Melee Attack Roll: +12, reach 10 ft. Hit: 21 (3d8 + 8) Bludgeoning damage plus 7 (2d6) Thunder damage.'),
            MonsterAbility(name='Thundercloud', description='Ranged Attack Roll: +12, range 240 ft. Hit: 18 (3d6 + 8) Thunder damage, and the target has the Incapacitated condition until the end of its next turn.'),
            MonsterAbility(name='Spellcasting', description='The giant casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 15):'),
        ],
            bonus_actions=[
            MonsterAbility(name='Misty Step', description='The giant casts the Misty Step spell, using the same spellcasting ability as Spellcasting.'),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class FireGiant(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Fire Giant",
            hp=162,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 25, Ability.DEXTERITY.short_name: 9, Ability.CONSTITUTION.short_name: 23, Ability.INTELLIGENCE.short_name: 10, Ability.WISDOM.short_name: 14, Ability.CHARISMA.short_name: 13},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Huge Giant, Lawful Evil",
            ac_note="",
            hp_formula="13d12 + 78",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 16",
            languages="Giant",
            traits=[],
            actions=[
            MonsterAbility(name='Multiattack', description='The giant makes two attacks, using Flame Sword or Hammer Throw in any combination.'),
            MonsterAbility(name='Flame Sword', description='Melee Attack Roll: +11, reach 10 ft. Hit: 21 (4d6 + 7) Slashing damage plus 10 (3d6) Fire damage.'),
            MonsterAbility(name='Hammer Throw', description='Ranged Attack Roll: +11, range 60/240 ft. Hit: 23 (3d10 + 7) Bludgeoning damage plus 4 (1d8) Fire damage, and the target is pushed up to 15 feet straight away from the giant and has Disadvantage on the next attack roll it makes before the end of its next turn.'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Glabrezu(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Glabrezu",
            hp=189,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 20, Ability.DEXTERITY.short_name: 15, Ability.CONSTITUTION.short_name: 21, Ability.INTELLIGENCE.short_name: 19, Ability.WISDOM.short_name: 17, Ability.CHARISMA.short_name: 16},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Fiend (Demon), Chaotic Evil",
            ac_note="",
            hp_formula="18d10 + 90",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 17",
            languages="Abyssal; telepathy 120 ft.",
            traits=[
            MonsterAbility(name='Demonic Restoration', description='If the glabrezu dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss.'),
            MonsterAbility(name='Magic Resistance', description='The glabrezu has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The glabrezu makes two Pincer attacks and uses Pummel or Spellcasting.'),
            MonsterAbility(name='Pincer', description='Melee Attack Roll: +9, reach 10 ft. Hit: 16 (2d10 + 5) Slashing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 15) from one of two pincers.'),
            MonsterAbility(name='Pummel', description='Dexterity Saving Throw: DC 17, one creature Grappled by the glabrezu. Failure: 15 (3d6 + 5) Bludgeoning damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The glabrezu casts one of the following spells, requiring no Material components and using Intelligence as the spellcasting ability (spell save DC 16):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GraySlaad(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Gray Slaad",
            hp=150,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 19, Ability.DEXTERITY.short_name: 17, Ability.CONSTITUTION.short_name: 16, Ability.INTELLIGENCE.short_name: 13, Ability.WISDOM.short_name: 8, Ability.CHARISMA.short_name: 18},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Medium Aberration, Chaotic Neutral",
            ac_note="",
            hp_formula="20d8 + 60",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 60 ft., Passive Perception 17",
            languages="Common, Slaad; telepathy 60 ft.",
            traits=[
            MonsterAbility(name='Magic Resistance', description='The slaad has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Regeneration', description='The slaad regains 10 Hit Points at the start of each of its turns if it has at least 1 Hit Point.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The slaad makes two Chaos Claw attacks.'),
            MonsterAbility(name='Chaos Claw', description="Melee Attack Roll: +8, reach 10 ft. Hit: 9 (1d10 + 4) Slashing damage plus 11 (2d10) Necrotic damage. Until the start of the slaad's next turn, the target has a condition determined by rolling 1d4: on a 1, Charmed; on a 2, Frightened; on a 3, Poisoned; or on a 4, Incapacitated."),
            MonsterAbility(name='Spellcasting', description='The slaad casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 16):'),
        ],
            bonus_actions=[
            MonsterAbility(name='Shape-Shift', description="The slaad shape-shifts into a Small or Medium Humanoid, or it returns to its true form. Other than its size, its game statistics are the same in each form. Any equipment it is wearing or carrying isn't transformed."),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Nycaloth(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Nycaloth",
            hp=152,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 20, Ability.DEXTERITY.short_name: 11, Ability.CONSTITUTION.short_name: 19, Ability.INTELLIGENCE.short_name: 12, Ability.WISDOM.short_name: 10, Ability.CHARISMA.short_name: 15},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Fiend (Yugoloth), Neutral Evil",
            ac_note="",
            hp_formula="16d10 + 64",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Passive Perception 14",
            languages="Abyssal, Infernal; telepathy 60 ft.",
            traits=[
            MonsterAbility(name='Fiendish Restoration', description='If the nycaloth dies outside Gehenna, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in Gehenna.'),
            MonsterAbility(name='Magic Resistance', description='The nycaloth has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The nycaloth makes two Mercurial Axe attacks.'),
            MonsterAbility(name='Mercurial Axe', description="Melee or Ranged Attack Roll: +9, reach 10 ft. or range 30/90 ft. Hit: 18 (2d12 + 5) Slashing damage plus 10 (3d6) Force damage. Hit or Miss: The axe magically returns to the nycaloth's hand immediately after a ranged attack."),
        ],
            bonus_actions=[
            MonsterAbility(name='Shadowy Teleport', description='The nycaloth has the Invisible condition for 1 minute, and it teleports up to 30 feet to an unoccupied space it can see. The condition ends early immediately after it deals damage.'),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Treant(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Treant",
            hp=138,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 23, Ability.DEXTERITY.short_name: 8, Ability.CONSTITUTION.short_name: 21, Ability.INTELLIGENCE.short_name: 12, Ability.WISDOM.short_name: 16, Ability.CHARISMA.short_name: 12},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Huge Plant, Chaotic Good",
            ac_note="",
            hp_formula="12d12 + 60",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 13",
            languages="Common, Druidic, Elvish, Sylvan",
            traits=[
            MonsterAbility(name='Siege Monster', description='The treant deals double damage to objects and structures.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The treant makes two Slam attacks.'),
            MonsterAbility(name='Slam', description='Melee Attack Roll: +10, reach 5 ft. Hit: 16 (3d6 + 6) Bludgeoning damage.'),
            MonsterAbility(name='Hail of Bark', description='Ranged Attack Roll: +10, range 180 ft. Hit: 28 (4d10 + 6) Piercing damage.'),
            MonsterAbility(name='Animate Trees (1/Day)', description="The treant magically animates up to two trees it can see within 60 feet of itself. Each tree uses the Treant stat block, except it has Intelligence and Charisma scores of 1, it can't speak, and it lacks this action. The tree takes its turn immediately after the treant on the same Initiative count, and it obeys the treant. A tree remains animate for 1 day or until it dies, the treant dies, or it is more than 120 feet from the treant. The tree then takes root if possible."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class YoungBlueDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Young Blue Dragon",
            hp=152,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 21, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 19, Ability.INTELLIGENCE.short_name: 14, Ability.WISDOM.short_name: 13, Ability.CHARISMA.short_name: 17},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Dragon (Chromatic), Lawful Evil",
            ac_note="",
            hp_formula="16d10 + 64",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Darkvision 120 ft., Passive Perception 19",
            languages="Common, Draconic",
            traits=[],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks.'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +9, reach 10 ft. Hit: 12 (2d6 + 5) Slashing damage plus 5 (1d10) Lightning damage.'),
            MonsterAbility(name='Lightning Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 16, each creature in a 60-foot-long, 5-foot-wide Line. Failure: 55 (10d10) Lightning damage. Success: Half damage.'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class YoungSilverDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Young Silver Dragon",
            hp=168,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 23, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 21, Ability.INTELLIGENCE.short_name: 14, Ability.WISDOM.short_name: 11, Ability.CHARISMA.short_name: 19},
            saving_throws={},
            spell_slots={},
            cr="9",
            monster_type="Large Dragon (Metallic), Lawful Good",
            ac_note="",
            hp_formula="16d10 + 80",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Darkvision 120 ft., Passive Perception 18",
            languages="Common, Draconic",
            traits=[],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of Paralyzing Breath.'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +10, reach 10 ft. Hit: 15 (2d8 + 6) Slashing damage.'),
            MonsterAbility(name='Cold Breath (Recharge 5–6)', description='Constitution Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: 49 (11d8) Cold damage. Success: Half damage.'),
            MonsterAbility(name='Paralyzing Breath', description='Constitution Saving Throw: DC 17, each creature in a 30-foot Cone. First Failure: The target has the Incapacitated condition until the end of its next turn, when it repeats the save. Second Failure: The target has the Paralyzed condition, and it repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = [
    "AbominableYeti",
    "BoneDevil",
    "BrazenGorgon",
    "ClayGolem",
    "CloudGiant",
    "FireGiant",
    "Glabrezu",
    "GraySlaad",
    "Nycaloth",
    "Treant",
    "YoungBlueDragon",
    "YoungSilverDragon",
]
