# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import ExtendedCombatantData


class AncientBlueDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Ancient Blue Dragon",
            hp=481,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 29, "Dex": 10, "Con": 27, "Int": 18, "Wis": 17, "Cha": 25},
            saving_throws={},
            spell_slots={},
            cr="23",
            monster_type="Gargantuan Dragon (Chromatic), Lawful Evil",
            ac_note="",
            hp_formula="26d20 + 208",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 27",
            languages="Common, Draconic",
            traits=[
            {"name": "Legendary Resistance (4/Day, or 5/Day in Lair)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Shatter (level 3 version)."},
            {"name": "Rend", "description": "Melee Attack Roll: +16, reach 15 ft. Hit: 18 (2d8 + 9) Slashing damage plus 11 (2d10) Lightning damage."},
            {"name": "Lightning Breath (Recharge 5–6)", "description": "Dexterity Saving Throw: DC 23, each creature in a 120-foot-long, 10-foot-wide Line. Failure: 88 (16d10) Lightning damage. Success: Half damage."},
            {"name": "Spellcasting", "description": "The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 22):"},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            {"name": "Cloaked Flight", "description": "The dragon uses Spellcasting to cast Invisibility on itself, and it can fly up to half its Fly Speed. The dragon can't take this action again until the start of its next turn."},
            {"name": "Sonic Boom", "description": "The dragon uses Spellcasting to cast Shatter (level 3 version). The dragon can't take this action again until the start of its next turn."},
            {"name": "Tail Swipe", "description": "The dragon makes one Rend attack."},
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class AncientSilverDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Ancient Silver Dragon",
            hp=468,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 30, "Dex": 10, "Con": 29, "Int": 18, "Wis": 15, "Cha": 26},
            saving_throws={},
            spell_slots={},
            cr="23",
            monster_type="Gargantuan Dragon (Metallic), Lawful Good",
            ac_note="",
            hp_formula="24d20 + 216",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 26",
            languages="Common, Draconic",
            traits=[
            {"name": "Legendary Resistance (4/Day, or 5/Day in Lair)", "description": "If the dragon fails a saving throw, it can choose to succeed instead."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The dragon makes three Rend attacks. It can replace one attack with a use of (A) Paralyzing Breath or (B) Spellcasting to cast Ice Knife (level 2 version)."},
            {"name": "Rend", "description": "Melee Attack Roll: +17, reach 15 ft. Hit: 19 (2d8 + 10) Slashing damage plus 9 (2d8) Cold damage."},
            {"name": "Cold Breath (Recharge 5–6)", "description": "Constitution Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 67 (15d8) Cold damage. Success: Half damage."},
            {"name": "Paralyzing Breath", "description": "Constitution Saving Throw: DC 24, each creature in a 90-foot Cone. First Failure: The target has the Incapacitated condition until the end of its next turn, when it repeats the save. Second Failure: The target has the Paralyzed condition, and it repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."},
            {"name": "Spellcasting", "description": "The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 23, +15 to hit with spell attacks):"},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            {"name": "Chill", "description": "The dragon uses Spellcasting to cast Hold Monster. The dragon can't take this action again until the start of its next turn."},
            {"name": "Cold Gale", "description": "Dexterity Saving Throw: DC 23, each creature in a 60-foot-long, 10-foot-wide Line. Failure: 14 (4d6) Cold damage, and the target is pushed up to 30 feet straight away from the dragon. Success: Half damage only. Failure or Success: The dragon can't take this action again until the start of its next turn."},
            {"name": "Pounce", "description": "The dragon moves up to half its Speed, and it makes one Rend attack."},
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class BlobOfAnnihilation(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Blob of Annihilation",
            hp=448,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 27, "Dex": 14, "Con": 28, "Int": 10, "Wis": 16, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="23",
            monster_type="Gargantuan Ooze (Titan), Neutral Evil",
            ac_note="",
            hp_formula="23d20 + 207",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 120 ft., Passive Perception 13",
            languages="—",
            traits=[],
            actions=[],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Empyrean(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Empyrean",
            hp=346,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 30, "Dex": 21, "Con": 30, "Int": 21, "Wis": 22, "Cha": 27},
            saving_throws={},
            spell_slots={},
            cr="23",
            monster_type="Huge Celestial or Fiend (Titan), Neutral",
            ac_note="",
            hp_formula="21d12 + 210",
            speed="50 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 23",
            languages="All",
            traits=[
            {"name": "Legendary Resistance (4/Day)", "description": "If the empyrean fails a saving throw, it can choose to succeed instead."},
            {"name": "Magic Resistance", "description": "The empyrean has Advantage on saving throws against spells and other magical effects."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The empyrean makes two attacks, using Sacred Weapon or Divine Ray in any combination."},
            {"name": "Sacred Weapon", "description": "Melee Attack Roll: +17, reach 10 ft. Hit: 31 (6d6 + 10) Force damage, and the target has the Stunned condition until the start of the empyrean's next turn. The target can choose not to be Stunned, in which case it takes an extra 21 Force damage that bypasses Resistance or Immunity."},
            {"name": "Divine Ray", "description": "Ranged Attack Roll: +15, range 600 ft. Hit: 35 (6d8 + 8) Necrotic or Radiant damage (empyrean's choice)."},
            {"name": "Spellcasting", "description": "The empyrean casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 23):"},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            {"name": "Bolster", "description": "The empyrean gains 10 Temporary Hit Points, and the empyrean and each ally within 30 feet of it gain Advantage on D20 Tests until the end of the empyrean's next turn. The empyrean can't take this action again until the start of its next turn."},
            {"name": "Shockwave of Glory", "description": "Constitution Saving Throw: DC 23, each creature in a 30-foot Emanation originating from the empyrean. Failure: 27 (6d8) Force damage, and the target has the Prone condition. Success: Half damage only. Failure or Success: The empyrean can't take this action again until the start of its next turn."},
            {"name": "Smite", "description": "The empyrean makes one Divine Ray attack."},
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class Kraken(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Kraken",
            hp=481,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 30, "Dex": 11, "Con": 26, "Int": 22, "Wis": 18, "Cha": 20},
            saving_throws={},
            spell_slots={},
            cr="23",
            monster_type="Gargantuan Monstrosity (Titan), Chaotic Evil",
            ac_note="",
            hp_formula="26d20 + 208",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 21",
            languages="Understands Abyssal, Celestial, Infernal, and Primordial but can't speak; telepathy 120 ft.",
            traits=[
            {"name": "Amphibious", "description": "The kraken can breathe air and water."},
            {"name": "Legendary Resistance (4/Day, or 5/Day in Lair)", "description": "If the kraken fails a saving throw, it can choose to succeed instead."},
            {"name": "Siege Monster", "description": "The kraken deals double damage to objects and structures."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The kraken makes two Tentacle attacks and uses Fling, Lightning Strike, or Swallow."},
            {"name": "Tentacle", "description": "Melee Attack Roll: +17, reach 30 ft. Hit: 24 (4d6 + 10) Bludgeoning damage. The target has the Grappled condition (escape DC 20) from one of ten tentacles, and it has the Restrained condition until the grapple ends."},
            {"name": "Fling", "description": "The kraken throws a Large or smaller creature Grappled by it to a space it can see within 60 feet of itself that isn't in the air. Dexterity Saving Throw: DC 25, the creature thrown and each creature in the destination space. Failure: 18 (4d8) Bludgeoning damage, and the target has the Prone condition. Success: Half damage only."},
            {"name": "Lightning Strike", "description": "Dexterity Saving Throw: DC 23, one creature the kraken can see within 120 feet. Failure: 33 (6d10) Lightning damage. Success: Half damage."},
            {"name": "Swallow", "description": "Dexterity Saving Throw: DC 25, one creature Grappled by the kraken (it can have up to four creatures swallowed at a time). Failure: 23 (3d8 + 10) Piercing damage. If the target is Large or smaller, it is swallowed and no longer Grappled. A swallowed creature has the Restrained condition, has Total Cover against attacks and other effects outside the kraken, and takes 24 (7d6) Acid damage at the start of each of its turns. If the kraken takes 50 damage or more on a single turn from a creature inside it, the kraken must succeed on a DC 25 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, each of which falls in a space within 10 feet of the kraken with the Prone condition. If the kraken dies, any swallowed creature no longer has the Restrained condition and can escape from the corpse using 15 feet of movement, exiting Prone."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            {"name": "Storm Bolt", "description": "The kraken uses Lightning Strike."},
            {"name": "Toxic Ink", "description": "Constitution Saving Throw: DC 23, each creature in a 15-foot Emanation originating from the kraken while it is underwater. Failure: The target has the Blinded and Poisoned conditions until the end of the kraken's next turn. The kraken then moves up to its Speed. Failure or Success: The kraken can't take this action again until the start of its next turn."},
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['AncientBlueDragon', 'AncientSilverDragon', 'BlobOfAnnihilation', 'Empyrean', 'Kraken']
