# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    MonsterType,
    Size,
    Skill,
)
from Core.Definitions import Ability


class AncientBronzeDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Bronze Dragon",
            hp=444,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH: 29, Ability.DEXTERITY: 10, Ability.CONSTITUTION: 27, Ability.INTELLIGENCE: 18, Ability.WISDOM: 17, Ability.CHARISMA: 25},
            saving_throws={Ability.DEXTERITY: 7, Ability.WISDOM: 10},
            spell_slots={},
            cr="22",
            monster_type=MonsterType.DRAGON, monster_type_note='Metallic',
            alignment=Alignment.LAWFUL_GOOD,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="24d20 + 192",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.INSIGHT: 10, Skill.PERCEPTION: 17, Skill.STEALTH: 7},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.LIGHTNING], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 27",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of (A) Repulsion Breath or (B) Spellcasting to cast Guiding Bolt (level 2 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +16, reach 15 ft. Hit: 18 (2d8 + 9) Slashing damage plus 9 (2d8) Lightning damage.'),
            MonsterAbility(name='Lightning Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 23, each creature in a 120-foot-long, 10-foot-wide Line. Failure: 82 (15d10) Lightning damage. Success: Half damage.'),
            MonsterAbility(name='Repulsion Breath', description='Strength Saving Throw: DC 23, each creature in a 30-foot Cone. Failure: The target is pushed up to 60 feet straight away from the dragon and has the Prone condition.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 22, +14 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Guiding Light', description='The dragon uses Spellcasting to cast Guiding Bolt (level 2 version).'),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
            MonsterAbility(name='Thunderclap', description='Constitution Saving Throw: DC 22, each creature in a 20-foot-radius Sphere centered on a point the dragon can see within 120 feet. Failure: 13 (3d8) Thunder damage, and the target has the Deafened condition until the end of its next turn.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class AncientGreenDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Green Dragon",
            hp=402,
            ac=21,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH: 27, Ability.DEXTERITY: 12, Ability.CONSTITUTION: 25, Ability.INTELLIGENCE: 20, Ability.WISDOM: 17, Ability.CHARISMA: 22},
            saving_throws={Ability.DEXTERITY: 8, Ability.WISDOM: 10},
            spell_slots={},
            cr="22",
            monster_type=MonsterType.DRAGON, monster_type_note='Chromatic',
            alignment=Alignment.LAWFUL_EVIL,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="23d20 + 161",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.DECEPTION: 13, Skill.PERCEPTION: 17, Skill.PERSUASION: 13, Skill.STEALTH: 8},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
            ],
            condition_immunities=[Condition.POISONED],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 27",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Mind Spike (level 5 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +15, reach 15 ft. Hit: 17 (2d8 + 8) Slashing damage plus 10 (3d6) Poison damage.'),
            MonsterAbility(name='Poison Breath (Recharge 5–6)', description='Constitution Saving Throw: DC 22, each creature in a 90-foot Cone. Failure: 77 (22d6) Poison damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 21):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Mind Invasion', description='The dragon uses Spellcasting to cast Mind Spike (level 5 version).'),
            MonsterAbility(name='Noxious Miasma', description="Constitution Saving Throw: DC 21, each creature in a 30-foot-radius Sphere centered on a point the dragon can see within 90 feet. Failure: 17 (5d6) Poison damage, and the target takes a -2 penalty to AC until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class ElementalCataclysm(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Elemental Cataclysm",
            hp=370,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH: 26, Ability.DEXTERITY: 19, Ability.CONSTITUTION: 27, Ability.INTELLIGENCE: 9, Ability.WISDOM: 14, Ability.CHARISMA: 9},
            saving_throws={Ability.DEXTERITY: 11, Ability.CONSTITUTION: 15, Ability.WISDOM: 9, Ability.CHARISMA: 6},
            spell_slots={},
            cr="22",
            monster_type=MonsterType.ELEMENTAL, monster_type_note='Titan',
            alignment=Alignment.CHAOTIC_NEUTRAL,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="20d20 + 160",
            speed_ground_ft=60,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='burrow 60 ft.; hover; swim 80 ft.',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.ACID], note=''),
                DamageTypeEntry(damage_types=[DamageType.COLD], note=''),
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
                DamageTypeEntry(damage_types=[DamageType.LIGHTNING], note=''),
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
                DamageTypeEntry(damage_types=[DamageType.THUNDER], note=''),
            ],
            condition_immunities=[Condition.BLINDED, Condition.CHARMED, Condition.DEAFENED, Condition.EXHAUSTION, Condition.FRIGHTENED, Condition.GRAPPLED, Condition.PARALYZED, Condition.PETRIFIED, Condition.POISONED, Condition.PRONE, Condition.RESTRAINED, Condition.STUNNED, Condition.UNCONSCIOUS],
            senses="Truesight 150 ft., Passive Perception 12",
            languages="Primordial",
            traits=[],
            actions=[],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['AncientBronzeDragon', 'AncientGreenDragon', 'ElementalCataclysm']
