# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    Size,
    Skill,
)
from Core.Definitions import Ability


class AdultBronzeDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Bronze Dragon",
            hp=212,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 25, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 23, Ability.INTELLIGENCE.short_name: 16, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 20},
            saving_throws={Ability.DEXTERITY.short_name: 5, Ability.WISDOM.short_name: 7},
            spell_slots={},
            cr="15",
            monster_type='Dragon (Metallic)',
            alignment=Alignment.LAWFUL_GOOD,
            size=Size.HUGE,
            ac_note="",
            hp_formula="17d12 + 102",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.INSIGHT: 7, Skill.PERCEPTION: 12, Skill.STEALTH: 5},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.LIGHTNING], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 22",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of (A) Repulsion Breath or (B) Spellcasting to cast Guiding Bolt (level 2 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +12, reach 10 ft. Hit: 16 (2d8 + 7) Slashing damage plus 5 (1d10) Lightning damage.'),
            MonsterAbility(name='Lightning Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 19, each creature in a 90-foot-long, 5-foot-wide Line. Failure: 55 (10d10) Lightning damage. Success: Half damage.'),
            MonsterAbility(name='Repulsion Breath', description='Strength Saving Throw: DC 19, each creature in a 30-foot Cone. Failure: The target is pushed up to 60 feet straight away from the dragon and has the Prone condition.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 17, +10 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Guiding Light', description='The dragon uses Spellcasting to cast Guiding Bolt (level 2 version).'),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
            MonsterAbility(name='Thunderclap', description='Constitution Saving Throw: DC 17, each creature in a 20-foot-radius Sphere centered on a point the dragon can see within 90 feet. Failure: 10 (3d6) Thunder damage, and the target has the Deafened condition until the end of its next turn.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class AdultGreenDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Green Dragon",
            hp=207,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 23, Ability.DEXTERITY.short_name: 12, Ability.CONSTITUTION.short_name: 21, Ability.INTELLIGENCE.short_name: 18, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 18},
            saving_throws={Ability.DEXTERITY.short_name: 6, Ability.WISDOM.short_name: 7},
            spell_slots={},
            cr="15",
            monster_type='Dragon (Chromatic)',
            alignment=Alignment.LAWFUL_EVIL,
            size=Size.HUGE,
            ac_note="",
            hp_formula="18d12 + 90",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.DECEPTION: 9, Skill.PERCEPTION: 12, Skill.PERSUASION: 9, Skill.STEALTH: 6},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
            ],
            condition_immunities=[Condition.POISONED],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 22",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Mind Spike (level 3 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +11, reach 10 ft. Hit: 15 (2d8 + 6) Slashing damage plus 7 (2d6) Poison damage.'),
            MonsterAbility(name='Poison Breath (Recharge 5–6)', description='Constitution Saving Throw: DC 18, each creature in a 60-foot Cone. Failure: 56 (16d6) Poison damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 17):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Mind Invasion', description='The dragon uses Spellcasting to cast Mind Spike (level 3 version).'),
            MonsterAbility(name='Noxious Miasma', description="Constitution Saving Throw: DC 17, each creature in a 20-foot-radius Sphere centered on a point the dragon can see within 90 feet. Failure: 7 (2d6) Poison damage, and the target takes a −2 penalty to AC until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class MummyLord(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Mummy Lord",
            hp=187,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 18, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 17, Ability.INTELLIGENCE.short_name: 11, Ability.WISDOM.short_name: 19, Ability.CHARISMA.short_name: 16},
            saving_throws={Ability.INTELLIGENCE.short_name: 5, Ability.WISDOM.short_name: 9},
            spell_slots={},
            cr="15",
            monster_type='Undead (Cleric)',
            alignment=Alignment.LAWFUL_EVIL,
            size=Size.MEDIUM,
            ac_note="",
            hp_formula="25d8 + 75",
            speed_ground_ft=30,
            speed_fly_ft=None,
            speed_climb_ft=None,
            speed_special_rules='',
            skills={Skill.HISTORY: 5, Skill.PERCEPTION: 9, Skill.RELIGION: 5},
            damage_vulnerabilities=[
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
            ],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.NECROTIC], note=''),
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
            ],
            condition_immunities=[Condition.CHARMED, Condition.EXHAUSTION, Condition.FRIGHTENED, Condition.PARALYZED, Condition.POISONED],
            senses="Truesight 60 ft., Passive Perception 19",
            languages="Common plus three other languages",
            traits=[
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the mummy fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Magic Resistance', description='The mummy has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Undead Restoration', description="If destroyed, the mummy gains a new body in 24 hours if its heart is intact, reviving with all its Hit Points. The new body appears in an unoccupied space within the mummy's lair. The heart is a Tiny object that has AC 17, HP 10, and Immunity to all damage except Fire."),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The mummy makes one Rotting Fist or Channel Negative Energy attack, and it uses Dreadful Glare.'),
            MonsterAbility(name='Rotting Fist', description="Melee Attack Roll: +9, reach 5 ft. Hit: 15 (2d10 + 4) Bludgeoning damage plus 10 (3d6) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target can't regain Hit Points, it gains no benefit from finishing a Long Rest, and its Hit Point maximum decreases by 10 (3d6) every 24 hours that elapse. A creature dies and turns to dust if reduced to 0 Hit Points by this attack."),
            MonsterAbility(name='Channel Negative Energy', description='Ranged Attack Roll: +9, range 60 ft. Hit: 25 (6d6 + 4) Necrotic damage.'),
            MonsterAbility(name='Dreadful Glare', description="Wisdom Saving Throw: DC 17, one creature the mummy can see within 60 feet. Failure: 25 (6d6 + 4) Psychic damage, and the target has the Paralyzed condition until the end of the mummy's next turn."),
            MonsterAbility(name='Spellcasting', description='The mummy casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 17, +9 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[
            MonsterAbility(name='Whirlwind of Sand', description="Trigger: The mummy is hit by an attack roll. Response: The mummy adds 2 to its AC against the attack, possibly causing the attack to miss, and the mummy teleports up to 60 feet to an unoccupied space it can see. Each creature of its choice that it can see within 5 feet of its destination space has the Blinded condition until the end of the mummy's next turn."),
        ],
            legendary_actions=[
            MonsterAbility(name='Dread Command', description="The mummy casts Command (level 2 version), using the same spellcasting ability as Spellcasting. The mummy can't take this action again until the start of its next turn."),
            MonsterAbility(name='Glare', description="The mummy uses Dreadful Glare. The mummy can't take this action again until the start of its next turn."),
            MonsterAbility(name='Necrotic Strike', description='The mummy makes one Rotting Fist or Channel Negative Energy attack'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class PurpleWorm(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Purple Worm",
            hp=247,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 28, Ability.DEXTERITY.short_name: 7, Ability.CONSTITUTION.short_name: 22, Ability.INTELLIGENCE.short_name: 1, Ability.WISDOM.short_name: 8, Ability.CHARISMA.short_name: 4},
            saving_throws={Ability.CONSTITUTION.short_name: 11, Ability.WISDOM.short_name: 4},
            spell_slots={},
            cr="15",
            monster_type='Monstrosity',
            alignment=Alignment.UNALIGNED,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="15d20 + 90",
            speed_ground_ft=50,
            speed_fly_ft=None,
            speed_climb_ft=None,
            speed_special_rules='burrow 50 ft.',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Tremorsense 60 ft., Passive Perception 9",
            languages="—",
            traits=[
            MonsterAbility(name='Tunneler', description='The worm can burrow through solid rock at half its Burrow Speed and leaves a 10-foot-diameter tunnel in its wake.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The worm makes one Bite attack and one Tail Stinger attack.'),
            MonsterAbility(name='Bite', description='Melee Attack Roll: +14, reach 10 ft. Hit: 22 (3d8 + 9) Piercing damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 19), and it has the Restrained condition until the grapple ends.'),
            MonsterAbility(name='Tail Stinger', description='Melee Attack Roll: +14, reach 10 ft. Hit: 16 (2d6 + 9) Piercing damage plus 35 (10d6) Poison damage.'),
        ],
            bonus_actions=[
            MonsterAbility(name='Swallow', description="Strength Saving Throw: DC 19, one Large or smaller creature Grappled by the worm (it can have up to three creatures swallowed at a time). Failure: The target is swallowed by the worm, and the Grappled condition ends. A swallowed creature has the Blinded and Restrained conditions, has Total Cover against attacks and other effects outside the worm, and takes 17 (5d6) Acid damage at the start of each of the worm's turns. If the worm takes 30 damage or more on a single turn from a creature inside it, the worm must succeed on a DC 21 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, each of which falls in a space within 5 feet of the worm and has the Prone condition. If the worm dies, any swallowed creature no longer has the Restrained condition and can escape from the corpse using 20 feet of movement, exiting Prone."),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class SalamanderInfernoMaster(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Salamander Inferno Master",
            hp=256,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 24, Ability.DEXTERITY.short_name: 16, Ability.CONSTITUTION.short_name: 18, Ability.INTELLIGENCE.short_name: 14, Ability.WISDOM.short_name: 10, Ability.CHARISMA.short_name: 20},
            saving_throws={Ability.DEXTERITY.short_name: 8, Ability.WISDOM.short_name: 5},
            spell_slots={},
            cr="15",
            monster_type='Elemental',
            alignment=Alignment.NEUTRAL_EVIL,
            size=Size.LARGE,
            ac_note="",
            hp_formula="27d10 + 108",
            speed_ground_ft=40,
            speed_fly_ft=None,
            speed_climb_ft=40,
            speed_special_rules='',
            skills={},
            damage_vulnerabilities=[
                DamageTypeEntry(damage_types=[DamageType.COLD], note=''),
            ],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
            ],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 10",
            languages="Primordial (Ignan)",
            traits=[
            MonsterAbility(name='Fire Aura', description="At the end of each of the salamander's turns, each creature of the salamander's choice in a 10-foot Emanation originating from the salamander takes 10 (3d6) Fire damage."),
            MonsterAbility(name='Magic Resistance', description='The salamander has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The salamander makes two Flame Trident attacks.'),
            MonsterAbility(name='Flame Trident', description="Melee or Ranged Attack Roll: +12, reach 5 ft. or range 30/90 ft. Hit: 16 (2d8 + 7) Piercing damage plus 14 (4d6) Fire damage. Hit or Miss: The trident magically returns to the salamander's hand immediately after a ranged attack."),
            MonsterAbility(name='Inferno Blast (Recharge 5–6)', description='Dexterity Saving Throw: DC 18, each creature in a 30-foot-radius Sphere centered on a point the salamander can see within 120 feet. Failure: 35 (10d6) Fire damage, and the target starts burning, taking 5 (1d10) Fire damage at the start of each of its turns instead of the normal burning damage. The target gains 1 Exhaustion level whenever it takes this burning damage. Success: Half damage only.'),
        ],
            bonus_actions=[
            MonsterAbility(name='Blazing Movement', description="The salamander moves up to its Speed without provoking Opportunity Attacks. During this movement, fire fills a 5-foot Emanation originating from the salamander. When the Emanation enters a creature's space, that creature takes 7 (2d6) Fire damage. A creature can take this damage only once per turn."),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class VampireUmbralLord(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Vampire Umbral Lord",
            hp=187,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 20, Ability.DEXTERITY.short_name: 18, Ability.CONSTITUTION.short_name: 18, Ability.INTELLIGENCE.short_name: 19, Ability.WISDOM.short_name: 16, Ability.CHARISMA.short_name: 21},
            saving_throws={Ability.STRENGTH.short_name: 10, Ability.DEXTERITY.short_name: 9, Ability.WISDOM.short_name: 8, Ability.CHARISMA.short_name: 10},
            spell_slots={},
            cr="15",
            monster_type='Undead',
            alignment=Alignment.LAWFUL_EVIL,
            size=Size.MEDIUM,
            ac_note="",
            hp_formula="22d8 + 88",
            speed_ground_ft=40,
            speed_fly_ft=40,
            speed_climb_ft=40,
            speed_special_rules='hover',
            skills={Skill.ARCANA: 9, Skill.PERCEPTION: 13, Skill.STEALTH: 9},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.COLD], note=''),
                DamageTypeEntry(damage_types=[DamageType.NECROTIC], note=''),
            ],
            condition_immunities=[Condition.CHARMED, Condition.EXHAUSTION],
            senses="Blindsight 120 ft., Passive Perception 23",
            languages="Common plus three other languages",
            traits=[
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the vampire fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Shadow Escape', description="If the vampire drops to 0 Hit Points outside its resting place, it teleports into its resting place unless it is in running water or sunlight. If it can't teleport, it is destroyed. Once inside its resting place, it has the Paralyzed condition for 1 hour, after which it regains 1 Hit Point."),
            MonsterAbility(name='Vampire Weakness', description='The vampire has these weaknesses:'),
            MonsterAbility(name='Forbiddance', description=". The vampire can't enter a residence without an invitation from an occupant."),
            MonsterAbility(name='Running Water', description='. The vampire takes 20 Acid damage if it ends its turn in running water.'),
            MonsterAbility(name='Stake to the Heart', description=". If a weapon that deals Piercing damage is driven into the vampire's heart while the vampire has the Incapacitated condition in its resting place, the vampire has the Paralyzed condition until the weapon is removed."),
            MonsterAbility(name='Sunlight', description='. The vampire takes 20 Radiant damage if it starts its turn in sunlight. While in sunlight, it has Disadvantage on attack rolls and ability checks.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The vampire makes two attacks, using Grave Strike or Sickening Ray in any combination.'),
            MonsterAbility(name='Grave Strike', description='Melee Attack Roll: +10, reach 5 ft. Hit: 9 (1d8 + 5) Slashing damage plus 13 (3d8) Necrotic damage.'),
            MonsterAbility(name='Hunger of Hadar (Recharge 5–6)', description='The vampire casts Hunger of Hadar (level 5 version), requiring no spell components and using Charisma as the spellcasting ability (spell save DC 18).'),
            MonsterAbility(name='Sickening Ray', description="Ranged Attack Roll: +10, range 120 ft. Hit: 16 (2d10 + 5) Necrotic damage, and the target has the Poisoned condition until the start of the vampire's next turn."),
        ],
            bonus_actions=[
            MonsterAbility(name='Sanguine Drain', description="Constitution Saving Throw: DC 18, one creature the vampire can see within 30 feet that isn't a Construct or an Undead. Failure: 14 (4d6) Necrotic damage. The target's Hit Point maximum decreases by an amount equal to the damage taken, and the vampire regains Hit Points equal to that amount."),
        ],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Beguile', description="The vampire casts Command, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 18). The vampire can't take this action again until the start of its next turn."),
            MonsterAbility(name='Umbral Strike', description='The vampire moves up to half its Speed, and it makes one Grave Strike or Sickening Ray attack.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['AdultBronzeDragon', 'AdultGreenDragon', 'MummyLord', 'PurpleWorm', 'SalamanderInfernoMaster', 'VampireUmbralLord']
