# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    ExtendedCombatantData,
    MonsterAbility,
    Size,
)
from Definitions import Ability


class AdultBrassDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Brass Dragon",
            hp=172,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 23,
                Ability.DEXTERITY.short_name: 10,
                Ability.CONSTITUTION.short_name: 21,
                Ability.INTELLIGENCE.short_name: 14,
                Ability.WISDOM.short_name: 13,
                Ability.CHARISMA.short_name: 17,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.HUGE, monster_type='Dragon (Metallic)', alignment=Alignment.CHAOTIC_GOOD,
            ac_note="",
            hp_formula="15d12 + 75",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 21",
            languages="Common, Draconic",
            traits=[
                MonsterAbility(
                    name="Legendary Resistance (3/Day, or 4/Day in Lair)",
                    description="If the dragon fails a saving throw, it can choose to succeed instead.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The dragon makes three Rend attacks. It can replace one attack with a use of (A) Sleep Breath or (B) Spellcasting to cast Scorching Ray.",
                ),
                MonsterAbility(
                    name="Rend",
                    description="Melee Attack Roll: +11, reach 10 ft. Hit: 17 (2d10 + 6) Slashing damage plus 4 (1d8) Fire damage.",
                ),
                MonsterAbility(
                    name="Fire Breath (Recharge 5–6)",
                    description="Dexterity Saving Throw: DC 18, each creature in a 60-foot-long, 5-foot-wide Line. Failure: 45 (10d8) Fire damage. Success: Half damage.",
                ),
                MonsterAbility(
                    name="Sleep Breath",
                    description="Constitution Saving Throw: DC 18, each creature in a 60-foot Cone. Failure: The target has the Incapacitated condition until the end of its next turn, at which point it repeats the save. Second Failure: The target has the Unconscious condition for 10 minutes. This effect ends for the target if it takes damage or a creature within 5 feet of it takes an action to wake it.",
                ),
                MonsterAbility(
                    name="Spellcasting",
                    description="The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 16):",
                ),
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
                MonsterAbility(
                    name="Blazing Light",
                    description="The dragon uses Spellcasting to cast Scorching Ray.",
                ),
                MonsterAbility(
                    name="Pounce",
                    description="The dragon moves up to half its Speed, and it makes one Rend attack.",
                ),
                MonsterAbility(
                    name="Scorching Sands",
                    description="Dexterity Saving Throw: DC 16, one creature the dragon can see within 120 feet. Failure: 27 (6d8) Fire damage, and the target's Speed is halved until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
                ),
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class AdultWhiteDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult White Dragon",
            hp=200,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 22,
                Ability.DEXTERITY.short_name: 10,
                Ability.CONSTITUTION.short_name: 22,
                Ability.INTELLIGENCE.short_name: 8,
                Ability.WISDOM.short_name: 12,
                Ability.CHARISMA.short_name: 12,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.HUGE, monster_type='Dragon (Chromatic)', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="16d12 + 96",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 21",
            languages="Common, Draconic",
            traits=[
                MonsterAbility(
                    name="Ice Walk",
                    description="The dragon can move across and climb icy surfaces without needing to make an ability check. Additionally, Difficult Terrain composed of ice or snow doesn't cost it extra movement.",
                ),
                MonsterAbility(
                    name="Legendary Resistance (3/Day, or 4/Day in Lair)",
                    description="If the dragon fails a saving throw, it can choose to succeed instead.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The dragon makes three Rend attacks.",
                ),
                MonsterAbility(
                    name="Rend",
                    description="Melee Attack Roll: +11, reach 10 ft. Hit: 13 (2d6 + 6) Slashing damage plus 4 (1d8) Cold damage.",
                ),
                MonsterAbility(
                    name="Cold Breath (Recharge 5–6)",
                    description="Constitution Saving Throw: DC 19, each creature in a 60-foot Cone. Failure: 54 (12d8) Cold damage. Success: Half damage.",
                ),
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
                MonsterAbility(
                    name="Freezing Burst",
                    description="Constitution Saving Throw: DC 14, each creature in a 30-foot-radius Sphere centered on a point the dragon can see within 120 feet. Failure: 7 (2d6) Cold damage, and the target's Speed is 0 until the end of the target's next turn. Failure or Success: The dragon can't take this action again until the start of its next turn.",
                ),
                MonsterAbility(
                    name="Frightful Presence",
                    description="The dragon casts Fear, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 14). The dragon can't take this action again until the start of its next turn.",
                ),
                MonsterAbility(
                    name="Pounce",
                    description="The dragon moves up to half its Speed, and it makes one Rend attack.",
                ),
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class Beholder(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Beholder",
            hp=190,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 16,
                Ability.DEXTERITY.short_name: 14,
                Ability.CONSTITUTION.short_name: 18,
                Ability.INTELLIGENCE.short_name: 17,
                Ability.WISDOM.short_name: 15,
                Ability.CHARISMA.short_name: 17,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.LARGE, monster_type='Aberration', alignment=Alignment.LAWFUL_EVIL,
            ac_note="",
            hp_formula="20d10 + 80",
            speed_ground_ft=5, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 22",
            languages="Deep Speech, Undercommon",
            traits=[],
            actions=[],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Nalfeshnee(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Nalfeshnee",
            hp=184,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 21,
                Ability.DEXTERITY.short_name: 10,
                Ability.CONSTITUTION.short_name: 22,
                Ability.INTELLIGENCE.short_name: 19,
                Ability.WISDOM.short_name: 12,
                Ability.CHARISMA.short_name: 15,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.LARGE, monster_type='Fiend (Demon)', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="16d10 + 96",
            speed_ground_ft=20, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 11",
            languages="Abyssal; telepathy 120 ft.",
            traits=[
                MonsterAbility(
                    name="Demonic Restoration",
                    description="If the nalfeshnee dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss.",
                ),
                MonsterAbility(
                    name="Magic Resistance",
                    description="The nalfeshnee has Advantage on saving throws against spells and other magical effects.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The nalfeshnee makes three Rend attacks.",
                ),
                MonsterAbility(
                    name="Rend",
                    description="Melee Attack Roll: +10, reach 10 ft. Hit: 16 (2d10 + 5) Slashing damage plus 11 (2d10) Force damage.",
                ),
                MonsterAbility(
                    name="Teleport",
                    description="The nalfeshnee teleports up to 120 feet to an unoccupied space it can see.",
                ),
                MonsterAbility(
                    name="Pursuit",
                    description="Trigger: Another creature the nalfeshnee can see ends its move within 120 feet of the nalfeshnee. Response: The nalfeshnee uses Teleport, but its destination space must be within 10 feet of the triggering creature.",
                ),
            ],
            bonus_actions=[
                MonsterAbility(
                    name="Horror Nimbus (Recharge 5–6)",
                    description="Wisdom Saving Throw: DC 15, each creature in a 15-foot Emanation originating from the nalfeshnee. Failure: 28 (8d6) Psychic damage, and the target has the Frightened condition for 1 minute, until it takes damage, or until it ends its turn with the nalfeshnee out of line of sight. Success: The target is immune to this nalfeshnee's Horror Nimbus for 24 hours.",
                ),
            ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Rakshasa(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Rakshasa",
            hp=221,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 14,
                Ability.DEXTERITY.short_name: 17,
                Ability.CONSTITUTION.short_name: 18,
                Ability.INTELLIGENCE.short_name: 13,
                Ability.WISDOM.short_name: 16,
                Ability.CHARISMA.short_name: 20,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.MEDIUM, monster_type='Fiend', alignment=Alignment.LAWFUL_EVIL,
            ac_note="",
            hp_formula="26d8 + 104",
            speed_ground_ft=None, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 60 ft., Passive Perception 18",
            languages="Common, Infernal",
            traits=[
                MonsterAbility(
                    name="Greater Magic Resistance",
                    description="The rakshasa automatically succeeds on saving throws against spells and other magical effects, and the attack rolls of spells automatically miss it. Without the rakshasa's permission, no spell can observe the rakshasa remotely or detect its thoughts, creature type, or alignment.",
                ),
                MonsterAbility(
                    name="Fiendish Restoration",
                    description="If the rakshasa dies outside the Nine Hells, its body turns to ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Nine Hells.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The rakshasa makes three Cursed Touch attacks.",
                ),
                MonsterAbility(
                    name="Cursed Touch",
                    description="Melee Attack Roll: +10, reach 5 ft. Hit: 12 (2d6 + 5) Slashing damage plus 19 (3d12) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target gains no benefit from finishing a Short or Long Rest.",
                ),
                MonsterAbility(
                    name="Baleful Command (Recharge 5–6)",
                    description="Wisdom Saving Throw: DC 18, each enemy in a 30-foot Emanation originating from the rakshasa. Failure: 28 (8d6) Psychic damage, and the target has the Frightened and Incapacitated conditions until the start of the rakshasa's next turn.",
                ),
                MonsterAbility(
                    name="Spellcasting",
                    description="The rakshasa casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 18):",
                ),
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class ShadowDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Shadow Dragon",
            hp=189,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 21,
                Ability.DEXTERITY.short_name: 19,
                Ability.CONSTITUTION.short_name: 18,
                Ability.INTELLIGENCE.short_name: 14,
                Ability.WISDOM.short_name: 12,
                Ability.CHARISMA.short_name: 18,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.HUGE, monster_type='Dragon', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="18d12 + 72",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Darkvision 120 ft., Passive Perception 21",
            languages="Common, Draconic",
            traits=[
                MonsterAbility(
                    name="Legendary Resistance (3/Day, or 4/Day in Lair)",
                    description="If the dragon fails a saving throw, it can choose to succeed instead.",
                ),
                MonsterAbility(
                    name="Living Shadow",
                    description="While in Dim Light or Darkness, the dragon has Resistance to damage that isn't Force, Psychic, or Radiant.",
                ),
                MonsterAbility(
                    name="Sunlight Sensitivity",
                    description="While in sunlight, the dragon has Disadvantage on ability checks and attack rolls.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The dragon makes three Rend attacks.",
                ),
                MonsterAbility(
                    name="Rend",
                    description="Melee Attack Roll: +10, reach 10 ft. Hit: 12 (2d6 + 5) Slashing damage plus 3 (1d6) Necrotic damage.",
                ),
                MonsterAbility(
                    name="Shadow Breath (Recharge 5–6)",
                    description="Dexterity Saving Throw: DC 17, each creature in a 60-foot Cone. Failure: 35 (10d6) Necrotic damage. Success: Half damage. Failure or Success: A Humanoid reduced to 0 Hit Points by this damage dies, and a Shadow rises from the corpse. The shadow is under the dragon's control and shares the dragon's Initiative count but acts immediately after the dragon.",
                ),
            ],
            bonus_actions=[
                MonsterAbility(
                    name="Shadow Stealth",
                    description="While in Dim Light or Darkness, the dragon takes the Hide action.",
                ),
            ],
            reactions=[],
            legendary_actions=[
                MonsterAbility(
                    name="Pounce",
                    description="The dragon moves up to half its Speed, and it makes one Rend attack.",
                ),
                MonsterAbility(
                    name="Veil of Shadow",
                    description="The dragon uses Shadow Stealth, and one creature of its choice that it can see within 10 feet of it takes 10 (3d6) Necrotic damage. The dragon can't take this action again until the start of its next turn.",
                ),
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class StormGiant(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Storm Giant",
            hp=230,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 29,
                Ability.DEXTERITY.short_name: 14,
                Ability.CONSTITUTION.short_name: 20,
                Ability.INTELLIGENCE.short_name: 16,
                Ability.WISDOM.short_name: 20,
                Ability.CHARISMA.short_name: 18,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.HUGE, monster_type='Giant', alignment=Alignment.CHAOTIC_GOOD,
            ac_note="",
            hp_formula="20d12 + 100",
            speed_ground_ft=50, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Truesight 30 ft., Passive Perception 20",
            languages="Common, Giant",
            traits=[
                MonsterAbility(
                    name="Amphibious",
                    description="The giant can breathe air and water.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The giant makes two attacks, using Storm Sword or Thunderbolt in any combination.",
                ),
                MonsterAbility(
                    name="Storm Sword",
                    description="Melee Attack Roll: +14, reach 10 ft. Hit: 23 (4d6 + 9) Slashing damage plus 13 (3d8) Lightning damage.",
                ),
                MonsterAbility(
                    name="Thunderbolt",
                    description="Ranged Attack Roll: +14, range 500 ft. Hit: 22 (2d12 + 9) Lightning damage, and the target has the Blinded and Deafened conditions until the start of the giant's next turn.",
                ),
                MonsterAbility(
                    name="Lightning Storm (Recharge 5–6)",
                    description="Dexterity Saving Throw: DC 18, each creature in a 10-foot-radius, 40-foot-high Cylinder originating from a point the giant can see within 500 feet. Failure: 55 (10d10) Lightning damage. Success: Half damage.",
                ),
                MonsterAbility(
                    name="Spellcasting",
                    description="The giant casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 18):",
                ),
            ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Ultroloth(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ultroloth",
            hp=221,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 19,
                Ability.DEXTERITY.short_name: 16,
                Ability.CONSTITUTION.short_name: 18,
                Ability.INTELLIGENCE.short_name: 19,
                Ability.WISDOM.short_name: 15,
                Ability.CHARISMA.short_name: 18,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.MEDIUM, monster_type='Fiend (Yugoloth)', alignment=Alignment.NEUTRAL_EVIL,
            ac_note="",
            hp_formula="26d8 + 104",
            speed_ground_ft=30, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 17",
            languages="Abyssal, Infernal; telepathy 120 ft.",
            traits=[
                MonsterAbility(
                    name="Fiendish Restoration",
                    description="If the ultroloth dies outside Gehenna, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in Gehenna.",
                ),
                MonsterAbility(
                    name="Magic Resistance",
                    description="The ultroloth has Advantage on saving throws against spells and other magical effects.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack",
                    description="The ultroloth uses Hypnotic Gaze and makes two Mercurial Whip attacks.",
                ),
                MonsterAbility(
                    name="Mercurial Whip",
                    description="Melee Attack Roll: +9, reach 15 ft. Hit: 25 (6d6 + 4) Force damage, and the ultroloth can teleport the target up to 10 feet to an unoccupied space the ultroloth can see that isn't in the air.",
                ),
                MonsterAbility(
                    name="Hypnotic Gaze",
                    description="Wisdom Saving Throw: DC 17, each creature in a 30-foot Cone. Failure: 10 (3d6) Psychic damage, and the target has the Stunned condition until the start of the ultroloth's next turn. Success: The target is immune to this ultroloth's Hypnotic Gaze for 24 hours.",
                ),
                MonsterAbility(
                    name="Spellcasting",
                    description="The ultroloth casts one of the following spells, requiring no Material components and using Intelligence as the spellcasting ability (spell save DC 17):",
                ),
            ],
            bonus_actions=[
                MonsterAbility(
                    name="Fiendish Guile (Recharge 4–6)",
                    description="The ultroloth casts Dispel Magic, Invisibility (self only), Misty Step, or Suggestion, requiring no Material components and using the same spellcasting ability as Spellcasting.",
                ),
            ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Vampire(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Vampire",
            hp=195,
            ac=16,
            temp_hp=0,
            conditions=[],
            ability_scores={
                Ability.STRENGTH.short_name: 18,
                Ability.DEXTERITY.short_name: 18,
                Ability.CONSTITUTION.short_name: 18,
                Ability.INTELLIGENCE.short_name: 17,
                Ability.WISDOM.short_name: 15,
                Ability.CHARISMA.short_name: 18,
            },
            saving_throws={},
            spell_slots={},
            cr="13",
            size=Size.MEDIUM, monster_type='Undead', alignment=Alignment.LAWFUL_EVIL,
            ac_note="",
            hp_formula="23d8 + 92",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 17",
            languages="Common plus two other languages",
            traits=[
                MonsterAbility(
                    name="Legendary Resistance (3/Day, or 4/Day in Lair)",
                    description="If the vampire fails a saving throw, it can choose to succeed instead.",
                ),
                MonsterAbility(
                    name="Misty Escape",
                    description="If the vampire drops to 0 Hit Points outside its resting place, the vampire uses Shape-Shift to become mist (no action required). If it can't use Shape-Shift, it is destroyed. While it has 0 Hit Points in mist form, it can't return to its vampire form, and it must reach its resting place within 2 hours or be destroyed. Once in its resting place, it returns to its vampire form and has the Paralyzed condition until it regains any Hit Points, and it regains 1 Hit Point after spending 1 hour there.",
                ),
                MonsterAbility(
                    name="Spider Climb",
                    description="The vampire can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
                ),
                MonsterAbility(
                    name="Vampire Weakness",
                    description="The vampire has these weaknesses:",
                ),
                MonsterAbility(
                    name="Forbiddance",
                    description=". The vampire can't enter a residence without an invitation from an occupant.",
                ),
                MonsterAbility(
                    name="Running Water",
                    description=". The vampire takes 20 Acid damage if it ends its turn in running water.",
                ),
                MonsterAbility(
                    name="Stake to the Heart",
                    description=". If a weapon that deals Piercing damage is driven into the vampire's heart while the vampire has the Incapacitated condition in its resting place, the vampire has the Paralyzed condition until the weapon is removed.",
                ),
                MonsterAbility(
                    name="Sunlight",
                    description=". The vampire takes 20 Radiant damage if it starts its turn in sunlight. While in sunlight, it has Disadvantage on attack rolls and ability checks.",
                ),
            ],
            actions=[
                MonsterAbility(
                    name="Multiattack (Vampire Form Only)",
                    description="The vampire makes two Grave Strike attacks and uses Bite.",
                ),
                MonsterAbility(
                    name="Grave Strike (Vampire Form Only)",
                    description="Melee Attack Roll: +9, reach 5 ft. Hit: 8 (1d8 + 4) Bludgeoning damage plus 7 (2d6) Necrotic damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 14) from one of two hands.",
                ),
                MonsterAbility(
                    name="Bite (Bat or Vampire Form Only)",
                    description="Constitution Saving Throw: DC 17, one creature within 5 feet that is willing or that has the Grappled, Incapacitated, or Restrained condition. Failure: 6 (1d4 + 4) Piercing damage plus 13 (3d8) Necrotic damage. The target's Hit Point maximum decreases by an amount equal to the Necrotic damage taken, and the vampire regains Hit Points equal to that amount. A Humanoid reduced to 0 Hit Points by this damage and then buried rises the following sunset as a Vampire Spawn under the vampire's control.",
                ),
            ],
            bonus_actions=[
                MonsterAbility(
                    name="Shape-Shift",
                    description="If the vampire isn't in sunlight or running water, it shape-shifts into a Tiny bat (Speed 5 ft., Fly Speed 30 ft.) or a Medium cloud of mist (Speed 5 ft., Fly Speed 20 ft. [hover]), or it returns to its vampire form. Anything it is wearing transforms with it. While in bat form, the vampire can't speak. Its game statistics, other than its size and Speed, are unchanged. While in mist form, the vampire can't take any actions, speak, or manipulate objects. It is weightless and can enter an enemy's space and stop there. If air can pass through a space, the mist can do so, but it can't pass through liquid. It has Resistance to all damage, except the damage it takes from sunlight.",
                ),
                MonsterAbility(
                    name="Charm (Recharge 5–6)",
                    description="The vampire casts Charm Person, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 17), and the duration is 24 hours. The Charmed target is a willing recipient of the vampire's Bite, the damage of which doesn't end the spell. When the spell ends, the target is unaware it was Charmed by the vampire.",
                ),
            ],
            reactions=[],
            legendary_actions=[
                MonsterAbility(
                    name="Deathless Strike",
                    description="The vampire moves up to half its Speed, and it makes one Grave Strike attack.",
                ),
                MonsterAbility(
                    name="Beguile",
                    description="The vampire casts Command, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 17). The vampire can't take this action again until the start of its next turn.",
                ),
            ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = [
    "AdultBrassDragon",
    "AdultWhiteDragon",
    "Beholder",
    "Nalfeshnee",
    "Rakshasa",
    "ShadowDragon",
    "StormGiant",
    "Ultroloth",
    "Vampire",
]
