# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import ExtendedCombatantData


class Ankylosaurus(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Ankylosaurus",
            hp=68,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 19, "Dex": 11, "Con": 15, "Int": 2, "Wis": 12, "Cha": 5},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Huge Beast (Dinosaur), Unaligned",
            ac_note="",
            hp_formula="8d12 + 16",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 11",
            languages="None",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The ankylosaurus makes two Tail attacks."},
            {"name": "Tail", "description": "Melee Attack Roll: +6, reach 10 ft. Hit: 9 (1d10 + 4) Bludgeoning damage. If the target is a Huge or smaller creature, it has the Prone condition."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Basilisk(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Basilisk",
            hp=52,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 8, "Con": 15, "Int": 2, "Wis": 8, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Unaligned",
            ac_note="",
            hp_formula="8d8 + 16",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 9",
            languages="None",
            traits=[],
            actions=[
            {"name": "Bite", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Piercing damage plus 7 (2d6) Poison damage."},
        ],
            bonus_actions=[
            {"name": "Petrifying Gaze (Recharge 4–6)", "description": "Constitution Saving Throw: DC 12, each creature in a 30-foot Cone. If the basilisk sees its reflection in the Cone, the basilisk must make this save. First Failure: The target has the Restrained condition and repeats the save at the end of its next turn if it is still Restrained, ending the effect on itself on a success. Second Failure: The target has the Petrified condition instead of the Restrained condition."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class BeardedDevil(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Bearded Devil",
            hp=58,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 15, "Con": 15, "Int": 9, "Wis": 11, "Cha": 14},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Fiend (Devil), Lawful Evil",
            ac_note="",
            hp_formula="9d8 + 18",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft. (unimpeded by magical Darkness), Passive Perception 10",
            languages="Infernal; telepathy 120 ft.",
            traits=[
            {"name": "Magic Resistance", "description": "The devil has Advantage on saving throws against spells and other magical effects."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The devil makes one Beard attack and one Infernal Glaive attack."},
            {"name": "Beard", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage, and the target has the Poisoned condition until the start of the devil's next turn. Until this poison ends, the target can't regain Hit Points."},
            {"name": "Infernal Glaive", "description": "Melee Attack Roll: +5, reach 10 ft. Hit: 8 (1d10 + 3) Slashing damage. If the target is a creature and doesn't already have an infernal wound, it is subjected to the following effect. Constitution Saving Throw: DC 12. Failure: The target receives an infernal wound. While wounded, the target loses 5 (1d10) Hit Points at the start of each of its turns. The wound closes after 1 minute, after a spell restores Hit Points to the target, or after the target or a creature within 5 feet of it takes an action to stanch the wound, doing so by succeeding on a DC 12 Wisdom (Medicine) check."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class BlueDragonWyrmling(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Blue Dragon Wyrmling",
            hp=65,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 10, "Con": 15, "Int": 12, "Wis": 11, "Cha": 15},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Dragon (Chromatic), Lawful Evil",
            ac_note="",
            hp_formula="10d8 + 20",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14",
            languages="Draconic",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The dragon makes two Rend attacks."},
            {"name": "Rend", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 8 (1d10 + 3) Slashing damage plus 3 (1d6) Lightning damage."},
            {"name": "Lightning Breath (Recharge 5–6)", "description": "Dexterity Saving Throw: DC 12, each creature in a 30-foot-long, 5-foot-wide Line. Failure: 21 (6d6) Lightning damage. Success: Half damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class BugbearStalker(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Bugbear Stalker",
            hp=65,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 14, "Con": 14, "Int": 11, "Wis": 12, "Cha": 11},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Fey (Goblinoid), Chaotic Evil",
            ac_note="",
            hp_formula="10d8 + 20",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 11",
            languages="Common, Goblin",
            traits=[
            {"name": "Abduct", "description": "The bugbear needn't spend extra movement to move a creature it is grappling."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The bugbear makes two Javelin or Morningstar attacks."},
            {"name": "Javelin", "description": "Melee or Ranged Attack Roll: +5, reach 10 ft. or range 30/120 ft. Hit: 13 (3d6 + 3) Piercing damage."},
            {"name": "Morningstar", "description": "Melee Attack Roll: +5 (with Advantage if the target is Grappled by the bugbear), reach 10 ft. Hit: 12 (2d8 + 3) Piercing damage."},
        ],
            bonus_actions=[
            {"name": "Quick Grapple", "description": "Dexterity Saving Throw: DC 13, one Medium or smaller creature the bugbear can see within 10 feet. Failure: The target has the Grappled condition (escape DC 13)."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class DisplacerBeast(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Displacer Beast",
            hp=76,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 15, "Con": 16, "Int": 6, "Wis": 12, "Cha": 8},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Lawful Evil",
            ac_note="",
            hp_formula="9d10 + 27",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 11",
            languages="Understands Sylvan but can't speak",
            traits=[
            {"name": "Avoidance", "description": "If the displacer beast is subjected to an effect that allows it to make a saving throw to take only half damage, it instead takes no damage if it succeeds on the save and half damage if it fails. It can't use this trait if it has the Incapacitated condition."},
            {"name": "Displacement", "description": "Attack rolls against the displacer beast have Disadvantage, since it projects an illusion that makes it appear to be near its actual location. This trait is suppressed while the displacer beast has the Incapacitated condition."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The displacer beast makes one Rend attack and one Tentacle attack."},
            {"name": "Rend", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 9 (1d10 + 4) Slashing damage. If target is a Large or smaller creature, it has the Prone condition."},
            {"name": "Tentacle", "description": "Melee Attack Roll: +6, reach 10 ft. Hit: 11 (2d6 + 4) Piercing damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Doppelganger(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Doppelganger",
            hp=52,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 11, "Dex": 18, "Con": 14, "Int": 11, "Wis": 12, "Cha": 14},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Neutral",
            ac_note="",
            hp_formula="8d8 + 16",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 11",
            languages="Common plus three other languages",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The doppelganger makes two Slam attacks and uses Unsettling Visage if available."},
            {"name": "Slam", "description": "Melee Attack Roll: +6 (with Advantage during the first round of each combat), reach 5 ft. Hit: 11 (2d6 + 4) Bludgeoning damage."},
            {"name": "Read Thoughts", "description": "The doppelganger casts Detect Thoughts, requiring no spell components and using Charisma as the spellcasting ability (spell save DC 12)."},
            {"name": "Unsettling Visage (Recharge 6)", "description": "Wisdom Saving Throw: DC 12, each creature in a 15-foot Emanation originating from the doppelganger that can see the doppelganger. Failure: The target has the Frightened condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."},
        ],
            bonus_actions=[
            {"name": "Shape-Shift", "description": "The doppelganger shape-shifts into a Medium or Small Humanoid, or it returns to its true form. Its game statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class FlamingSkeleton(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Flaming Skeleton",
            hp=65,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 10, "Dex": 14, "Con": 15, "Int": 10, "Wis": 15, "Cha": 8},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Undead, Lawful Evil",
            ac_note="",
            hp_formula="10d8 + 20",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 12",
            languages="Understands Common plus one other language but can't speak",
            traits=[
            {"name": "Death Burst", "description": "The skeleton explodes when it dies. Dexterity Saving Throw: DC 12, each creature in a 10-foot Emanation originating from the skeleton. Failure: 14 (4d6) Fire damage. Success: Half damage."},
            {"name": "Illumination", "description": "The skeleton sheds Bright Light in a 15-foot radius and Dim Light for an additional 15 feet."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The skeleton makes two attacks, using Flame Scepter or Hurl Flame in any combination."},
            {"name": "Flame Scepter", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Bludgeoning damage plus 3 (1d6) Fire damage."},
            {"name": "Hurl Flame", "description": "Ranged Attack Roll: +4, range 60 ft. Hit: 7 (1d10 + 2) Fire damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GiantScorpion(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Giant Scorpion",
            hp=52,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 13, "Con": 15, "Int": 1, "Wis": 9, "Cha": 3},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Beast, Unaligned",
            ac_note="",
            hp_formula="7d10 + 14",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Passive Perception 9",
            languages="None",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The scorpion makes two Claw attacks and one Sting attack."},
            {"name": "Claw", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Bludgeoning damage. If the target is a Large or smaller creature, it has the Grappled condition (escape DC 13) from one of two claws."},
            {"name": "Sting", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage plus 11 (2d10) Poison damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GithyankiWarrior(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Githyanki Warrior",
            hp=49,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 15, "Dex": 14, "Con": 12, "Int": 13, "Wis": 13, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Aberration (Gith), Lawful Evil",
            ac_note="",
            hp_formula="9d8 + 9",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 11",
            languages="Common, Gith",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The githyanki makes two Psi Blade attacks."},
            {"name": "Psi Blade", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 9 (2d6 + 2) Slashing damage plus 7 (2d6) Psychic damage."},
            {"name": "Spellcasting", "description": "The githyanki casts one of the following spells, requiring no spell components and using Intelligence as the spellcasting ability:"},
        ],
            bonus_actions=[
            {"name": "Misty Step (2/Day)", "description": "The githyanki casts Misty Step, requiring no spell components and using the same spellcasting ability as Spellcasting."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GoblinHexer(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Goblin Hexer",
            hp=45,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 8, "Dex": 16, "Con": 12, "Int": 16, "Wis": 10, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Small Fey (Goblinoid), Chaotic Neutral",
            ac_note="",
            hp_formula="10d6 + 10",
            speed="",
            skills={"of Hand": 5, "Stealth": 7},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 10",
            languages="Common, Goblin",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The goblin makes two Hex Stick attacks. It can replace one attack with a use of Spellcasting."},
            {"name": "Hex Stick", "description": "Melee or Ranged Attack Roll: +5, reach 5 ft. or range 60 ft. Hit: 12 (2d8 + 3) Psychic damage."},
            {"name": "Spellcasting", "description": "The goblin casts one of the following spells, using Intelligence as the spellcasting ability (spell save DC 13):"},
            {"name": "Jinx", "description": "Trigger: A creature the goblin can see hits it with an attack roll. Response—Wisdom Saving Throw: DC 13, the triggering creature. Failure: The attack misses instead."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GoldDragonWyrmling(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Gold Dragon Wyrmling",
            hp=60,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 19, "Dex": 14, "Con": 17, "Int": 14, "Wis": 11, "Cha": 16},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Dragon (Metallic), Lawful Good",
            ac_note="",
            hp_formula="8d8 + 24",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14",
            languages="Draconic",
            traits=[
            {"name": "Amphibious", "description": "The dragon can breathe air and water."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The dragon makes two Rend attacks."},
            {"name": "Rend", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 9 (1d10 + 4) Slashing damage."},
            {"name": "Fire Breath (Recharge 5–6)", "description": "Dexterity Saving Throw: DC 13, each creature in a 15-foot Cone. Failure: 22 (4d10) Fire damage. Success: Half damage."},
            {"name": "Weakening Breath", "description": "Strength Saving Throw: DC 13, each creature that isn't currently affected by this breath in a 15-foot Cone. Failure: The target has Disadvantage on Strength-based D20 Tests and subtracts 2 (1d4) from its damage rolls. It repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class GreenHag(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Green Hag",
            hp=82,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 12, "Con": 16, "Int": 13, "Wis": 14, "Cha": 14},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Fey, Neutral Evil",
            ac_note="",
            hp_formula="11d8 + 33",
            speed="30 ft.,",
            skills={"Arcana": 5, "Deception": 4, "Perception": 4, "Stealth": 3},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 14",
            languages="Common, Elvish, Sylvan",
            traits=[
            {"name": "Amphibious", "description": "The hag can breathe air and water."},
            {"name": "Coven Magic", "description": "While within 30 feet of at least two hag allies, the hag can cast one of the following spells, requiring no Material components, using the spell's normal casting time, and using Intelligence as the spellcasting ability (spell save DC 11): Augury, Find Familiar, Identify, Locate Object, Scrying, or Unseen Servant. The hag must finish a Long Rest before using this trait to cast that spell again."},
            {"name": "Mimicry", "description": "The hag can mimic animal sounds and humanoid voices. A creature that hears the sounds can tell they are imitations only with a successful DC 14 Wisdom (Insight) check."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The hag makes two Claw attacks."},
            {"name": "Claw", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 8 (1d8 + 4) Slashing damage plus 3 (1d6) Poison damage."},
            {"name": "Spellcasting", "description": "The hag casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 12, +4 to hit with spell attacks):"},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Grell(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Grell",
            hp=55,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 15, "Dex": 14, "Con": 13, "Int": 12, "Wis": 11, "Cha": 9},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Aberration, Neutral Evil",
            ac_note="",
            hp_formula="10d8 + 10",
            speed="10 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Passive Perception 14",
            languages="Deep Speech",
            traits=[
            {"name": "Abduct", "description": "The grell needn't spend extra movement to move a creature it is grappling."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The grell makes one Beak attack and one Paralyzing Tentacles attack."},
            {"name": "Beak", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 11 (2d8 + 2) Piercing damage."},
            {"name": "Paralyzing Tentacles", "description": "Melee Attack Roll: +4, reach 10 ft. Hit: 7 (1d10 + 2) Piercing damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12) from two of ten tentacles. The target is also subjected to the following effect. Constitution Saving Throw: DC 11. Failure: The target has the Poisoned condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically. While Poisoned, the target has the Paralyzed condition."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class HellHound(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Hell Hound",
            hp=58,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 12, "Con": 14, "Int": 6, "Wis": 13, "Cha": 6},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Fiend, Lawful Evil",
            ac_note="",
            hp_formula="9d8 + 18",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 15",
            languages="Understands Infernal but can't speak",
            traits=[
            {"name": "Pack Tactics", "description": "The hound has Advantage on an attack roll against a creature if at least one of the hound's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The hound makes two Bite attacks."},
            {"name": "Bite", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Piercing damage plus 3 (1d6) Fire damage."},
            {"name": "Fire Breath (Recharge 5–6)", "description": "Dexterity Saving Throw: DC 12, each creature in a 15-foot Cone. Failure: 17 (5d6) Fire damage. Success: Half damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class HobgoblinCaptain(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Hobgoblin Captain",
            hp=58,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 15, "Dex": 14, "Con": 14, "Int": 12, "Wis": 10, "Cha": 13},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Fey (Goblinoid), Lawful Evil",
            ac_note="",
            hp_formula="9d8 + 18",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 10",
            languages="Common, Goblin",
            traits=[
            {"name": "Aura of Authority", "description": "While in a 10-foot Emanation originating from the hobgoblin, the hobgoblin and its allies have Advantage on attack rolls and saving throws, provided the hobgoblin doesn't have the Incapacitated condition."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The hobgoblin makes two attacks, using Greatsword or Longbow in any combination."},
            {"name": "Greatsword", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 9 (2d6 + 2) Slashing damage plus 3 (1d6) Poison damage."},
            {"name": "Longbow", "description": "Ranged Attack Roll: +4, range 150/600 ft. Hit: 6 (1d8 + 2) Piercing damage plus 5 (2d4) Poison damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class HookHorror(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Hook Horror",
            hp=75,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 10, "Con": 15, "Int": 6, "Wis": 12, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Neutral",
            ac_note="",
            hp_formula="10d10 + 20",
            speed="30 ft.,",
            skills={"Perception": 5},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 15",
            languages="Hook Horror",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The hook horror makes two Hook attacks."},
            {"name": "Hook", "description": "Melee Attack Roll: +6, reach 10 ft. Hit: 11 (2d6 + 4) Piercing damage. If the target is a Large or smaller creature, the hook horror moves the target 5 feet straight toward or away from itself."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class KillerWhale(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Killer Whale",
            hp=90,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 19, "Dex": 14, "Con": 13, "Int": 3, "Wis": 12, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Huge Beast, Unaligned",
            ac_note="",
            hp_formula="12d12 + 12",
            speed="5 ft.,",
            skills={"Perception": 3, "Stealth": 4},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 120 ft., Passive Perception 13",
            languages="None",
            traits=[
            {"name": "Hold Breath", "description": "The whale can hold its breath for 30 minutes."},
        ],
            actions=[
            {"name": "Bite", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 21 (5d6 + 4) Piercing damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Knight(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Knight",
            hp=52,
            ac=18,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 11, "Con": 14, "Int": 11, "Wis": 11, "Cha": 15},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Humanoid, Any Alignment",
            ac_note="",
            hp_formula="8d8 +16",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 10",
            languages="Common plus one other language",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The knight makes two attacks, using Greatsword or Heavy Crossbow in any combination."},
            {"name": "Greatsword", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6+ 3) Slashing damage plus 4 (1d8) Radiant damage."},
            {"name": "Heavy Crossbow", "description": "Ranged Attack Roll: +2, range 100/400 ft. Hit: 11 (2d10) Piercing damage plus 4 (1d8) Radiant damage."},
            {"name": "Parry", "description": "Trigger: The knight is hit by a melee attack roll while holding a weapon. Response: The knight adds 2 to its AC against that attack, possibly causing it to miss."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class KuotoaMonitor(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Kuo-toa Monitor",
            hp=65,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 10, "Con": 14, "Int": 12, "Wis": 14, "Cha": 11},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Aberration, Neutral Evil",
            ac_note="",
            hp_formula="10d8 + 20",
            speed="30 ft.,",
            skills={"Perception": 6, "Religion": 3},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Truesight 30 ft., Passive Perception 16",
            languages="Undercommon",
            traits=[
            {"name": "Amphibious", "description": "The kuo-toa can breathe air and water."},
            {"name": "Sunlight Sensitivity", "description": "While in sunlight, the kuo-toa has Disadvantage on ability checks and attack rolls."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The kuo-toa makes two Bone Whip attacks."},
            {"name": "Bone Whip", "description": "Melee Attack Roll: +5, reach 10 ft. Hit: 6 (1d6 + 3) Slashing damage plus 7 (2d6) Lightning damage, and the target can't make Opportunity Attacks until the start of the kuo-toa's next turn."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Manticore(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Manticore",
            hp=68,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 16, "Con": 17, "Int": 7, "Wis": 12, "Cha": 8},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Lawful Evil",
            ac_note="",
            hp_formula="8d10 + 24",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 11",
            languages="Common",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The manticore makes three attacks, using Rend or Tail Spike in any combination."},
            {"name": "Rend", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 7 (1d8 + 3) Slashing damage."},
            {"name": "Tail Spike", "description": "Ranged Attack Roll: +5, range 100/200 ft. Hit: 7 (1d8 + 3) Piercing damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class MinotaurOfBaphomet(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Minotaur of Baphomet",
            hp=85,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 11, "Con": 16, "Int": 6, "Wis": 16, "Cha": 9},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Chaotic Evil",
            ac_note="",
            hp_formula="10d10 + 30",
            speed="",
            skills={"Perception": 7, "Survival": 7},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 17",
            languages="Abyssal",
            traits=[],
            actions=[
            {"name": "Abyssal Glaive", "description": "Melee Attack Roll: +6, reach 10 ft. Hit: 10 (1d12 + 4) Slashing damage plus 10 (3d6) Necrotic damage."},
            {"name": "Gore (Recharge 5–6)", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 18 (4d6 + 4) Piercing damage. If the target is a Large or smaller creature and the minotaur moved 10+ feet straight toward it immediately before the hit, the target takes an extra 10 (3d6) Piercing damage and has the Prone condition."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Mummy(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Mummy",
            hp=58,
            ac=11,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 8, "Con": 15, "Int": 6, "Wis": 12, "Cha": 12},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Undead, Lawful Evil",
            ac_note="",
            hp_formula="9d8 + 18",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 11",
            languages="Common plus two other languages",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The mummy makes two Rotting Fist attacks and uses Dreadful Glare."},
            {"name": "Rotting Fist", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 8 (1d10 + 3) Bludgeoning damage plus 10 (3d6) Necrotic damage. If the target is a creature, it is cursed. While cursed, the target can't regain Hit Points, its Hit Point maximum doesn't return to normal when finishing a Long Rest, and its Hit Point maximum decreases by 10 (3d6) every 24 hours that elapse. A creature dies and turns to dust if reduced to 0 Hit Points by this attack."},
            {"name": "Dreadful Glare", "description": "Wisdom Saving Throw: DC 11, one creature the mummy can see within 60 feet. Failure: The target has the Frightened condition until the end of the mummy's next turn. Success: The target is immune to this mummy's Dreadful Glare for 24 hours."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Nightmare(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Nightmare",
            hp=68,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 15, "Con": 16, "Int": 10, "Wis": 13, "Cha": 15},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Fiend, Neutral Evil",
            ac_note="",
            hp_formula="8d10 + 24",
            speed="60 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 11",
            languages="Understands Abyssal, Common, and Infernal but can't speak",
            traits=[
            {"name": "Confer Fire Resistance", "description": "The nightmare can grant Resistance to Fire damage to a rider while it is on the nightmare."},
            {"name": "Illumination", "description": "The nightmare sheds Bright Light in a 10-foot radius and Dim Light for an additional 10 feet."},
        ],
            actions=[
            {"name": "Hooves", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 13 (2d8 + 4) Bludgeoning damage plus 10 (3d6) Fire damage."},
            {"name": "Ethereal Stride", "description": "The nightmare and up to three willing creatures within 5 feet of it teleport to the Ethereal Plane from the Material Plane or vice versa."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Owlbear(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Owlbear",
            hp=59,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 20, "Dex": 12, "Con": 17, "Int": 3, "Wis": 12, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Unaligned",
            ac_note="",
            hp_formula="7d10 + 21",
            speed="40 ft.,",
            skills={"Perception": 5},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 15",
            languages="None",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The owlbear makes two Rend attacks."},
            {"name": "Rend", "description": "Melee Attack Roll: +7, reach 5 ft. Hit: 14 (2d8 + 5) Slashing damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class PhaseSpider(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Phase Spider",
            hp=45,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 15, "Dex": 16, "Con": 12, "Int": 6, "Wis": 10, "Cha": 6},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Unaligned",
            ac_note="",
            hp_formula="7d10 + 7",
            speed="30 ft.,",
            skills={"Stealth": 7},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 10",
            languages="—",
            traits=[
            {"name": "Ethereal Sight", "description": "The spider can see 60 feet into the Ethereal Plane while on the Material Plane and vice versa."},
            {"name": "Spider Climb", "description": "The spider can climb difficult surfaces, including along ceilings, without needing to make an ability check."},
            {"name": "Web Walker", "description": "The spider ignores movement restrictions caused by webs, and the spider knows the location of any other creature in contact with the same web."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The spider makes two Bite attacks."},
            {"name": "Bite", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 8 (1d10 + 3) Piercing damage plus 9 (2d8) Poison damage. If this damage reduces the target to 0 Hit Points, the target becomes Stable, and it has the Poisoned condition for 1 hour. While Poisoned, the target also has the Paralyzed condition."},
        ],
            bonus_actions=[
            {"name": "Ethereal Jaunt", "description": "The spider teleports from the Material Plane to the Ethereal Plane or vice versa."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class QuaggothThonot(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Quaggoth Thonot",
            hp=67,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 12, "Con": 16, "Int": 6, "Wis": 14, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Chaotic Neutral",
            ac_note="",
            hp_formula="9d8 + 27",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 12",
            languages="Undercommon",
            traits=[
            {"name": "Bloodied Fury", "description": "While Bloodied, the quaggoth has Advantage on attack rolls."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The quaggoth makes two Claw attacks."},
            {"name": "Claw", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Slashing damage plus 5 (2d4) Psychic damage."},
            {"name": "Spellcasting", "description": "The quaggoth casts one of the following spells, requiring no spell components and using Wisdom as the spellcasting ability (spell save DC 12):"},
            {"name": "Psionic Defense (3/Day)", "description": "The quaggoth casts Feather Fall or Shield in response to the spell's trigger, requiring no spell components and using the same spellcasting ability as Spellcasting."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class ScoutCaptain(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Scout Captain",
            hp=66,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 11, "Dex": 16, "Con": 12, "Int": 14, "Wis": 15, "Cha": 11},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Humanoid, Neutral",
            ac_note="",
            hp_formula="12d8 + 12",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 16",
            languages="Common plus one other language",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The scout makes two attacks, using Shortsword or Longbow in any combination."},
            {"name": "Shortsword", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage, plus 10 (3d6) Piercing damage if the attack was made with Advantage."},
            {"name": "Longbow", "description": "Ranged Attack Roll: +5, range 150/600 ft. Hit: 7 (1d8 + 3) Piercing damage, plus 10 (3d6) Piercing damage if the attack was made with Advantage."},
            {"name": "Uncanny Dodge", "description": "Trigger: The scout is hit by an attack roll. Response: The scout halves the damage (round down) it takes from that attack."},
        ],
            bonus_actions=[
            {"name": "Aim", "description": "The scout has Advantage on the next attack roll it makes during the current turn."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Spectator(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Spectator",
            hp=45,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 8, "Dex": 14, "Con": 14, "Int": 13, "Wis": 14, "Cha": 11},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Aberration (Beholder), Lawful Neutral",
            ac_note="",
            hp_formula="7d8 + 14",
            speed="5 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 16",
            languages="Deep Speech, Undercommon; telepathy 120 ft.",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The spectator uses Eye Rays twice."},
            {"name": "Bite", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage."},
            {"name": "Eye Rays", "description": "The spectator randomly shoots one of the following magical rays at a target it can see within 90 feet of itself (roll 1d4; reroll if the spectator has already used that ray during this turn):"},
            {"name": "1: Confusion Ray", "description": ". Wisdom Saving Throw: DC 12. Failure: 5 (2d4) Psychic damage, and the target can't take Reactions until the end of its next turn. On its next turn, the target can't move, and it uses its action to make a melee or ranged attack against a randomly determined creature within range. If the target can't attack, it does nothing on that turn."},
            {"name": "2: Paralyzing Ray", "description": ". Constitution Saving Throw: DC 12. Failure: The target has the Paralyzed condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."},
            {"name": "3: Fear Ray", "description": ". Wisdom Saving Throw: DC 12. Failure: 5 (2d4) Psychic damage, and the target has the Frightened condition until the end of its next turn."},
            {"name": "4: Wounding Ray", "description": ". Constitution Saving Throw: DC 12. Failure: 16 (3d10) Necrotic damage. Success: Half damage."},
            {"name": "Spell Reflection", "description": "Trigger: The spectator succeeds on a saving throw against a spell, or a spell's attack roll misses it. Response—Dexterity Saving Throw: DC 12, one creature the spectator can see within 120 feet. Failure: 10 (3d6) Force damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class SwarmOfCrawlingClaws(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Swarm of Crawling Claws",
            hp=49,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 14, "Dex": 14, "Con": 11, "Int": 5, "Wis": 10, "Cha": 4},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Swarm of Tiny Undead, Neutral Evil",
            ac_note="",
            hp_formula="11d8",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Passive Perception 10",
            languages="Understands Common but can't speak",
            traits=[
            {"name": "Swarm", "description": "The swarm can occupy another creature's space and vice versa, and the swarm can move through any opening large enough for a Tiny creature. The swarm can't regain Hit Points or gain Temporary Hit Points."},
        ],
            actions=[
            {"name": "Swarm of Grasping Hands", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 20 (4d8 + 2) Necrotic damage, or 11 (2d8 + 2) Necrotic damage if the swarm is Bloodied. If the target is a Medium or smaller creature, it has the Prone condition."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class SwarmOfLemures(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Swarm of Lemures",
            hp=45,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 14, "Dex": 7, "Con": 14, "Int": 1, "Wis": 12, "Cha": 3},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large swarm of Medium Fiends (Devil), Lawful Evil",
            ac_note="",
            hp_formula="6d10 + 12",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft. (unimpeded by magical Darkness), Passive Perception 11",
            languages="Understands Infernal but can't speak",
            traits=[
            {"name": "Hellish Restoration", "description": "If the swarm dies in the Nine Hells, it revives with all its Hit Points in 1d10 days unless it is killed by a creature under the effects of a Bless spell or its remains are sprinkled with Holy Water."},
            {"name": "Swarm", "description": "The swarm can occupy another creature's space and vice versa, and the swarm can move through an opening large enough for a Medium creature. The swarm can't regain Hit Points or gain Temporary Hit Points."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The swarm makes two Vile Slime attacks."},
            {"name": "Vile Slime", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 11 (2d8 + 2) Poison damage, or 9 (2d6 + 2) Poison damage if the swarm is Bloodied."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class VampireFamiliar(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Vampire Familiar",
            hp=65,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 16, "Con": 15, "Int": 10, "Wis": 10, "Cha": 14},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Humanoid, Neutral Evil",
            ac_note="",
            hp_formula="10d8 +20",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 14",
            languages="Common plus one other language",
            traits=[
            {"name": "Vampiric Connection", "description": "While the familiar and its vampire master are on the same plane of existence, the vampire can communicate with the familiar telepathically, and the vampire can perceive through the familiar's senses."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The familiar makes two Umbral Dagger attacks."},
            {"name": "Umbral Dagger", "description": "Melee or Ranged Attack Roll: +5, reach 5 ft. or range 20/60 ft. Hit: 5 (1d4 + 3) Piercing damage plus 7 (3d4) Necrotic damage. If the target is reduced to 0 Hit Points by this attack, the target becomes Stable but has the Poisoned condition for 1 hour. While it has the Poisoned condition, the target has the Paralyzed condition."},
        ],
            bonus_actions=[
            {"name": "Deathless Agility", "description": "The familiar takes the Dash or Disengage action."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class WarriorVeteran(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Warrior Veteran",
            hp=65,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 13, "Con": 14, "Int": 10, "Wis": 11, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Humanoid, Neutral",
            ac_note="",
            hp_formula="10d8 + 20",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 12",
            languages="Common plus one other language",
            traits=[],
            actions=[
            {"name": "Multiattack", "description": "The warrior makes two Greatsword or Heavy Crossbow attacks."},
            {"name": "Greatsword", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage."},
            {"name": "Heavy Crossbow", "description": "Ranged Attack Roll: +3, range 100/400 ft. Hit: 12 (2d10 + 1) Piercing damage."},
            {"name": "Parry", "description": "Trigger: The warrior is hit by a melee attack roll while holding a weapon. Response: The warrior adds 2 to its AC against that attack, possibly causing it to miss."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class WaterWeird(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Water Weird",
            hp=65,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 17, "Dex": 16, "Con": 13, "Int": 11, "Wis": 10, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Elemental, Neutral",
            ac_note="",
            hp_formula="10d10 + 10",
            speed="5 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 30 ft., Passive Perception 10",
            languages="Understands Primordial but can't speak",
            traits=[
            {"name": "Invisible in Water", "description": "The water weird has the Invisible condition while fully immersed in water."},
            {"name": "Water Bound", "description": "The water weird dies if it leaves the water to which it is bound or if that water is destroyed."},
        ],
            actions=[
            {"name": "Surge", "description": "Melee Attack Roll: +5, reach 10 ft. Hit: 13 (3d6 + 3) Cold damage. If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13), and it has the Restrained condition until the grapple ends."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Werewolf(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Werewolf",
            hp=71,
            ac=15,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 14, "Con": 14, "Int": 10, "Wis": 11, "Cha": 10},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium or Small Monstrosity (Lycanthrope), Chaotic Evil",
            ac_note="",
            hp_formula="11d8 + 22",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 14",
            languages="Common (can't speak in wolf form)",
            traits=[
            {"name": "Pack Tactics", "description": "The werewolf has Advantage on an attack roll against a creature if at least one of the werewolf's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The werewolf makes two attacks, using Scratch or Longbow in any combination. It can replace one attack with a Bite attack."},
            {"name": "Bite (Wolf or Hybrid Form Only)", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 12 (2d8 + 3) Piercing damage. If the target is a Humanoid, it is subjected to the following effect. Constitution Saving Throw: DC 12. Failure: The target is cursed. If the cursed target drops to 0 Hit Points, it instead becomes a Werewolf under the DM's control and has 10 Hit Points. Success: The target is immune to this werewolf's curse for 24 hours."},
            {"name": "Scratch", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 10 (2d6 + 3) Slashing damage."},
            {"name": "Longbow (Humanoid or Hybrid Form Only)", "description": "Ranged Attack Roll: +4, range 150/600 ft. Hit: 11 (2d8 + 2) Piercing damage."},
        ],
            bonus_actions=[
            {"name": "Shape-Shift", "description": "The werewolf shape-shifts into a Large wolf-humanoid hybrid or a Medium wolf, or it returns to its true humanoid form. Its game statistics, other than its size, are the same in each form. Any equipment it is wearing or carrying isn't transformed."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Wight(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Wight",
            hp=82,
            ac=14,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 15, "Dex": 14, "Con": 16, "Int": 10, "Wis": 13, "Cha": 15},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Undead, Neutral Evil",
            ac_note="",
            hp_formula="11d8 + 33",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 13",
            languages="Common plus one other language",
            traits=[
            {"name": "Sunlight Sensitivity", "description": "While in sunlight, the wight has Disadvantage on ability checks and attack rolls."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The wight makes two attacks, using Necrotic Sword or Necrotic Bow in any combination. It can replace one attack with a use of Life Drain."},
            {"name": "Necrotic Sword", "description": "Melee Attack Roll: +4, reach 5 ft. Hit: 6 (1d8 + 2) Slashing damage plus 4 (1d8) Necrotic damage."},
            {"name": "Necrotic Bow", "description": "Ranged Attack Roll: +4, range 150/600 ft. Hit: 6 (1d8 + 2) Piercing damage plus 4 (1d8) Necrotic damage."},
            {"name": "Life Drain", "description": "Constitution Saving Throw: DC 13, one creature within 5 feet. Failure: 6 (1d8 + 2) Necrotic damage, and the target's Hit Point maximum decreases by an amount equal to the damage taken. A Humanoid slain by this attack rises 24 hours later as a Zombie under the wight's control, unless the Humanoid is restored to life or its body is destroyed. The wight can have no more than twelve zombies under its control at a time."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class WinterWolf(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Winter Wolf",
            hp=75,
            ac=13,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 13, "Con": 14, "Int": 7, "Wis": 12, "Cha": 8},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Neutral Evil",
            ac_note="",
            hp_formula="10d10 + 20",
            speed="",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Passive Perception 15",
            languages="Common, Giant",
            traits=[
            {"name": "Pack Tactics", "description": "The wolf has Advantage on an attack roll against a creature if at least one of the wolf's allies is within 5 feet of the creature and the ally doesn't have the Incapacitated condition."},
        ],
            actions=[
            {"name": "Bite", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 11 (2d6 + 4) Piercing damage. If the target is a Large or smaller creature, it has the Prone condition."},
            {"name": "Cold Breath (Recharge 5–6)", "description": "Constitution Saving Throw: DC 12, each creature in a 15-foot Cone. Failure: 18 (4d8) Cold damage. Success: Half damage."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Yeti(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Yeti",
            hp=51,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 18, "Dex": 13, "Con": 16, "Int": 8, "Wis": 12, "Cha": 7},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Large Monstrosity, Chaotic Evil",
            ac_note="",
            hp_formula="6d10 + 18",
            speed="40 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 15",
            languages="Yeti",
            traits=[
            {"name": "Fear of Fire", "description": "If the yeti takes Fire damage, it has Disadvantage on attack rolls and ability checks until the end of its next turn."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The yeti can use its Chilling Gaze and makes two attacks, using Claw or Ice Throw in any combination."},
            {"name": "Claw", "description": "Melee Attack Roll: +6, reach 5 ft. Hit: 7 (1d6 + 4) Slashing damage plus 3 (1d6) Cold damage."},
            {"name": "Ice Throw", "description": "Ranged Attack Roll: +6, range 30/120 ft. Hit: 6 (1d4 + 4) Bludgeoning damage plus 2 (1d4) Cold damage."},
            {"name": "Chilling Gaze", "description": "Constitution Saving Throw: DC 13, one creature the yeti can see within 30 feet. Failure: 5 (2d4) Cold damage, and the target has the Paralyzed condition until the start of the yeti's next turn unless the target has Immunity to Cold damage. Success: The target is immune to the Chilling Gaze of all yetis (but not abominable yetis) for 1 hour."},
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class YuantiMalisonType1(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Yuan-ti Malison (Type 1)",
            hp=66,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 14, "Con": 13, "Int": 14, "Wis": 16, "Cha": 12},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Neutral Evil",
            ac_note="",
            hp_formula="12d8 + 12",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 13",
            languages="Abyssal, Common, Draconic",
            traits=[
            {"name": "Magic Resistance", "description": "The yuan-ti has Advantage on saving throws against spells and other magical effects."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The yuan-ti makes two attacks, using Bite or Poison Ray in any combination, and it can use Spellcasting to cast Suggestion if available."},
            {"name": "Bite", "description": "Melee Attack Roll: +5, reach 5 ft. Hit: 5 (1d4 + 3) Piercing damage plus 7 (2d6) Poison damage."},
            {"name": "Poison Ray (Yuan-ti Form Only)", "description": "Ranged Attack Roll: +5, range 120 ft. Hit: 12 (2d8 + 3) Poison damage."},
            {"name": "Spellcasting (Yuan-ti Form Only)", "description": "The yuan-ti casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 13):"},
        ],
            bonus_actions=[
            {"name": "Shape-Shift", "description": "The yuan-ti shape-shifts into a Medium snake or returns to its true form. If it dies, it stays in its current form. The yuan-ti's game statistics are the same in each form, except where noted. Any equipment it is wearing or carrying isn't transformed."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class YuantiMalisonType2(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Yuan-ti Malison (Type 2)",
            hp=66,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 14, "Con": 13, "Int": 14, "Wis": 16, "Cha": 12},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Neutral Evil",
            ac_note="",
            hp_formula="12d8 + 12",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 13",
            languages="Abyssal, Common, Draconic",
            traits=[
            {"name": "Magic Resistance", "description": "The yuan-ti has Advantage on saving throws against spells and other magical effects."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The yuan-ti makes two Bite attacks, and it can use Spellcasting to cast Suggestion if available."},
            {"name": "Bite", "description": "Melee Attack Roll: +5, reach 10 ft. Hit: 7 (1d8 + 3) Piercing damage plus 7 (2d6) Poison damage."},
            {"name": "Spellcasting (Yuan-ti Form Only)", "description": "The yuan-ti casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 13):"},
        ],
            bonus_actions=[
            {"name": "Shape-Shift", "description": "The yuan-ti shape-shifts into a Medium snake or returns to its true form. If it dies, it stays in its current form. The yuan-ti's game statistics are the same in each form, except where noted. Any equipment it is wearing or carrying isn't transformed."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class YuantiMalisonType3(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            name="Yuan-ti Malison (Type 3)",
            hp=66,
            ac=12,
            temp_hp=0,
            conditions=[],
            ability_scores={"Str": 16, "Dex": 14, "Con": 13, "Int": 14, "Wis": 16, "Cha": 12},
            saving_throws={},
            spell_slots={},
            cr="3",
            monster_type="Medium Monstrosity, Neutral Evil",
            ac_note="",
            hp_formula="12d8 + 12",
            speed="30 ft.,",
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 60 ft., Passive Perception 13",
            languages="Abyssal, Common, Draconic",
            traits=[
            {"name": "Magic Resistance", "description": "The yuan-ti has Advantage on saving throws against spells and other magical effects."},
        ],
            actions=[
            {"name": "Multiattack", "description": "The yuan-ti makes two Poison Burst attacks, and it can use Spellcasting to cast Suggestion if available."},
            {"name": "Poison Burst (Yuan-ti Form Only)", "description": "Melee or Ranged Attack Roll: +5, reach 5 ft. or range 120 ft. Hit: 12 (2d8 + 3) Poison damage."},
            {"name": "Constrict", "description": "Strength Saving Throw: DC 13, one Medium or smaller creature within 5 feet. Failure: 21 (4d8 + 3) Bludgeoning damage. The target has the Grappled condition (escape DC 13), and it has the Restrained condition until the grapple ends."},
            {"name": "Spellcasting (Yuan-ti Form Only)", "description": "The yuan-ti casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 13):"},
        ],
            bonus_actions=[
            {"name": "Shape-Shift", "description": "The yuan-ti shape-shifts into a Medium snake or returns to its true form. If it dies, it stays in its current form. The yuan-ti's game statistics are the same in each form, except where noted. Any equipment it is wearing or carrying isn't transformed."},
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['Ankylosaurus', 'Basilisk', 'BeardedDevil', 'BlueDragonWyrmling', 'BugbearStalker', 'DisplacerBeast', 'Doppelganger', 'FlamingSkeleton', 'GiantScorpion', 'GithyankiWarrior', 'GoblinHexer', 'GoldDragonWyrmling', 'GreenHag', 'Grell', 'HellHound', 'HobgoblinCaptain', 'HookHorror', 'KillerWhale', 'Knight', 'KuotoaMonitor', 'Manticore', 'MinotaurOfBaphomet', 'Mummy', 'Nightmare', 'Owlbear', 'PhaseSpider', 'QuaggothThonot', 'ScoutCaptain', 'Spectator', 'SwarmOfCrawlingClaws', 'SwarmOfLemures', 'VampireFamiliar', 'WarriorVeteran', 'WaterWeird', 'Werewolf', 'Wight', 'WinterWolf', 'Yeti', 'YuantiMalisonType1', 'YuantiMalisonType2', 'YuantiMalisonType3']
