# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    Size,
    Skill,
)
from Definitions import Ability


class AdultGoldDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Gold Dragon",
            hp=243,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 27, Ability.DEXTERITY.short_name: 14, Ability.CONSTITUTION.short_name: 25, Ability.INTELLIGENCE.short_name: 16, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 24},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.HUGE, monster_type='Dragon (Metallic)', alignment=Alignment.LAWFUL_GOOD,
            ac_note="",
            hp_formula="18d12 + 126",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 24",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of (A) Spellcasting to cast Guiding Bolt (level 2 version) or (B) Weakening Breath.'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +14, reach 10 ft. Hit: 17 (2d8 + 8) Slashing damage plus 4 (1d8) Fire damage.'),
            MonsterAbility(name='Fire Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 21, each creature in a 60-foot Cone. Failure: 66 (12d10) Fire damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 21, +13 to hit with spell attacks):'),
            MonsterAbility(name='Weakening Breath', description="Strength Saving Throw: DC 21, each creature that isn't currently affected by this breath in a 60-foot Cone. Failure: The target has Disadvantage on Strength-based D20 Tests and subtracts 3 (1d6) from its damage rolls. It repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Banish', description="Charisma Saving Throw: DC 21, one creature the dragon can see within 120 feet. Failure: 10 (3d6) Force damage, and the target has the Incapacitated condition and is transported to a harmless demiplane until the start of the dragon's next turn, at which point it reappears in an unoccupied space of the dragon's choice within 120 feet of the dragon. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Guiding Light', description='The dragon uses Spellcasting to cast Guiding Bolt (level 2 version).'),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class AdultRedDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Adult Red Dragon",
            hp=256,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 27, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 25, Ability.INTELLIGENCE.short_name: 16, Ability.WISDOM.short_name: 13, Ability.CHARISMA.short_name: 23},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.HUGE, monster_type='Dragon (Chromatic)', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="19d12 + 133",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 23",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Scorching Ray.'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +14, reach 10 ft. Hit: 13 (1d10 + 8) Slashing damage plus 5 (2d4) Fire damage.'),
            MonsterAbility(name='Fire Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 21, each creature in a 60-foot Cone. Failure: 59 (17d6) Fire damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 20, +12 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Commanding Presence', description="The dragon uses Spellcasting to cast Command (level 2 version). The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Fiery Rays', description="The dragon uses Spellcasting to cast Scorching Ray. The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class DeathKnight(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Death Knight",
            hp=199,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 20, Ability.DEXTERITY.short_name: 11, Ability.CONSTITUTION.short_name: 20, Ability.INTELLIGENCE.short_name: 12, Ability.WISDOM.short_name: 16, Ability.CHARISMA.short_name: 18},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.MEDIUM, monster_type='Undead', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="21d8 + 105",
            speed_ground_ft=None, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 13",
            languages="Abyssal, Common",
            traits=[
            MonsterAbility(name='Legendary Resistance (3/Day)', description='If the death knight fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Magic Resistance', description='The death knight has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Marshal Undead', description="Undead creatures of the death knight's choice (excluding itself) in a 60-foot Emanation originating from it have Advantage on attack rolls and saving throws. It can't use this trait if it has the Incapacitated condition."),
            MonsterAbility(name='Undead Restoration', description='If the death knight is destroyed before it atones for its evil, it gains a new body in 1d10 days, reviving with all its Hit Points. The new body appears in a location significant to the death knight.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The death knight makes three Dread Blade attacks.'),
            MonsterAbility(name='Dread Blade', description='Melee Attack Roll: +11, reach 5 ft. Hit: 12 (2d6 + 5) Slashing damage plus 13 (3d8) Necrotic damage.'),
            MonsterAbility(name='Hellfire Orb (Recharge 5–6)', description='Dexterity Saving Throw: DC 18, each creature in a 20-foot-radius Sphere centered on a point the death knight can see within 120 feet. Failure: 35 (10d6) Fire damage plus 35 (10d6) Necrotic damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The death knight casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 18):'),
            MonsterAbility(name='Parry', description='Trigger: The death knight is hit by a melee attack roll while holding a weapon. Response: The death knight adds 6 to its AC against that attack, possibly causing it to miss.'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Dread Authority', description="The death knight uses Spellcasting to cast Command. The death knight can't take this action again until the start of its next turn."),
            MonsterAbility(name='Fell Word', description="Constitution Saving Throw: DC 18, one creature the death knight can see within 120 feet. Failure: 17 (5d6) Necrotic damage, and the target's Hit Point maximum decreases by an amount equal to the damage taken. Failure or Success: The death knight can't take this action again until the start of its next turn."),
            MonsterAbility(name='Lunge', description='The death knight moves up to half its Speed, and it makes one Dread Blade attack.'),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class Dracolich(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Dracolich",
            hp=225,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 25, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 23, Ability.INTELLIGENCE.short_name: 19, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 21},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.HUGE, monster_type='Undead', alignment=Alignment.LAWFUL_EVIL,
            ac_note="",
            hp_formula="18d12 + 108",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 24",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the dracolich fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Life Suppression', description="Creatures within 60 feet of the dracolich can't regain Hit Points."),
            MonsterAbility(name='Magic Resistance', description='The dracolich has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Soul Gem', description='The dracolich has a magical gem. If the dracolich is destroyed while the gem is on the same plane of existence as it, the dracolich gains a new body in 1d20 days, regaining all its Hit Points and appearing within 5 feet of the gem. The gem is a Tiny object that has AC 20; HP 50; and Immunity to Necrotic, Poison, and Psychic damage. The gem regains all its Hit Points at the end of every turn, but it turns to dust if reduced to 0 Hit Points. If the gem is destroyed, the dracolich can create a new one by completing an 8-hour ritual using a gem worth 1,000+ GP and by expending 5,000 GP, which the ritual consumes.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dracolich makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Ray of Sickness (level 2 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +13, reach 10 ft. Hit: 18 (2d10 + 7) Slashing damage plus 4 (1d8) Necrotic damage.'),
            MonsterAbility(name='Necrotic Breath (Recharge 5–6)', description='Constitution Saving Throw: DC 20, each creature in a 60-foot Cone. Failure: 52 (8d12) Necrotic damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dracolich casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 19, +11 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Pounce', description='The dracolich moves up to half its Speed, and it makes one Rend attack.'),
            MonsterAbility(name='Sickening Ray', description="The dracolich uses Spellcasting to cast Ray of Sickness (level 2 version). The dracolich can't take this action again until the start of its next turn."),
            MonsterAbility(name='Terrifying Presence', description="Wisdom Saving Throw: DC 19, each creature in a 30-foot Emanation originating from the dracolich. Failure: 11 (2d10) Psychic damage, and the target has the Frightened condition until the end of its next turn. Failure or Success: The dracolich can't take this action again until the start of its next turn."),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


class DragonTurtle(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Dragon Turtle",
            hp=356,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 25, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 20, Ability.INTELLIGENCE.short_name: 10, Ability.WISDOM.short_name: 12, Ability.CHARISMA.short_name: 12},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.GARGANTUAN, monster_type='Dragon', alignment=Alignment.NEUTRAL,
            ac_note="",
            hp_formula="23d20 + 115",
            speed_ground_ft=20, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 11",
            languages="Draconic, Primordial (Aquan)",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Bite attacks. It can replace one attack with a Tail attack.'),
            MonsterAbility(name='Bite', description="Melee Attack Roll: +13, reach 15 ft. Hit: 23 (3d10 + 7) Piercing damage plus 7 (2d6) Fire damage. Being underwater doesn't grant Resistance to this Fire damage."),
            MonsterAbility(name='Tail', description='Melee Attack Roll: +13, reach 15 ft. Hit: 18 (2d10 + 7) Bludgeoning damage. If the target is a Huge or smaller creature, it has the Prone condition.'),
            MonsterAbility(name='Steam Breath (Recharge 5–6)', description="Constitution Saving Throw: DC 19, each creature in a 60-foot Cone. Failure: 56 (16d6) Fire damage. Success: Half damage. Failure or Success: Being underwater doesn't grant Resistance to this Fire damage."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class Goristro(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Goristro",
            hp=310,
            ac=19,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 25, Ability.DEXTERITY.short_name: 11, Ability.CONSTITUTION.short_name: 25, Ability.INTELLIGENCE.short_name: 6, Ability.WISDOM.short_name: 13, Ability.CHARISMA.short_name: 14},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.HUGE, monster_type='Fiend (Demon)', alignment=Alignment.CHAOTIC_EVIL,
            ac_note="",
            hp_formula="23d12 + 161",
            speed_ground_ft=None, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='straight toward an enemy it can see.',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Darkvision 120 ft., Passive Perception 17",
            languages="Abyssal",
            traits=[
            MonsterAbility(name='Demonic Restoration', description='If the goristro dies outside the Abyss, its body dissolves into ichor, and it gains a new body instantly, reviving with all its Hit Points somewhere in the Abyss.'),
            MonsterAbility(name='Magic Resistance', description='The goristro has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Siege Monster', description='The goristro deals double damage to objects and structures.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The goristro makes one Brutal Gore attack and two Slam attacks.'),
            MonsterAbility(name='Brutal Gore', description='Melee Attack Roll: +13, reach 10 ft. Hit: 40 (6d10 + 7) Piercing damage. If the target is a Huge or smaller creature, it is pushed up to 20 feet straight away from the goristro and has the Prone condition.'),
            MonsterAbility(name='Slam', description='Melee Attack Roll: +13, reach 10 ft. Hit: 29 (4d10 + 7) Bludgeoning damage.'),
        ],
            bonus_actions=[
            MonsterAbility(name='Charge', description='The goristro moves up to half its Speed straight toward an enemy it can see.'),
        ],
            reactions=[],
            legendary_actions=[],
            legendary_resistances=0,
            lair_actions=[],
            mythic_actions=[],
        )


class SphinxOfValor(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Sphinx of Valor",
            hp=199,
            ac=17,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 22, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 20, Ability.INTELLIGENCE.short_name: 16, Ability.WISDOM.short_name: 23, Ability.CHARISMA.short_name: 18},
            saving_throws={},
            spell_slots={},
            cr="17",
            size=Size.LARGE, monster_type='Celestial', alignment=Alignment.LAWFUL_NEUTRAL,
            ac_note="",
            hp_formula="19d10 + 95",
            speed_ground_ft=40, speed_fly_ft=None, speed_climb_ft=None, speed_special_rules='',
            skills={},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[],
            condition_immunities=[],
            senses="Truesight 120 ft., Passive Perception 22",
            languages="Celestial, Common",
            traits=[
            MonsterAbility(name='Inscrutable', description='No magic can observe the sphinx remotely or detect its thoughts without its permission. Wisdom (Insight) checks made to ascertain its intentions or sincerity are made with Disadvantage.'),
            MonsterAbility(name='Legendary Resistance (3/Day, or 4/Day in Lair)', description='If the sphinx fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The sphinx makes two Claw attacks and uses Roar.'),
            MonsterAbility(name='Claw', description='Melee Attack Roll: +12, reach 5 ft. Hit: 20 (4d6 + 6) Slashing damage.'),
            MonsterAbility(name='Roar (3/Day)', description='The sphinx emits a magical roar. Whenever it roars, the roar has a different effect, as detailed below (the sequence resets when it takes a Long Rest):'),
            MonsterAbility(name='First Roar', description='. Wisdom Saving Throw: DC 20, each enemy in a 500-foot Emanation originating from the sphinx. Failure: The target has the Frightened condition for 1 minute.'),
            MonsterAbility(name='Second Roar', description='. Wisdom Saving Throw: DC 20, each enemy in a 500-foot Emanation originating from the sphinx. Failure: The target has the Paralyzed condition, and it repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.'),
            MonsterAbility(name='Third Roar', description='. Constitution Saving Throw: DC 20, each enemy in a 500-foot Emanation originating from the sphinx. Failure: 44 (8d10) Thunder damage, and the target has the Prone condition. Success: Half damage only.'),
            MonsterAbility(name='Spellcasting', description='The sphinx casts one of the following spells, requiring no Material components and using Wisdom as the spellcasting ability (spell save DC 20):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Arcane Prowl', description='The sphinx can teleport up to 30 feet to an unoccupied space it can see, and it makes one Claw attack.'),
            MonsterAbility(name='Weight of Years', description="Constitution Saving Throw: DC 16, one creature the sphinx can see within 120 feet. Failure: The target gains 1 Exhaustion level. While the target has any Exhaustion levels, it appears 3d10 years older. Failure or Success: The sphinx can't take this action again until the start of its next turn."),
        ],
            legendary_resistances=3,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = [
    "AdultGoldDragon",
    "AdultRedDragon",
    "DeathKnight",
    "Dracolich",
    "DragonTurtle",
    "Goristro",
    "SphinxOfValor",
]
