# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    Size,
    Skill,
)
from Definitions import Ability


class AncientGoldDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Gold Dragon",
            hp=546,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 30, Ability.DEXTERITY.short_name: 14, Ability.CONSTITUTION.short_name: 29, Ability.INTELLIGENCE.short_name: 18, Ability.WISDOM.short_name: 17, Ability.CHARISMA.short_name: 28},
            saving_throws={Ability.DEXTERITY.short_name: 9, Ability.WISDOM.short_name: 10},
            spell_slots={},
            cr="24",
            monster_type='Dragon (Metallic)',
            alignment=Alignment.LAWFUL_GOOD,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="28d20 + 252",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.INSIGHT: 10, Skill.PERCEPTION: 17, Skill.PERSUASION: 16, Skill.STEALTH: 9},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 27",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to suc ceed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of (A) Spellcasting to cast Guiding Bolt (level 4 version) or (B) Weakening Breath.'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +17 to hit, reach 15 ft. Hit: 19 (2d8+ 10) Slashing damage plus 9 (2d8) Fire damage.'),
            MonsterAbility(name='Fire Breath (Recharge 5-6)', description='Dexterity Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 71 (13d10) Fire damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 24):'),
            MonsterAbility(name='Weakening Breath', description="Strength Saving Throw: DC 24, each creature that isn't currently affected by this breath in a 90-foot Cone. Failure: The target has Disadvantage on Strength-based D20 Tests and subtracts 5 (1d10) from its damage rolls. It repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Banish', description="Charisma Saving Throw: DC 24, one creature the dragon can see within 120 feet. Failure: 24 (7d6) Force damage, and the target has the Incapacitated condition and is transported to a harmless demiplane until the start of the dragon's next turn, at which point it reappears in an unoccupied space of the dragon's choice within 120 feet of the dragon. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Guiding Light', description='The dragon uses Spellcasting to cast Guiding Bolt (level 4 version).'),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class AncientRedDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Red Dragon",
            hp=507,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 30, Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 29, Ability.INTELLIGENCE.short_name: 18, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 27},
            saving_throws={Ability.DEXTERITY.short_name: 7, Ability.WISDOM.short_name: 9},
            spell_slots={},
            cr="24",
            monster_type='Dragon (Chromatic)',
            alignment=Alignment.CHAOTIC_EVIL,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="26d20 + 234",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=40,
            speed_special_rules='',
            skills={Skill.PERCEPTION: 16, Skill.STEALTH: 7},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 26",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Scorching Ray (level 3 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +17, reach 15 ft. Hit: 19 (2d8 + 10) Slashing damage plus 10 (3d6) Fire damage.'),
            MonsterAbility(name='Fire Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 24, each creature in a 90-foot Cone. Failure: 91 (26d6) Fire damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 23, +15 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Commanding Presence', description="The dragon uses Spellcasting to cast Command (level 2 version). The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Fiery Rays', description="The dragon uses Spellcasting to cast Scorching Ray (level 3 version). The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['AncientGoldDragon', 'AncientRedDragon']
