# Auto-generated by generate_monsters.py — do not edit manually
from Combat.Definitions import (
    Alignment,
    Condition,
    DamageType,
    DamageTypeEntry,
    ExtendedCombatantData,
    MonsterAbility,
    Size,
    Skill,
)
from Definitions import Ability


class AncientBlackDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Black Dragon",
            hp=367,
            ac=22,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 27, Ability.DEXTERITY.short_name: 14, Ability.CONSTITUTION.short_name: 25, Ability.INTELLIGENCE.short_name: 16, Ability.WISDOM.short_name: 15, Ability.CHARISMA.short_name: 22},
            saving_throws={Ability.DEXTERITY.short_name: 9, Ability.CONSTITUTION.short_name: 7, Ability.WISDOM.short_name: 9},
            spell_slots={},
            cr="21",
            monster_type='Dragon (Chromatic)',
            alignment=Alignment.CHAOTIC_EVIL,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="21d20 + 147",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=None,
            speed_special_rules='swim 40 ft.',
            skills={Skill.PERCEPTION: 16, Skill.STEALTH: 9},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.ACID], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 26",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Amphibious', description='The dragon can breathe air and water.'),
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description="The dragon makes three Rend attacks. It can replace one attack with a use of Spellcasting to cast Melf's Acid Arrow (level 4 version)."),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +15, reach 15 ft. Hit: 17 (2d8 + 8) Slashing damage plus 9 (2d8) Acid damage.'),
            MonsterAbility(name='Acid Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 22, each creature in a 90-foot-long, 10-foot-wide Line. Failure: 67 (15d8) Acid damage. Success: Half damage.'),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 21, +13 to hit with spell attacks):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Cloud of Insects', description="Dexterity Saving Throw: DC 21, one creature the dragon can see within 120 feet. Failure: 33 (6d10) Poison damage, and the target has Disadvantage on saving throws to maintain Concentration until the end of its next turn. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Frightful Presence', description="The dragon uses Spellcasting to cast Fear. The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class AncientCopperDragon(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Ancient Copper Dragon",
            hp=367,
            ac=21,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 27, Ability.DEXTERITY.short_name: 12, Ability.CONSTITUTION.short_name: 25, Ability.INTELLIGENCE.short_name: 20, Ability.WISDOM.short_name: 17, Ability.CHARISMA.short_name: 22},
            saving_throws={Ability.DEXTERITY.short_name: 8, Ability.WISDOM.short_name: 10},
            spell_slots={},
            cr="21",
            monster_type='Dragon (Metallic)',
            alignment=Alignment.CHAOTIC_GOOD,
            size=Size.GARGANTUAN,
            ac_note="",
            hp_formula="21d20 + 147",
            speed_ground_ft=40,
            speed_fly_ft=80,
            speed_climb_ft=40,
            speed_special_rules='',
            skills={Skill.DECEPTION: 13, Skill.PERCEPTION: 17, Skill.STEALTH: 8},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.ACID], note=''),
            ],
            condition_immunities=[],
            senses="Blindsight 60 ft., Darkvision 120 ft., Passive Perception 27",
            languages="Common, Draconic",
            traits=[
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the dragon fails a saving throw, it can choose to succeed instead.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The dragon makes three Rend attacks. It can replace one attack with a use of (A) Slowing Breath or (B) Spellcasting to cast Mind Spike (level 5 version).'),
            MonsterAbility(name='Rend', description='Melee Attack Roll: +15, reach 15 ft. Hit: 19 (2d10 + 8) Slashing damage plus 9 (2d8) Acid damage.'),
            MonsterAbility(name='Acid Breath (Recharge 5–6)', description='Dexterity Saving Throw: DC 22, each creature in an 90-foot-long, 10-foot-wide Line. Failure: 63 (14d8) Acid damage. Success: Half damage.'),
            MonsterAbility(name='Slowing Breath', description="Constitution Saving Throw: DC 22, each creature in a 90-foot Cone. Failure: The target can't take Reactions; its Speed is halved; and it can take either an action or a Bonus Action on its turn, not both. This effect lasts until the end of its next turn."),
            MonsterAbility(name='Spellcasting', description='The dragon casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 21):'),
        ],
            bonus_actions=[],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Giggling Magic', description="Charisma Saving Throw: DC 21, one creature the dragon can see within 120 feet. Failure: 31 (9d6) Psychic damage. Until the end of its next turn, the target rolls 1d8 whenever it makes an ability check or attack roll and subtracts the number rolled from the D20 Test. Failure or Success: The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Mind Jolt', description="The dragon uses Spellcasting to cast Mind Spike (level 5 version). The dragon can't take this action again until the start of its next turn."),
            MonsterAbility(name='Pounce', description='The dragon moves up to half its Speed, and it makes one Rend attack.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class Archhag(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Arch-hag",
            hp=333,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 24, Ability.DEXTERITY.short_name: 15, Ability.CONSTITUTION.short_name: 23, Ability.INTELLIGENCE.short_name: 19, Ability.WISDOM.short_name: 19, Ability.CHARISMA.short_name: 25},
            saving_throws={Ability.DEXTERITY.short_name: 9, Ability.WISDOM.short_name: 11},
            spell_slots={},
            cr="21",
            monster_type='Fey',
            alignment=Alignment.NEUTRAL_EVIL,
            size=Size.LARGE,
            ac_note="",
            hp_formula="29d10 + 174",
            speed_ground_ft=40,
            speed_fly_ft=None,
            speed_climb_ft=None,
            speed_special_rules='',
            skills={Skill.DECEPTION: 14, Skill.PERCEPTION: 11, Skill.PERSUASION: 21},
            damage_vulnerabilities=[],
            damage_resistances=[
                DamageTypeEntry(damage_types=[DamageType.COLD], note=''),
                DamageTypeEntry(damage_types=[DamageType.FIRE], note=''),
                DamageTypeEntry(damage_types=[DamageType.PSYCHIC], note=''),
            ],
            damage_immunities=[],
            condition_immunities=[Condition.CHARMED, Condition.EXHAUSTION, Condition.FRIGHTENED],
            senses="Truesight 60 ft., Passive Perception 21",
            languages="All",
            traits=[
            MonsterAbility(name='Coven Magic', description="While within 30 feet of at least two hag allies, the hag can cast one of the following spells, requiring no Material components, using the spell's normal casting time, and using Intelligence as the spellcasting ability (spell save DC 19): Augury, Find Familiar, Identify, Locate Object, Scrying, or Unseen Servant. The hag must finish a Long Rest before using this trait to cast that spell again."),
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the hag fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Magic Resistance', description='The hag has Advantage on saving throws against spells and other magical effects.'),
            MonsterAbility(name='Spiteful Escape', description="When the hag drops to 0 Hit Points, it dies only if it is within 30 feet of its anathema (a thing the DM chooses as the hag's most hated thing). Otherwise, the hag drops to 1 Hit Point and teleports to a harmless demiplane, and it can't return to the plane it left for 2d6 days. When the hag teleports away, each creature within 60 feet of the space it left is cursed. Until the curse ends, a creature has Disadvantage on ability checks and saving throws, and the hag knows its location anywhere in the multiverse."),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The hag makes two Spectral Claw attacks and uses Crackling Wave.'),
            MonsterAbility(name='Spectral Claw', description='Melee or Ranged Attack Roll: +14, reach 10 ft. or range 60 ft. Hit: 17 (3d6 + 7) Force damage. If the target is a Large or smaller creature, it has the Prone condition.'),
            MonsterAbility(name='Crackling Wave', description="Dexterity Saving Throw: DC 22, each creature in a 60-foot Cone. Failure: 32 (5d12) Lightning damage. Success: Half damage. Failure or Success: The target is cursed until the end of the hag's next turn. The target can't take Reactions until the curse ends."),
            MonsterAbility(name='Spellcasting', description='The hag casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 22):'),
        ],
            bonus_actions=[
            MonsterAbility(name='Witch Strike', description='Each creature cursed by the hag and within 60 feet of it takes 14 (4d6) Lightning damage.'),
        ],
            reactions=[
            MonsterAbility(name='Tongue Twister', description="The hag casts Counterspell in response to that spell's trigger, using the same spellcasting ability as Spellcasting. If the target fails its saving throw, it is cursed until the end of its next turn. Until the curse ends, the target can't cast spells with a Verbal component, and when it speaks, it says the opposite of what it means."),
        ],
            legendary_actions=[
            MonsterAbility(name="Hag's Swipe", description='The hag makes one Spectral Claw attack.'),
            MonsterAbility(name='Malicious Magic', description="The hag uses Spellcasting to cast Dimension Door or Hypnotic Pattern. The hag can't take this action again until the start of its next turn."),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class Lich(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Lich",
            hp=315,
            ac=20,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 11, Ability.DEXTERITY.short_name: 16, Ability.CONSTITUTION.short_name: 16, Ability.INTELLIGENCE.short_name: 21, Ability.WISDOM.short_name: 14, Ability.CHARISMA.short_name: 16},
            saving_throws={Ability.DEXTERITY.short_name: 10, Ability.CONSTITUTION.short_name: 10, Ability.INTELLIGENCE.short_name: 12, Ability.WISDOM.short_name: 9},
            spell_slots={},
            cr="21",
            monster_type='Undead (Wizard)',
            alignment=Alignment.NEUTRAL_EVIL,
            size=Size.MEDIUM,
            ac_note="",
            hp_formula="42d8 + 126",
            speed_ground_ft=30,
            speed_fly_ft=None,
            speed_climb_ft=None,
            speed_special_rules='',
            skills={Skill.ARCANA: 19, Skill.HISTORY: 12, Skill.INSIGHT: 9, Skill.PERCEPTION: 9},
            damage_vulnerabilities=[],
            damage_resistances=[
                DamageTypeEntry(damage_types=[DamageType.COLD], note=''),
                DamageTypeEntry(damage_types=[DamageType.LIGHTNING], note=''),
            ],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.NECROTIC], note=''),
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
            ],
            condition_immunities=[Condition.CHARMED, Condition.EXHAUSTION, Condition.FRIGHTENED, Condition.PARALYZED, Condition.POISONED],
            senses="Truesight 120 ft., Passive Perception 19",
            languages="All",
            traits=[
            MonsterAbility(name='Legendary Resistance (4/Day, or 5/Day in Lair)', description='If the lich fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Spirit Jar', description="If destroyed, the lich reforms in 1d10 days if it has a spirit jar, reviving with all its Hit Points. The new body appears in an unoccupied space within the lich's lair."),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The lich makes three attacks, using Eldritch Burst or Paralyzing Touch in any combination.'),
            MonsterAbility(name='Eldritch Burst', description='Melee or Ranged Attack Roll: +12, reach 5 ft. or range 120 ft. Hit: 31 (4d12 + 5) Force damage.'),
            MonsterAbility(name='Paralyzing Touch', description="Melee Attack Roll: +12, reach 5 ft. Hit: 15 (3d6 + 5) Cold damage, and the target has the Paralyzed condition until the start of the lich's next turn."),
            MonsterAbility(name='Spellcasting', description='The lich casts one of the following spells, using Intelligence as the spellcasting ability (spell save DC 20):'),
        ],
            bonus_actions=[],
            reactions=[
            MonsterAbility(name='Protective Magic', description="The lich casts Counterspell or Shield in response to the spell's trigger, using the same spellcasting ability as Spellcasting."),
        ],
            legendary_actions=[
            MonsterAbility(name='Deathly Teleport', description='The lich teleports up to 60 feet to an unoccupied space it can see, and each creature within 10 feet of the space it left takes 11 (2d10) Necrotic damage.'),
            MonsterAbility(name='Disrupt Life', description="Constitution Saving Throw: DC 20, each creature that isn't an Undead in a 20-foot Emanation originating from the lich. Failure: 31 (9d6) Necrotic damage. Success: Half damage. Failure or Success: The lich can't take this action again until the start of its next turn."),
            MonsterAbility(name='Frightening Gaze', description="The lich casts Fear, using the same spellcasting ability as Spellcasting. The lich can't take this action again until the start of its next turn."),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


class Solar(ExtendedCombatantData):
    def __init__(self):
        super().__init__(
            combatant_type="Solar",
            hp=297,
            ac=21,
            temp_hp=0,
            conditions=[],
            ability_scores={Ability.STRENGTH.short_name: 26, Ability.DEXTERITY.short_name: 22, Ability.CONSTITUTION.short_name: 26, Ability.INTELLIGENCE.short_name: 25, Ability.WISDOM.short_name: 25, Ability.CHARISMA.short_name: 30},
            saving_throws={},
            spell_slots={},
            cr="21",
            monster_type='Celestial (Angel)',
            alignment=Alignment.LAWFUL_GOOD,
            size=Size.LARGE,
            ac_note="",
            hp_formula="22d10 + 176",
            speed_ground_ft=50,
            speed_fly_ft=150,
            speed_climb_ft=None,
            speed_special_rules='hover',
            skills={Skill.PERCEPTION: 14},
            damage_vulnerabilities=[],
            damage_resistances=[],
            damage_immunities=[
                DamageTypeEntry(damage_types=[DamageType.POISON], note=''),
                DamageTypeEntry(damage_types=[DamageType.RADIANT], note=''),
            ],
            condition_immunities=[Condition.CHARMED, Condition.EXHAUSTION, Condition.FRIGHTENED, Condition.POISONED],
            senses="Truesight 120 ft., Passive Perception 24",
            languages="All; telepathy 120 ft",
            traits=[
            MonsterAbility(name='Divine Awareness', description='The solar knows if it hears a lie.'),
            MonsterAbility(name='Exalted Restoration', description='If the solar dies outside Mount Celestia, its body disappears, and it gains a new body instantly, reviving with all its Hit Points somewhere in Mount Celestia.'),
            MonsterAbility(name='Legendary Resistance (4/Day)', description='If the solar fails a saving throw, it can choose to succeed instead.'),
            MonsterAbility(name='Magic Resistance', description='The solar has Advantage on saving throws against spells and other magical effects.'),
        ],
            actions=[
            MonsterAbility(name='Multiattack', description='The solar makes two Flying Sword attacks. It can replace one attack with a use of Slaying Bow.'),
            MonsterAbility(name='Flying Sword', description="Melee or Ranged Attack Roll: +15, reach 10 ft. or range 120 ft. Hit: 22 (4d6 + 8) Slashing damage plus 36 (8d8) Radiant damage. Hit or Miss: The sword magically returns to the solar's hand or hovers within 5 feet of the solar immediately after a ranged attack."),
            MonsterAbility(name='Slaying Bow', description='Dexterity Saving Throw: DC 21, one creature the solar can see within 600 feet. Failure: If the creature has 100 Hit Points or fewer, it dies. It otherwise takes 24 (4d8 + 6) Piercing damage plus 36 (8d8) Radiant damage.'),
            MonsterAbility(name='Spellcasting', description='The solar casts one of the following spells, requiring no Material components and using Charisma as the spellcasting ability (spell save DC 25):'),
        ],
            bonus_actions=[
            MonsterAbility(name='Divine Aid (3/Day)', description='The solar casts Cure Wounds (level 2 version), Lesser Restoration, or Remove Curse, using the same spellcasting ability as Spellcasting.'),
        ],
            reactions=[],
            legendary_actions=[
            MonsterAbility(name='Blinding Gaze', description="Constitution Saving Throw: DC 25, one creature the solar can see within 120 feet. Failure: The target has the Blinded condition for 1 minute. Failure or Success: The solar can't take this action again until the start of its next turn."),
            MonsterAbility(name='Radiant Teleport', description='The solar teleports up to 60 feet to an unoccupied space it can see. Dexterity Saving Throw: DC 25, each creature in a 10-foot Emanation originating from the solar at its destination space. Failure: 11 (2d10) Radiant damage. Success: Half damage.'),
        ],
            legendary_resistances=4,
            lair_actions=[],
            mythic_actions=[],
        )


__all__ = ['AncientBlackDragon', 'AncientCopperDragon', 'Archhag', 'Lich', 'Solar']
