from enum import Enum

class SorcererLevel0Spells(str, Enum):
    ACID_SPLASH = "Acid Splash"
    BLADE_WARD = "Blade Ward"
    CHILL_TOUCH = "Chill Touch"
    CONTROL_FLAMES = "Control Flames"
    CREATE_BONFIRE = "Create Bonfire"
    DANCING_LIGHTS = "Dancing Lights"
    ELEMENTALISM = "Elementalism"
    FIRE_BOLT = "Fire Bolt"
    FRIENDS = "Friends"
    FROSTBITE = "Frostbite"
    GUST = "Gust"
    INFESTATION = "Infestation"
    LIGHT = "Light"
    MAGE_HAND = "Mage Hand"
    MENDING = "Mending"
    MESSAGE = "Message"
    MIND_SLIVER = "Mind Sliver"
    MINOR_ILLUSION = "Minor Illusion"
    MOLD_EARTH = "Mold Earth"
    POISON_SPRAY = "Poison Spray"
    PRESTIDIGITATION = "Prestidigitation"
    RAY_OF_FROST = "Ray of Frost"
    SHAPE_WATER = "Shape Water"
    SHOCKING_GRASP = "Shocking Grasp"
    SORCEROUS_BURST = "Sorcerous Burst"
    THUNDERCLAP = "Thunderclap"
    TRUE_STRIKE = "True Strike"

class SorcererLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    BURNING_HANDS = "Burning Hands"
    BUZZING_BEE = "Buzzing Bee"
    CATAPULT = "Catapult"
    CHAOS_BOLT = "Chaos Bolt"
    CHARM_PERSON = "Charm Person"
    CHROMATIC_ORB = "Chromatic Orb"
    COLOR_SPRAY = "Color Spray"
    COMPREHEND_LANGUAGES = "Comprehend Languages"
    DETECT_MAGIC = "Detect Magic"
    DISGUISE_SELF = "Disguise Self"
    DISTORT_VALUE = "Distort Value"
    EARTH_TREMOR = "Earth Tremor"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    FALSE_LIFE = "False Life"
    FEATHER_FALL = "Feather Fall"
    FOG_CLOUD = "Fog Cloud"
    GREASE = "Grease"
    ICE_KNIFE = "Ice Knife"
    JUMP = "Jump"
    MAGE_ARMOR = "Mage Armor"
    MAGIC_MISSILE = "Magic Missile"
    RAY_OF_SICKNESS = "Ray of Sickness"
    SHIELD = "Shield"
    SILENT_IMAGE = "Silent Image"
    SILVERY_BARBS = "Silvery Barbs"
    SLEEP = "Sleep"
    SPELLFIRE_FLARE = "Spellfire Flare"
    THUNDERWAVE = "Thunderwave"
    WITCH_BOLT = "Witch Bolt"

class SorcererLevel2Spells(str, Enum):
    AGANAZZARS_SCORCHER = "Aganazzar's Scorcher"
    AIR_BUBBLE = "Air Bubble"
    ALTER_SELF = "Alter Self"
    ARCANE_VIGOR = "Arcane Vigor"
    BLINDNESS_DEAFNESS = "Blindness/Deafness"
    BLUR = "Blur"
    CLOUD_OF_DAGGERS = "Cloud of Daggers"
    CROWN_OF_MADNESS = "Crown of Madness"
    DARKNESS = "Darkness"
    DARKVISION = "Darkvision"
    DEATH_ARMOR = "Death Armor"
    DETECT_THOUGHTS = "Detect Thoughts"
    DRAGONS_BREATH = "Dragon's Breath"
    DUST_DEVIL = "Dust Devil"
    EARTHBIND = "Earthbind"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    FLAME_BLADE = "Flame Blade"
    FLAMING_SPHERE = "Flaming Sphere"
    GUST_OF_WIND = "Gust of Wind"
    HOLD_PERSON = "Hold Person"
    INVISIBILITY = "Invisibility"
    KINETIC_JAUNT = "Kinetic Jaunt"
    KNOCK = "Knock"
    LEVITATE = "Levitate"
    MAGIC_WEAPON = "Magic Weapon"
    MAXIMILLIANS_EARTHEN_GRASP = "Maximillian's Earthen Grasp"
    MIND_SPIKE = "Mind Spike"
    MIRROR_IMAGE = "Mirror Image"
    MISTY_STEP = "Misty Step"
    NATHAIRS_MISCHIEF = "Nathair's Mischief"
    PHANTASMAL_FORCE = "Phantasmal Force"
    PYROTECHNICS = "Pyrotechnics"
    RIMES_BINDING_ICE = "Rime's Binding Ice"
    SCORCHING_RAY = "Scorching Ray"
    SEE_INVISIBILITY = "See Invisibility"
    SHADOW_BLADE = "Shadow Blade"
    SHATTER = "Shatter"
    SNILLOCS_SNOWBALL_SWARM = "Snilloc's Snowball Swarm"
    SPIDER_CLIMB = "Spider Climb"
    SPRAY_OF_CARDS = "Spray of Cards"
    SUGGESTION = "Suggestion"
    VORTEX_WARP = "Vortex Warp"
    WARDING_WIND = "Warding Wind"
    WARP_SENSE = "Warp Sense"
    WEB = "Web"
    WITHER_AND_BLOOM = "Wither and Bloom"

class SorcererLevel3Spells(str, Enum):
    ANTAGONIZE = "Antagonize"
    ASHARDALONS_STRIDE = "Ashardalon's Stride"
    ASTRAL_FLOOD = "Astral Flood"
    BLINK = "Blink"
    CACOPHONIC_SHIELD = "Cacophonic Shield"
    CATNAP = "Catnap"
    CLAIRVOYANCE = "Clairvoyance"
    COUNTERSPELL = "Counterspell"
    DAYLIGHT = "Daylight"
    DISPEL_MAGIC = "Dispel Magic"
    ENEMIES_ABOUND = "Enemies Abound"
    ERUPTING_EARTH = "Erupting Earth"
    FEAR = "Fear"
    FIREBALL = "Fireball"
    FLAME_ARROWS = "Flame Arrows"
    FLY = "Fly"
    GASEOUS_FORM = "Gaseous Form"
    HASTE = "Haste"
    HYPNOTIC_PATTERN = "Hypnotic Pattern"
    INCITE_GREED = "Incite Greed"
    LAERALS_SILVER_LANCE = "Laeral's Silver Lance"
    LIGHTNING_BOLT = "Lightning Bolt"
    MAJOR_IMAGE = "Major Image"
    MELFS_MINUTE_METEORS = "Melf's Minute Meteors"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    SLEET_STORM = "Sleet Storm"
    SLOW = "Slow"
    STINKING_CLOUD = "Stinking Cloud"
    TIDAL_WAVE = "Tidal Wave"
    TONGUES = "Tongues"
    VAMPIRIC_TOUCH = "Vampiric Touch"
    WALL_OF_WATER = "Wall of Water"
    WATER_BREATHING = "Water Breathing"
    WATER_WALK = "Water Walk"

class SorcererLevel4Spells(str, Enum):
    BACKLASH = "Backlash"
    BANISHMENT = "Banishment"
    BLIGHT = "Blight"
    CHARM_MONSTER = "Charm Monster"
    CONFUSION = "Confusion"
    DIMENSION_DOOR = "Dimension Door"
    DOMINATE_BEAST = "Dominate Beast"
    FIRE_SHIELD = "Fire Shield"
    GATE_SEAL = "Gate Seal"
    GREATER_INVISIBILITY = "Greater Invisibility"
    ICE_STORM = "Ice Storm"
    POLYMORPH = "Polymorph"
    RAULOTHIMS_PSYCHIC_LANCE = "Raulothim's Psychic Lance"
    SICKENING_RADIANCE = "Sickening Radiance"
    SPELLFIRE_STORM = "Spellfire Storm"
    SPIRIT_OF_DEATH = "Spirit of Death"
    STONESKIN = "Stoneskin"
    STORM_SPHERE = "Storm Sphere"
    VITRIOLIC_SPHERE = "Vitriolic Sphere"
    WALL_OF_FIRE = "Wall of Fire"
    WATERY_SPHERE = "Watery Sphere"

class SorcererLevel5Spells(str, Enum):
    ANIMATE_OBJECTS = "Animate Objects"
    BIGBYS_HAND = "Bigby's Hand"
    CLOUDKILL = "Cloudkill"
    CONE_OF_COLD = "Cone of Cold"
    CONTROL_WINDS = "Control Winds"
    CREATION = "Creation"
    DOMINATE_PERSON = "Dominate Person"
    ENERVATION = "Enervation"
    FAR_STEP = "Far Step"
    HOLD_MONSTER = "Hold Monster"
    IMMOLATION = "Immolation"
    INSECT_PLAGUE = "Insect Plague"
    SEEMING = "Seeming"
    SKILL_EMPOWERMENT = "Skill Empowerment"
    SONGALS_ELEMENTAL_SUFFUSION = "Songal's Elemental Suffusion"
    SUMMON_DRACONIC_SPIRIT = "Summon Draconic Spirit"
    SYNAPTIC_STATIC = "Synaptic Static"
    TELEKINESIS = "Telekinesis"
    TELEPORTATION_CIRCLE = "Teleportation Circle"
    WALL_OF_LIGHT = "Wall of Light"
    WALL_OF_STONE = "Wall of Stone"

class SorcererLevel6Spells(str, Enum):
    ARCANE_GATE = "Arcane Gate"
    CHAIN_LIGHTNING = "Chain Lightning"
    CIRCLE_OF_DEATH = "Circle of Death"
    DISINTEGRATE = "Disintegrate"
    ELMINSTERS_EFFULGENT_SPHERES = "Elminster's Effulgent Spheres"
    EYEBITE = "Eyebite"
    FIZBANS_PLATINUM_SHIELD = "Fizban's Platinum Shield"
    FLESH_TO_STONE = "Flesh to Stone"
    GLOBE_OF_INVULNERABILITY = "Globe of Invulnerability"
    INVESTITURE_OF_FLAME = "Investiture of Flame"
    INVESTITURE_OF_ICE = "Investiture of Ice"
    INVESTITURE_OF_STONE = "Investiture of Stone"
    INVESTITURE_OF_WIND = "Investiture of Wind"
    LEOMUNDS_LAMENTABLE_BELABORMENT = "Leomund's Lamentable Belaborment"
    MASS_SUGGESTION = "Mass Suggestion"
    MENTAL_PRISON = "Mental Prison"
    MOVE_EARTH = "Move Earth"
    OTILUKES_FREEZING_SPHERE = "Otiluke's Freezing Sphere"
    SCATTER = "Scatter"
    SUNBEAM = "Sunbeam"
    TRUE_SEEING = "True Seeing"

class SorcererLevel7Spells(str, Enum):
    CROWN_OF_STARS = "Crown of Stars"
    DELAYED_BLAST_FIREBALL = "Delayed Blast Fireball"
    DRACONIC_TRANSFORMATION = "Draconic Transformation"
    ETHEREALNESS = "Etherealness"
    FINGER_OF_DEATH = "Finger of Death"
    FIRE_STORM = "Fire Storm"
    PLANE_SHIFT = "Plane Shift"
    POWER_WORD_PAIN = "Power Word Pain"
    PRISMATIC_SPRAY = "Prismatic Spray"
    REVERSE_GRAVITY = "Reverse Gravity"
    SIMBULS_SYNOSTODWEOMER = "Simbul's Synostodweomer"
    TELEPORT = "Teleport"

class SorcererLevel8Spells(str, Enum):
    ABI_DALZIMS_HORRID_WILTING = "Abi-Dalzim's Horrid Wilting"
    DEMIPLANE = "Demiplane"
    DOMINATE_MONSTER = "Dominate Monster"
    EARTHQUAKE = "Earthquake"
    INCENDIARY_CLOUD = "Incendiary Cloud"
    POWER_WORD_STUN = "Power Word Stun"
    SUNBURST = "Sunburst"

class SorcererLevel9Spells(str, Enum):
    BLADE_OF_DISASTER = "Blade of Disaster"
    GATE = "Gate"
    MASS_POLYMORPH = "Mass Polymorph"
    METEOR_SWARM = "Meteor Swarm"
    POWER_WORD_KILL = "Power Word Kill"
    PSYCHIC_SCREAM = "Psychic Scream"
    TIME_STOP = "Time Stop"
    WISH = "Wish"

class ArtificerLevel0Spells(str, Enum):
    ACID_SPLASH = "Acid Splash"
    BOOMING_BLADE = "Booming Blade"
    CREATE_BONFIRE = "Create Bonfire"
    DANCING_LIGHTS = "Dancing Lights"
    ELEMENTALISM = "Elementalism"
    FIRE_BOLT = "Fire Bolt"
    FROSTBITE = "Frostbite"
    GREEN_FLAME_BLADE = "Green-Flame Blade"
    GUIDANCE = "Guidance"
    LIGHT = "Light"
    LIGHTNING_LURE = "Lightning Lure"
    MAGE_HAND = "Mage Hand"
    MAGIC_STONE = "Magic Stone"
    MESSAGE = "Message"
    POISON_SPRAY = "Poison Spray"
    PRESTIDIGITATION = "Prestidigitation"
    RAY_OF_FROST = "Ray of Frost"
    RESISTANCE = "Resistance"
    SHOCKING_GRASP = "Shocking Grasp"
    SPARE_THE_DYING = "Spare the Dying"
    SWORD_BURST = "Sword Burst"
    THORN_WHIP = "Thorn Whip"
    THUNDERCLAP = "Thunderclap"
    TRUE_STRIKE = "True Strike"

class ArtificerLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    ALARM = "Alarm"
    CATAPULT = "Catapult"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_MAGIC = "Detect Magic"
    DISGUISE_SELF = "Disguise Self"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    FAERIE_FIRE = "Faerie Fire"
    FALSE_LIFE = "False Life"
    FEATHER_FALL = "Feather Fall"
    GREASE = "Grease"
    IDENTIFY = "Identify"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    PURIFY_FOOD_AND_DRINK = "Purify Food and Drink"
    SANCTUARY = "Sanctuary"
    SNARE = "Snare"
    TASHAS_CAUSTIC_BREW = "Tasha's Caustic Brew"

class ArtificerLevel2Spells(str, Enum):
    AID = "Aid"
    AIR_BUBBLE = "Air Bubble"
    ALTER_SELF = "Alter Self"
    ARCANE_LOCK = "Arcane Lock"
    ARCANE_VIGOR = "Arcane Vigor"
    BLUR = "Blur"
    CONTINUAL_FLAME = "Continual Flame"
    DARKVISION = "Darkvision"
    DRAGONS_BREATH = "Dragon's Breath"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    HEAT_METAL = "Heat Metal"
    HOMUNCULUS_SERVANT = "Homunculus Servant"
    INVISIBILITY = "Invisibility"
    KINETIC_JAUNT = "Kinetic Jaunt"
    LESSER_RESTORATION = "Lesser Restoration"
    LEVITATE = "Levitate"
    MAGIC_MOUTH = "Magic Mouth"
    MAGIC_WEAPON = "Magic Weapon"
    PROTECTION_FROM_POISON = "Protection from Poison"
    PYROTECHNICS = "Pyrotechnics"
    ROPE_TRICK = "Rope Trick"
    SEE_INVISIBILITY = "See Invisibility"
    SKYWRITE = "Skywrite"
    SPIDER_CLIMB = "Spider Climb"
    TORTOISE_SHELL = "Tortoise Shell"
    VORTEX_WARP = "Vortex Warp"
    WEB = "Web"

class ArtificerLevel3Spells(str, Enum):
    ASHARDALONS_STRIDE = "Ashardalon's Stride"
    BLINK = "Blink"
    CATNAP = "Catnap"
    CREATE_FOOD_AND_WATER = "Create Food and Water"
    DISPEL_MAGIC = "Dispel Magic"
    ELEMENTAL_WEAPON = "Elemental Weapon"
    FLAME_ARROWS = "Flame Arrows"
    FLY = "Fly"
    GLYPH_OF_WARDING = "Glyph of Warding"
    HASTE = "Haste"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    REVIVIFY = "Revivify"
    TINY_SERVANT = "Tiny Servant"
    WATER_BREATHING = "Water Breathing"
    WATER_WALK = "Water Walk"

class ArtificerLevel4Spells(str, Enum):
    ARCANE_EYE = "Arcane Eye"
    ELEMENTAL_BANE = "Elemental Bane"
    FABRICATE = "Fabricate"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    LEOMUNDS_SECRET_CHEST = "Leomund's Secret Chest"
    MORDENKAINENS_FAITHFUL_HOUND = "Mordenkainen's Faithful Hound"
    MORDENKAINENS_PRIVATE_SANCTUM = "Mordenkainen's Private Sanctum"
    OTILUKES_RESILIENT_SPHERE = "Otiluke's Resilient Sphere"
    STONE_SHAPE = "Stone Shape"
    STONESKIN = "Stoneskin"
    SUMMON_CONSTRUCT = "Summon Construct"

class ArtificerLevel5Spells(str, Enum):
    ANIMATE_OBJECTS = "Animate Objects"
    BIGBYS_HAND = "Bigby's Hand"
    CIRCLE_OF_POWER = "Circle of Power"
    CREATE_SPELLJAMMING_HELM = "Create Spelljamming Helm"
    CREATION = "Creation"
    GREATER_RESTORATION = "Greater Restoration"
    SKILL_EMPOWERMENT = "Skill Empowerment"
    TRANSMUTE_ROCK = "Transmute Rock"
    WALL_OF_STONE = "Wall of Stone"

class WizardLevel0Spells(str, Enum):
    ACID_SPLASH = "Acid Splash"
    BLADE_WARD = "Blade Ward"
    CHILL_TOUCH = "Chill Touch"
    CONTROL_FLAMES = "Control Flames"
    CREATE_BONFIRE = "Create Bonfire"
    DANCING_LIGHTS = "Dancing Lights"
    ELEMENTALISM = "Elementalism"
    FIRE_BOLT = "Fire Bolt"
    FRIENDS = "Friends"
    FROSTBITE = "Frostbite"
    GUST = "Gust"
    INFESTATION = "Infestation"
    LIGHT = "Light"
    MAGE_HAND = "Mage Hand"
    MENDING = "Mending"
    MESSAGE = "Message"
    MIND_SLIVER = "Mind Sliver"
    MINOR_ILLUSION = "Minor Illusion"
    MOLD_EARTH = "Mold Earth"
    POISON_SPRAY = "Poison Spray"
    PRESTIDIGITATION = "Prestidigitation"
    RAY_OF_FROST = "Ray of Frost"
    SHAPE_WATER = "Shape Water"
    SHOCKING_GRASP = "Shocking Grasp"
    THUNDERCLAP = "Thunderclap"
    TOLL_THE_DEAD = "Toll the Dead"
    TRUE_STRIKE = "True Strike"

class WizardLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    ALARM = "Alarm"
    BURNING_HANDS = "Burning Hands"
    BUZZING_BEE = "Buzzing Bee"
    CATAPULT = "Catapult"
    CAUSE_FEAR = "Cause Fear"
    CHARM_PERSON = "Charm Person"
    CHROMATIC_ORB = "Chromatic Orb"
    COLOR_SPRAY = "Color Spray"
    COMPREHEND_LANGUAGES = "Comprehend Languages"
    DETECT_MAGIC = "Detect Magic"
    DISGUISE_SELF = "Disguise Self"
    DISTORT_VALUE = "Distort Value"
    EARTH_TREMOR = "Earth Tremor"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    FALSE_LIFE = "False Life"
    FEATHER_FALL = "Feather Fall"
    FIND_FAMILIAR = "Find Familiar"
    FOG_CLOUD = "Fog Cloud"
    FROST_FINGERS = "Frost Fingers"
    GREASE = "Grease"
    ICE_KNIFE = "Ice Knife"
    IDENTIFY = "Identify"
    ILLUSORY_SCRIPT = "Illusory Script"
    JIMS_MAGIC_MISSILE = "Jim's Magic Missile"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    MAGE_ARMOR = "Mage Armor"
    MAGIC_MISSILE = "Magic Missile"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    RAY_OF_SICKNESS = "Ray of Sickness"
    SHIELD = "Shield"
    SILENT_IMAGE = "Silent Image"
    SILVERY_BARBS = "Silvery Barbs"
    SLEEP = "Sleep"
    SNARE = "Snare"
    SPELLFIRE_FLARE = "Spellfire Flare"
    TASHAS_HIDEOUS_LAUGHTER = "Tasha's Hideous Laughter"
    TENSERS_FLOATING_DISK = "Tenser's Floating Disk"
    THUNDERWAVE = "Thunderwave"
    UNSEEN_SERVANT = "Unseen Servant"
    WARDAWAY = "Wardaway"
    WITCH_BOLT = "Witch Bolt"

class WizardLevel2Spells(str, Enum):
    AGANAZZARS_SCORCHER = "Aganazzar's Scorcher"
    AIR_BUBBLE = "Air Bubble"
    ALTER_SELF = "Alter Self"
    ARCANE_LOCK = "Arcane Lock"
    ARCANE_VIGOR = "Arcane Vigor"
    AUGURY = "Augury"
    BLINDNESS_DEAFNESS = "Blindness/Deafness"
    BLUR = "Blur"
    BORROWED_KNOWLEDGE = "Borrowed Knowledge"
    CLOUD_OF_DAGGERS = "Cloud of Daggers"
    CONTINUAL_FLAME = "Continual Flame"
    CROWN_OF_MADNESS = "Crown of Madness"
    DARKNESS = "Darkness"
    DARKVISION = "Darkvision"
    DEATH_ARMOR = "Death Armor"
    DERYANS_HELPFUL_HOMUNCULI = "Deryan's Helpful Homunculi"
    DETECT_THOUGHTS = "Detect Thoughts"
    DRAGONS_BREATH = "Dragon's Breath"
    DUST_DEVIL = "Dust Devil"
    EARTHBIND = "Earthbind"
    ELMINSTERS_ELUSION = "Elminster's Elusion"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    FLAMING_SPHERE = "Flaming Sphere"
    FLOCK_OF_FAMILIARS = "Flock of Familiars"
    GENTLE_REPOSE = "Gentle Repose"
    GIFT_OF_GAB = "Gift of Gab"
    GUST_OF_WIND = "Gust of Wind"
    HOLD_PERSON = "Hold Person"
    INVISIBILITY = "Invisibility"
    JIMS_GLOWING_COIN = "Jim's Glowing Coin"
    KINETIC_JAUNT = "Kinetic Jaunt"
    KNOCK = "Knock"
    LEVITATE = "Levitate"
    LOCATE_OBJECT = "Locate Object"
    MAGIC_MOUTH = "Magic Mouth"
    MAGIC_WEAPON = "Magic Weapon"
    MAXIMILLIANS_EARTHEN_GRASP = "Maximillian's Earthen Grasp"
    MELFS_ACID_ARROW = "Melf's Acid Arrow"
    MIND_SPIKE = "Mind Spike"
    MIRROR_IMAGE = "Mirror Image"
    MISTY_STEP = "Misty Step"
    NATHAIRS_MISCHIEF = "Nathair's Mischief"
    NYSTULS_MAGIC_AURA = "Nystul's Magic Aura"
    PHANTASMAL_FORCE = "Phantasmal Force"
    PYROTECHNICS = "Pyrotechnics"
    RAY_OF_ENFEEBLEMENT = "Ray of Enfeeblement"
    RIMES_BINDING_ICE = "Rime's Binding Ice"
    ROPE_TRICK = "Rope Trick"
    SCORCHING_RAY = "Scorching Ray"
    SEE_INVISIBILITY = "See Invisibility"
    SHADOW_BLADE = "Shadow Blade"
    SHATTER = "Shatter"
    SKYWRITE = "Skywrite"
    SNILLOCS_SNOWBALL_SWARM = "Snilloc's Snowball Swarm"
    SPIDER_CLIMB = "Spider Climb"
    SPRAY_OF_CARDS = "Spray of Cards"
    SUGGESTION = "Suggestion"
    VORTEX_WARP = "Vortex Warp"
    WARDING_WIND = "Warding Wind"
    WARP_SENSE = "Warp Sense"
    WEB = "Web"
    WITHER_AND_BLOOM = "Wither and Bloom"

class WizardLevel3Spells(str, Enum):
    ANIMATE_DEAD = "Animate Dead"
    ANTAGONIZE = "Antagonize"
    ASHARDALONS_STRIDE = "Ashardalon's Stride"
    ASTRAL_FLOOD = "Astral Flood"
    BESTOW_CURSE = "Bestow Curse"
    BLINK = "Blink"
    CACOPHONIC_SHIELD = "Cacophonic Shield"
    CATNAP = "Catnap"
    CLAIRVOYANCE = "Clairvoyance"
    CONJURE_CONSTRUCTS = "Conjure Constructs"
    COUNTERSPELL = "Counterspell"
    DISPEL_MAGIC = "Dispel Magic"
    ENEMIES_ABOUND = "Enemies Abound"
    ERUPTING_EARTH = "Erupting Earth"
    FEAR = "Fear"
    FEIGN_DEATH = "Feign Death"
    FIREBALL = "Fireball"
    FLAME_ARROWS = "Flame Arrows"
    FLY = "Fly"
    GALDERS_TOWER = "Galder's Tower"
    GASEOUS_FORM = "Gaseous Form"
    GLYPH_OF_WARDING = "Glyph of Warding"
    HASTE = "Haste"
    HYPNOTIC_PATTERN = "Hypnotic Pattern"
    INCITE_GREED = "Incite Greed"
    LAERALS_SILVER_LANCE = "Laeral's Silver Lance"
    LEOMUNDS_TINY_HUT = "Leomund's Tiny Hut"
    LIGHTNING_BOLT = "Lightning Bolt"
    MAGIC_CIRCLE = "Magic Circle"
    MAJOR_IMAGE = "Major Image"
    MELFS_MINUTE_METEORS = "Melf's Minute Meteors"
    NONDETECTION = "Nondetection"
    PHANTOM_STEED = "Phantom Steed"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    PULSE_WAVE = "Pulse Wave"
    REMOVE_CURSE = "Remove Curse"
    SENDING = "Sending"
    SLEET_STORM = "Sleet Storm"
    SLOW = "Slow"
    SPEAK_WITH_DEAD = "Speak with Dead"
    STINKING_CLOUD = "Stinking Cloud"
    SUMMON_FEY = "Summon Fey"
    SUMMON_LESSER_DEMONS = "Summon Lesser Demons"
    SUMMON_UNDEAD = "Summon Undead"
    SYLUNES_VIPER = "Sylune's Viper"
    TIDAL_WAVE = "Tidal Wave"
    TINY_SERVANT = "Tiny Servant"
    TONGUES = "Tongues"
    VAMPIRIC_TOUCH = "Vampiric Touch"
    WALL_OF_SAND = "Wall of Sand"
    WALL_OF_WATER = "Wall of Water"
    WATER_BREATHING = "Water Breathing"

class WizardLevel4Spells(str, Enum):
    ARCANE_EYE = "Arcane Eye"
    BACKLASH = "Backlash"
    BANISHMENT = "Banishment"
    BLIGHT = "Blight"
    CHARM_MONSTER = "Charm Monster"
    CONFUSION = "Confusion"
    CONJURE_MINOR_ELEMENTALS = "Conjure Minor Elementals"
    CONTROL_WATER = "Control Water"
    DIMENSION_DOOR = "Dimension Door"
    DIVINATION = "Divination"
    ELEMENTAL_BANE = "Elemental Bane"
    EVARDS_BLACK_TENTACLES = "Evard's Black Tentacles"
    FABRICATE = "Fabricate"
    FIRE_SHIELD = "Fire Shield"
    GALDERS_SPEEDY_COURIER = "Galder's Speedy Courier"
    GATE_SEAL = "Gate Seal"
    GRAVITY_SINKHOLE = "Gravity Sinkhole"
    GREATER_INVISIBILITY = "Greater Invisibility"
    HALLUCINATORY_TERRAIN = "Hallucinatory Terrain"
    ICE_STORM = "Ice Storm"
    LEOMUNDS_SECRET_CHEST = "Leomund's Secret Chest"
    LOCATE_CREATURE = "Locate Creature"
    MORDENKAINENS_FAITHFUL_HOUND = "Mordenkainen's Faithful Hound"
    MORDENKAINENS_PRIVATE_SANCTUM = "Mordenkainen's Private Sanctum"
    OTILUKES_RESILIENT_SPHERE = "Otiluke's Resilient Sphere"
    PHANTASMAL_KILLER = "Phantasmal Killer"
    POLYMORPH = "Polymorph"
    RAULOTHIMS_PSYCHIC_LANCE = "Raulothim's Psychic Lance"
    SICKENING_RADIANCE = "Sickening Radiance"
    SPELLFIRE_STORM = "Spellfire Storm"
    SPIRIT_OF_DEATH = "Spirit of Death"
    STONE_SHAPE = "Stone Shape"
    STONESKIN = "Stoneskin"
    STORM_SPHERE = "Storm Sphere"
    SUMMON_ABERRATION = "Summon Aberration"
    SUMMON_CONSTRUCT = "Summon Construct"
    SUMMON_ELEMENTAL = "Summon Elemental"
    SUMMON_GREATER_DEMON = "Summon Greater Demon"
    VITRIOLIC_SPHERE = "Vitriolic Sphere"
    WALL_OF_FIRE = "Wall of Fire"
    WATERY_SPHERE = "Watery Sphere"

class WizardLevel5Spells(str, Enum):
    ALUSTRIELS_MOONCLOAK = "Alustriel's Mooncloak"
    ANIMATE_OBJECTS = "Animate Objects"
    BIGBYS_HAND = "Bigby's Hand"
    CIRCLE_OF_POWER = "Circle of Power"
    CLOUDKILL = "Cloudkill"
    CONE_OF_COLD = "Cone of Cold"
    CONJURE_ELEMENTAL = "Conjure Elemental"
    CONTACT_OTHER_PLANE = "Contact Other Plane"
    CONTROL_WINDS = "Control Winds"
    CREATE_SPELLJAMMING_HELM = "Create Spelljamming Helm"
    CREATION = "Creation"
    DANSE_MACABRE = "Danse Macabre"
    DAWN = "Dawn"
    DOMINATE_PERSON = "Dominate Person"
    DREAM = "Dream"
    ENERVATION = "Enervation"
    FAR_STEP = "Far Step"
    GEAS = "Geas"
    HOLD_MONSTER = "Hold Monster"
    IMMOLATION = "Immolation"
    INFERNAL_CALLING = "Infernal Calling"
    JALLARZIS_STORM_OF_RADIANCE = "Jallarzi's Storm of Radiance"
    LEGEND_LORE = "Legend Lore"
    MISLEAD = "Mislead"
    MODIFY_MEMORY = "Modify Memory"
    NEGATIVE_ENERGY_FLOOD = "Negative Energy Flood"
    PASSWALL = "Passwall"
    PLANAR_BINDING = "Planar Binding"
    RARYS_TELEPATHIC_BOND = "Rary's Telepathic Bond"
    SCRYING = "Scrying"
    SEEMING = "Seeming"
    SKILL_EMPOWERMENT = "Skill Empowerment"
    SONGALS_ELEMENTAL_SUFFUSION = "Songal's Elemental Suffusion"
    STEEL_WIND_STRIKE = "Steel Wind Strike"
    SUMMON_DRACONIC_SPIRIT = "Summon Draconic Spirit"
    SUMMON_DRAGON = "Summon Dragon"
    SYNAPTIC_STATIC = "Synaptic Static"
    TELEKINESIS = "Telekinesis"
    TELEPORTATION_CIRCLE = "Teleportation Circle"
    TEMPORAL_SHUNT = "Temporal Shunt"
    TRANSMUTE_ROCK = "Transmute Rock"
    WALL_OF_FORCE = "Wall of Force"
    WALL_OF_LIGHT = "Wall of Light"
    WALL_OF_STONE = "Wall of Stone"
    YOLANDES_REGAL_PRESENCE = "Yolande's Regal Presence"

class WizardLevel6Spells(str, Enum):
    ARCANE_GATE = "Arcane Gate"
    CHAIN_LIGHTNING = "Chain Lightning"
    CIRCLE_OF_DEATH = "Circle of Death"
    CONTINGENCY = "Contingency"
    CREATE_HOMUNCULUS = "Create Homunculus"
    CREATE_UNDEAD = "Create Undead"
    DISINTEGRATE = "Disintegrate"
    DRAWMIJS_INSTANT_SUMMONS = "Drawmij's Instant Summons"
    ELMINSTERS_EFFULGENT_SPHERES = "Elminster's Effulgent Spheres"
    EYEBITE = "Eyebite"
    FIZBANS_PLATINUM_SHIELD = "Fizban's Platinum Shield"
    FLESH_TO_STONE = "Flesh to Stone"
    GLOBE_OF_INVULNERABILITY = "Globe of Invulnerability"
    GRAVITY_FISSURE = "Gravity Fissure"
    GUARDS_AND_WARDS = "Guards and Wards"
    INVESTITURE_OF_FLAME = "Investiture of Flame"
    INVESTITURE_OF_ICE = "Investiture of Ice"
    INVESTITURE_OF_STONE = "Investiture of Stone"
    INVESTITURE_OF_WIND = "Investiture of Wind"
    LEOMUNDS_LAMENTABLE_BELABORMENT = "Leomund's Lamentable Belaborment"
    MAGIC_JAR = "Magic Jar"
    MASS_SUGGESTION = "Mass Suggestion"
    MENTAL_PRISON = "Mental Prison"
    MOVE_EARTH = "Move Earth"
    OTILUKES_FREEZING_SPHERE = "Otiluke's Freezing Sphere"
    OTTOS_IRRESISTIBLE_DANCE = "Otto's Irresistible Dance"
    PROGRAMMED_ILLUSION = "Programmed Illusion"
    SCATTER = "Scatter"
    SOUL_CAGE = "Soul Cage"
    SUMMON_FIEND = "Summon Fiend"
    SUNBEAM = "Sunbeam"
    TASHAS_BUBBLING_CAULDRON = "Tasha's Bubbling Cauldron"
    TENSERS_TRANSFORMATION = "Tenser's Transformation"
    TRUE_SEEING = "True Seeing"
    WALL_OF_ICE = "Wall of Ice"

class WizardLevel7Spells(str, Enum):
    CREATE_MAGEN = "Create Magen"
    CROWN_OF_STARS = "Crown of Stars"
    DELAYED_BLAST_FIREBALL = "Delayed Blast Fireball"
    DRACONIC_TRANSFORMATION = "Draconic Transformation"
    ETHEREALNESS = "Etherealness"
    FINGER_OF_DEATH = "Finger of Death"
    FORCECAGE = "Forcecage"
    MIRAGE_ARCANE = "Mirage Arcane"
    MORDENKAINENS_MAGNIFICENT_MANSION = "Mordenkainen's Magnificent Mansion"
    MORDENKAINENS_SWORD = "Mordenkainen's Sword"
    PLANE_SHIFT = "Plane Shift"
    POWER_WORD_PAIN = "Power Word Pain"
    PRISMATIC_SPRAY = "Prismatic Spray"
    PROJECT_IMAGE = "Project Image"
    REVERSE_GRAVITY = "Reverse Gravity"
    SEQUESTER = "Sequester"
    SIMBULS_SYNOSTODWEOMER = "Simbul's Synostodweomer"
    SIMULACRUM = "Simulacrum"
    SYMBOL = "Symbol"
    TELEPORT = "Teleport"
    TETHER_ESSENCE = "Tether Essence"
    VOID_STAR = "Void Star"
    WHIRLWIND = "Whirlwind"

class WizardLevel8Spells(str, Enum):
    ABI_DALZIMS_HORRID_WILTING = "Abi-Dalzim's Horrid Wilting"
    ANTIMAGIC_FIELD = "Antimagic Field"
    ANTIPATHY_SYMPATHY = "Antipathy/Sympathy"
    BEFUDDLEMENT = "Befuddlement"
    CLONE = "Clone"
    CONTROL_WEATHER = "Control Weather"
    DARK_STAR = "Dark Star"
    DEMIPLANE = "Demiplane"
    DOMINATE_MONSTER = "Dominate Monster"
    FEEBLEMIND = "Feeblemind"
    HOLY_STAR_OF_MYSTRA = "Holy Star of Mystra"
    ILLUSORY_DRAGON = "Illusory Dragon"
    INCENDIARY_CLOUD = "Incendiary Cloud"
    MADDENING_DARKNESS = "Maddening Darkness"
    MAZE = "Maze"
    MIGHTY_FORTRESS = "Mighty Fortress"
    MIND_BLANK = "Mind Blank"
    POWER_WORD_STUN = "Power Word Stun"
    REALITY_BREAK = "Reality Break"
    SUNBURST = "Sunburst"
    TELEPATHY = "Telepathy"

class WizardLevel9Spells(str, Enum):
    ASTRAL_PROJECTION = "Astral Projection"
    BLADE_OF_DISASTER = "Blade of Disaster"
    FORESIGHT = "Foresight"
    GATE = "Gate"
    IMPRISONMENT = "Imprisonment"
    INVULNERABILITY = "Invulnerability"
    MASS_POLYMORPH = "Mass Polymorph"
    METEOR_SWARM = "Meteor Swarm"
    POWER_WORD_KILL = "Power Word Kill"
    PRISMATIC_WALL = "Prismatic Wall"
    PSYCHIC_SCREAM = "Psychic Scream"
    RAVENOUS_VOID = "Ravenous Void"
    SHAPECHANGE = "Shapechange"
    TIME_RAVAGE = "Time Ravage"
    TIME_STOP = "Time Stop"
    TRUE_POLYMORPH = "True Polymorph"
    WEIRD = "Weird"
    WISH = "Wish"

class BardLevel0Spells(str, Enum):
    BLADE_WARD = "Blade Ward"
    DANCING_LIGHTS = "Dancing Lights"
    FRIENDS = "Friends"
    LIGHT = "Light"
    MAGE_HAND = "Mage Hand"
    MENDING = "Mending"
    MESSAGE = "Message"
    MINOR_ILLUSION = "Minor Illusion"
    PRESTIDIGITATION = "Prestidigitation"
    STARRY_WISP = "Starry Wisp"
    THUNDERCLAP = "Thunderclap"
    TRUE_STRIKE = "True Strike"
    VICIOUS_MOCKERY = "Vicious Mockery"

class BardLevel1Spells(str, Enum):
    ANIMAL_FRIENDSHIP = "Animal Friendship"
    BANE = "Bane"
    CHARM_PERSON = "Charm Person"
    COLOR_SPRAY = "Color Spray"
    COMMAND = "Command"
    COMPREHEND_LANGUAGES = "Comprehend Languages"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_MAGIC = "Detect Magic"
    DISGUISE_SELF = "Disguise Self"
    DISSONANT_WHISPERS = "Dissonant Whispers"
    DISTORT_VALUE = "Distort Value"
    EARTH_TREMOR = "Earth Tremor"
    FAERIE_FIRE = "Faerie Fire"
    FEATHER_FALL = "Feather Fall"
    HEALING_WORD = "Healing Word"
    HEROISM = "Heroism"
    IDENTIFY = "Identify"
    ILLUSORY_SCRIPT = "Illusory Script"
    INSIDIOUS_RHYTHM = "Insidious Rhythm"
    LONGSTRIDER = "Longstrider"
    SILENT_IMAGE = "Silent Image"
    SILVERY_BARBS = "Silvery Barbs"
    SLEEP = "Sleep"
    SPEAK_WITH_ANIMALS = "Speak with Animals"
    TASHAS_HIDEOUS_LAUGHTER = "Tasha's Hideous Laughter"
    THUNDERWAVE = "Thunderwave"
    UNSEEN_SERVANT = "Unseen Servant"
    WARDAWAY = "Wardaway"

class BardLevel2Spells(str, Enum):
    AID = "Aid"
    ANIMAL_MESSENGER = "Animal Messenger"
    BLINDNESS_DEAFNESS = "Blindness/Deafness"
    BORROWED_KNOWLEDGE = "Borrowed Knowledge"
    CALM_EMOTIONS = "Calm Emotions"
    CLOUD_OF_DAGGERS = "Cloud of Daggers"
    CROWN_OF_MADNESS = "Crown of Madness"
    DETECT_THOUGHTS = "Detect Thoughts"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    ENTHRALL = "Enthrall"
    GIFT_OF_GAB = "Gift of Gab"
    HEAT_METAL = "Heat Metal"
    HOLD_PERSON = "Hold Person"
    INVISIBILITY = "Invisibility"
    KINETIC_JAUNT = "Kinetic Jaunt"
    KNOCK = "Knock"
    LESSER_RESTORATION = "Lesser Restoration"
    LOCATE_ANIMALS_OR_PLANTS = "Locate Animals or Plants"
    LOCATE_OBJECT = "Locate Object"
    MAGIC_MOUTH = "Magic Mouth"
    MIRROR_IMAGE = "Mirror Image"
    NATHAIRS_MISCHIEF = "Nathair's Mischief"
    PHANTASMAL_FORCE = "Phantasmal Force"
    PYROTECHNICS = "Pyrotechnics"
    SEE_INVISIBILITY = "See Invisibility"
    SHATTER = "Shatter"
    SILENCE = "Silence"
    SKYWRITE = "Skywrite"
    SPRAY_OF_CARDS = "Spray of Cards"
    SUGGESTION = "Suggestion"
    WARDING_WIND = "Warding Wind"
    ZONE_OF_TRUTH = "Zone of Truth"

class BardLevel3Spells(str, Enum):
    ANTAGONIZE = "Antagonize"
    ASTRAL_FLOOD = "Astral Flood"
    BESTOW_CURSE = "Bestow Curse"
    CACOPHONIC_SHIELD = "Cacophonic Shield"
    CATNAP = "Catnap"
    CLAIRVOYANCE = "Clairvoyance"
    DISPEL_MAGIC = "Dispel Magic"
    ENEMIES_ABOUND = "Enemies Abound"
    FEAR = "Fear"
    FEIGN_DEATH = "Feign Death"
    GLYPH_OF_WARDING = "Glyph of Warding"
    HYPNOTIC_PATTERN = "Hypnotic Pattern"
    LEOMUNDS_TINY_HUT = "Leomund's Tiny Hut"
    MAJOR_IMAGE = "Major Image"
    MASS_HEALING_WORD = "Mass Healing Word"
    NONDETECTION = "Nondetection"
    PLANT_GROWTH = "Plant Growth"
    SENDING = "Sending"
    SLOW = "Slow"
    SPEAK_WITH_DEAD = "Speak with Dead"
    SPEAK_WITH_PLANTS = "Speak with Plants"
    STINKING_CLOUD = "Stinking Cloud"
    TONGUES = "Tongues"

class BardLevel4Spells(str, Enum):
    BACKLASH = "Backlash"
    CHARM_MONSTER = "Charm Monster"
    COMPULSION = "Compulsion"
    CONFUSION = "Confusion"
    DIMENSION_DOOR = "Dimension Door"
    DOOMTIDE = "Doomtide"
    FOUNT_OF_MOONLIGHT = "Fount of Moonlight"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    GREATER_INVISIBILITY = "Greater Invisibility"
    HALLUCINATORY_TERRAIN = "Hallucinatory Terrain"
    LOCATE_CREATURE = "Locate Creature"
    PHANTASMAL_KILLER = "Phantasmal Killer"
    POLYMORPH = "Polymorph"
    RAULOTHIMS_PSYCHIC_LANCE = "Raulothim's Psychic Lance"

class BardLevel5Spells(str, Enum):
    ALUSTRIELS_MOONCLOAK = "Alustriel's Mooncloak"
    ANIMATE_OBJECTS = "Animate Objects"
    AWAKEN = "Awaken"
    DOMINATE_PERSON = "Dominate Person"
    DREAM = "Dream"
    GEAS = "Geas"
    GREATER_RESTORATION = "Greater Restoration"
    HOLD_MONSTER = "Hold Monster"
    LEGEND_LORE = "Legend Lore"
    MASS_CURE_WOUNDS = "Mass Cure Wounds"
    MISLEAD = "Mislead"
    MODIFY_MEMORY = "Modify Memory"
    PLANAR_BINDING = "Planar Binding"
    RAISE_DEAD = "Raise Dead"
    RARYS_TELEPATHIC_BOND = "Rary's Telepathic Bond"
    SCRYING = "Scrying"
    SEEMING = "Seeming"
    SKILL_EMPOWERMENT = "Skill Empowerment"
    SYNAPTIC_STATIC = "Synaptic Static"
    TELEPORTATION_CIRCLE = "Teleportation Circle"
    YOLANDES_REGAL_PRESENCE = "Yolande's Regal Presence"

class BardLevel6Spells(str, Enum):
    DIRGE = "Dirge"
    EYEBITE = "Eyebite"
    FIND_THE_PATH = "Find the Path"
    GUARDS_AND_WARDS = "Guards and Wards"
    HEROES_FEAST = "Heroes' Feast"
    LEOMUNDS_LAMENTABLE_BELABORMENT = "Leomund's Lamentable Belaborment"
    MASS_SUGGESTION = "Mass Suggestion"
    OTTOS_IRRESISTIBLE_DANCE = "Otto's Irresistible Dance"
    PROGRAMMED_ILLUSION = "Programmed Illusion"
    TRUE_SEEING = "True Seeing"

class BardLevel7Spells(str, Enum):
    ETHEREALNESS = "Etherealness"
    FORCECAGE = "Forcecage"
    MIRAGE_ARCANE = "Mirage Arcane"
    MORDENKAINENS_MAGNIFICENT_MANSION = "Mordenkainen's Magnificent Mansion"
    MORDENKAINENS_SWORD = "Mordenkainen's Sword"
    POWER_WORD_FORTIFY = "Power Word Fortify"
    PRISMATIC_SPRAY = "Prismatic Spray"
    PROJECT_IMAGE = "Project Image"
    REGENERATE = "Regenerate"
    RESURRECTION = "Resurrection"
    SYMBOL = "Symbol"
    TELEPORT = "Teleport"

class BardLevel8Spells(str, Enum):
    ANTIPATHY_SYMPATHY = "Antipathy/Sympathy"
    BEFUDDLEMENT = "Befuddlement"
    DOMINATE_MONSTER = "Dominate Monster"
    FEEBLEMIND = "Feeblemind"
    GLIBNESS = "Glibness"
    MIND_BLANK = "Mind Blank"
    POWER_WORD_STUN = "Power Word Stun"

class BardLevel9Spells(str, Enum):
    FORESIGHT = "Foresight"
    MASS_POLYMORPH = "Mass Polymorph"
    POWER_WORD_HEAL = "Power Word Heal"
    POWER_WORD_KILL = "Power Word Kill"
    PRISMATIC_WALL = "Prismatic Wall"
    PSYCHIC_SCREAM = "Psychic Scream"
    TRUE_POLYMORPH = "True Polymorph"

class ClericLevel0Spells(str, Enum):
    GUIDANCE = "Guidance"
    LIGHT = "Light"
    MENDING = "Mending"
    RESISTANCE = "Resistance"
    SACRED_FLAME = "Sacred Flame"
    SPARE_THE_DYING = "Spare the Dying"
    THAUMATURGY = "Thaumaturgy"
    TOLL_THE_DEAD = "Toll the Dead"
    WORD_OF_RADIANCE = "Word of Radiance"

class ClericLevel1Spells(str, Enum):
    BANE = "Bane"
    BLESS = "Bless"
    CEREMONY = "Ceremony"
    COMMAND = "Command"
    CREATE_OR_DESTROY_WATER = "Create or Destroy Water"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_EVIL_AND_GOOD = "Detect Evil and Good"
    DETECT_MAGIC = "Detect Magic"
    DETECT_POISON_AND_DISEASE = "Detect Poison and Disease"
    GUIDING_BOLT = "Guiding Bolt"
    HEALING_WORD = "Healing Word"
    INFLICT_WOUNDS = "Inflict Wounds"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    PURIFY_FOOD_AND_DRINK = "Purify Food and Drink"
    SANCTUARY = "Sanctuary"
    SHIELD_OF_FAITH = "Shield of Faith"
    WARDAWAY = "Wardaway"

class ClericLevel2Spells(str, Enum):
    AID = "Aid"
    AUGURY = "Augury"
    BLINDNESS_DEAFNESS = "Blindness/Deafness"
    BORROWED_KNOWLEDGE = "Borrowed Knowledge"
    CALM_EMOTIONS = "Calm Emotions"
    CONTINUAL_FLAME = "Continual Flame"
    DERYANS_HELPFUL_HOMUNCULI = "Deryan's Helpful Homunculi"
    ENHANCE_ABILITY = "Enhance Ability"
    FIND_TRAPS = "Find Traps"
    GENTLE_REPOSE = "Gentle Repose"
    HOLD_PERSON = "Hold Person"
    LESSER_RESTORATION = "Lesser Restoration"
    LOCATE_OBJECT = "Locate Object"
    PRAYER_OF_HEALING = "Prayer of Healing"
    PROTECTION_FROM_POISON = "Protection from Poison"
    SEARING_ORB = "Searing Orb"
    SILENCE = "Silence"
    SPIRITUAL_WEAPON = "Spiritual Weapon"
    WARDING_BOND = "Warding Bond"
    ZONE_OF_TRUTH = "Zone of Truth"

class ClericLevel3Spells(str, Enum):
    ANIMATE_DEAD = "Animate Dead"
    ASTRAL_FLOOD = "Astral Flood"
    AURA_OF_VITALITY = "Aura of Vitality"
    BEACON_OF_HOPE = "Beacon of Hope"
    BESTOW_CURSE = "Bestow Curse"
    CLAIRVOYANCE = "Clairvoyance"
    CREATE_FOOD_AND_WATER = "Create Food and Water"
    DAYLIGHT = "Daylight"
    DISPEL_MAGIC = "Dispel Magic"
    FEIGN_DEATH = "Feign Death"
    GLYPH_OF_WARDING = "Glyph of Warding"
    INCITE_GREED = "Incite Greed"
    LAERALS_SILVER_LANCE = "Laeral's Silver Lance"
    MAGIC_CIRCLE = "Magic Circle"
    MASS_HEALING_WORD = "Mass Healing Word"
    MELD_INTO_STONE = "Meld into Stone"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    REMOVE_CURSE = "Remove Curse"
    REVIVIFY = "Revivify"
    SENDING = "Sending"
    SPEAK_WITH_DEAD = "Speak with Dead"
    SPIRIT_GUARDIANS = "Spirit Guardians"
    TONGUES = "Tongues"
    WATER_WALK = "Water Walk"

class ClericLevel4Spells(str, Enum):
    AURA_OF_LIFE = "Aura of Life"
    AURA_OF_PURITY = "Aura of Purity"
    BANISHMENT = "Banishment"
    CONTROL_WATER = "Control Water"
    DEATH_WARD = "Death Ward"
    DIVINATION = "Divination"
    DOOMTIDE = "Doomtide"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    GUARDIAN_OF_FAITH = "Guardian of Faith"
    LOCATE_CREATURE = "Locate Creature"
    STICKS_TO_SNAKES = "Sticks to Snakes"
    STONE_SHAPE = "Stone Shape"

class ClericLevel5Spells(str, Enum):
    CIRCLE_OF_POWER = "Circle of Power"
    COMMUNE = "Commune"
    CONTAGION = "Contagion"
    DAWN = "Dawn"
    DISPEL_EVIL_AND_GOOD = "Dispel Evil and Good"
    FLAME_STRIKE = "Flame Strike"
    GEAS = "Geas"
    GREATER_RESTORATION = "Greater Restoration"
    HALLOW = "Hallow"
    HOLY_WEAPON = "Holy Weapon"
    INSECT_PLAGUE = "Insect Plague"
    LEGEND_LORE = "Legend Lore"
    MASS_CURE_WOUNDS = "Mass Cure Wounds"
    PLANAR_BINDING = "Planar Binding"
    RAISE_DEAD = "Raise Dead"
    SCRYING = "Scrying"
    SUMMON_CELESTIAL = "Summon Celestial"

class ClericLevel6Spells(str, Enum):
    BLADE_BARRIER = "Blade Barrier"
    CREATE_UNDEAD = "Create Undead"
    DIRGE = "Dirge"
    FIND_THE_PATH = "Find the Path"
    FORBIDDANCE = "Forbiddance"
    HARM = "Harm"
    HEAL = "Heal"
    HEROES_FEAST = "Heroes' Feast"
    PLANAR_ALLY = "Planar Ally"
    SUNBEAM = "Sunbeam"
    TRUE_SEEING = "True Seeing"
    WORD_OF_RECALL = "Word of Recall"

class ClericLevel7Spells(str, Enum):
    CONJURE_CELESTIAL = "Conjure Celestial"
    DIVINE_WORD = "Divine Word"
    ETHEREALNESS = "Etherealness"
    FIRE_STORM = "Fire Storm"
    PLANE_SHIFT = "Plane Shift"
    POWER_WORD_FORTIFY = "Power Word Fortify"
    REGENERATE = "Regenerate"
    RESURRECTION = "Resurrection"
    SYMBOL = "Symbol"
    TEMPLE_OF_THE_GODS = "Temple of the Gods"

class ClericLevel8Spells(str, Enum):
    ANTIMAGIC_FIELD = "Antimagic Field"
    CONTROL_WEATHER = "Control Weather"
    EARTHQUAKE = "Earthquake"
    HOLY_AURA = "Holy Aura"
    HOLY_STAR_OF_MYSTRA = "Holy Star of Mystra"
    SUNBURST = "Sunburst"

class ClericLevel9Spells(str, Enum):
    ASTRAL_PROJECTION = "Astral Projection"
    GATE = "Gate"
    MASS_HEAL = "Mass Heal"
    POWER_WORD_HEAL = "Power Word Heal"
    TRUE_RESURRECTION = "True Resurrection"

class DruidLevel0Spells(str, Enum):
    CONTROL_FLAMES = "Control Flames"
    CREATE_BONFIRE = "Create Bonfire"
    DRUIDCRAFT = "Druidcraft"
    ELEMENTALISM = "Elementalism"
    FROSTBITE = "Frostbite"
    GUIDANCE = "Guidance"
    GUST = "Gust"
    INFESTATION = "Infestation"
    MAGIC_STONE = "Magic Stone"
    MENDING = "Mending"
    MESSAGE = "Message"
    MOLD_EARTH = "Mold Earth"
    POISON_SPRAY = "Poison Spray"
    PRIMAL_SAVAGERY = "Primal Savagery"
    PRODUCE_FLAME = "Produce Flame"
    RESISTANCE = "Resistance"
    SHAPE_WATER = "Shape Water"
    SHILLELAGH = "Shillelagh"
    SPARE_THE_DYING = "Spare the Dying"
    STARRY_WISP = "Starry Wisp"
    THORN_WHIP = "Thorn Whip"
    THUNDERCLAP = "Thunderclap"

class DruidLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    ANIMAL_FRIENDSHIP = "Animal Friendship"
    BEAST_BOND = "Beast Bond"
    BUZZING_BEE = "Buzzing Bee"
    CHARM_PERSON = "Charm Person"
    CREATE_OR_DESTROY_WATER = "Create or Destroy Water"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_MAGIC = "Detect Magic"
    DETECT_POISON_AND_DISEASE = "Detect Poison and Disease"
    EARTH_TREMOR = "Earth Tremor"
    ENTANGLE = "Entangle"
    FAERIE_FIRE = "Faerie Fire"
    FOG_CLOUD = "Fog Cloud"
    GOODBERRY = "Goodberry"
    HEALING_WORD = "Healing Word"
    ICE_KNIFE = "Ice Knife"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    PURIFY_FOOD_AND_DRINK = "Purify Food and Drink"
    SNARE = "Snare"
    SPEAK_WITH_ANIMALS = "Speak with Animals"
    THUNDERWAVE = "Thunderwave"

class DruidLevel2Spells(str, Enum):
    AID = "Aid"
    AIR_BUBBLE = "Air Bubble"
    ANIMAL_MESSENGER = "Animal Messenger"
    AUGURY = "Augury"
    BARKSKIN = "Barkskin"
    BEAST_SENSE = "Beast Sense"
    CONTINUAL_FLAME = "Continual Flame"
    DARKVISION = "Darkvision"
    DUST_DEVIL = "Dust Devil"
    EARTHBIND = "Earthbind"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    FIND_TRAPS = "Find Traps"
    FLAME_BLADE = "Flame Blade"
    FLAMING_SPHERE = "Flaming Sphere"
    GUST_OF_WIND = "Gust of Wind"
    HEALING_SPIRIT = "Healing Spirit"
    HEAT_METAL = "Heat Metal"
    HOLD_PERSON = "Hold Person"
    LESSER_RESTORATION = "Lesser Restoration"
    LOCATE_ANIMALS_OR_PLANTS = "Locate Animals or Plants"
    LOCATE_OBJECT = "Locate Object"
    MOONBEAM = "Moonbeam"
    PASS_WITHOUT_TRACE = "Pass without Trace"
    PROTECTION_FROM_POISON = "Protection from Poison"
    SKYWRITE = "Skywrite"
    SPIKE_GROWTH = "Spike Growth"
    SUMMON_BEAST = "Summon Beast"
    TORTOISE_SHELL = "Tortoise Shell"
    WARDING_WIND = "Warding Wind"
    WITHER_AND_BLOOM = "Wither and Bloom"

class DruidLevel3Spells(str, Enum):
    AURA_OF_VITALITY = "Aura of Vitality"
    CALL_LIGHTNING = "Call Lightning"
    CONJURE_ANIMALS = "Conjure Animals"
    DAYLIGHT = "Daylight"
    DISPEL_MAGIC = "Dispel Magic"
    ELEMENTAL_WEAPON = "Elemental Weapon"
    ERUPTING_EARTH = "Erupting Earth"
    FEIGN_DEATH = "Feign Death"
    FLAME_ARROWS = "Flame Arrows"
    MELD_INTO_STONE = "Meld into Stone"
    PLANT_GROWTH = "Plant Growth"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    REVIVIFY = "Revivify"
    SLEET_STORM = "Sleet Storm"
    SPEAK_WITH_PLANTS = "Speak with Plants"
    SUMMON_FEY = "Summon Fey"
    SYLUNES_VIPER = "Sylune's Viper"
    TIDAL_WAVE = "Tidal Wave"
    WALL_OF_WATER = "Wall of Water"
    WATER_BREATHING = "Water Breathing"
    WATER_WALK = "Water Walk"
    WIND_WALL = "Wind Wall"

class DruidLevel4Spells(str, Enum):
    BLIGHT = "Blight"
    CHARM_MONSTER = "Charm Monster"
    CONFUSION = "Confusion"
    CONJURE_MINOR_ELEMENTALS = "Conjure Minor Elementals"
    CONJURE_WOODLAND_BEINGS = "Conjure Woodland Beings"
    CONTROL_WATER = "Control Water"
    DIVINATION = "Divination"
    DOMINATE_BEAST = "Dominate Beast"
    ELEMENTAL_BANE = "Elemental Bane"
    FIRE_SHIELD = "Fire Shield"
    FOUNT_OF_MOONLIGHT = "Fount of Moonlight"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    GIANT_INSECT = "Giant Insect"
    GRASPING_VINE = "Grasping Vine"
    GUARDIAN_OF_NATURE = "Guardian of Nature"
    HALLUCINATORY_TERRAIN = "Hallucinatory Terrain"
    ICE_STORM = "Ice Storm"
    LOCATE_CREATURE = "Locate Creature"
    POLYMORPH = "Polymorph"
    STICKS_TO_SNAKES = "Sticks to Snakes"
    STONE_SHAPE = "Stone Shape"
    STONESKIN = "Stoneskin"
    SUMMON_ELEMENTAL = "Summon Elemental"
    WALL_OF_FIRE = "Wall of Fire"
    WATERY_SPHERE = "Watery Sphere"

class DruidLevel5Spells(str, Enum):
    ALUSTRIELS_MOONCLOAK = "Alustriel's Mooncloak"
    ANTILIFE_SHELL = "Antilife Shell"
    AWAKEN = "Awaken"
    COMMUNE_WITH_NATURE = "Commune with Nature"
    CONE_OF_COLD = "Cone of Cold"
    CONJURE_ELEMENTAL = "Conjure Elemental"
    CONTAGION = "Contagion"
    CONTROL_WINDS = "Control Winds"
    GEAS = "Geas"
    GREATER_RESTORATION = "Greater Restoration"
    INSECT_PLAGUE = "Insect Plague"
    MAELSTROM = "Maelstrom"
    MASS_CURE_WOUNDS = "Mass Cure Wounds"
    PLANAR_BINDING = "Planar Binding"
    REINCARNATE = "Reincarnate"
    SCRYING = "Scrying"
    SONGALS_ELEMENTAL_SUFFUSION = "Songal's Elemental Suffusion"
    SUMMON_DRACONIC_SPIRIT = "Summon Draconic Spirit"
    TRANSMUTE_ROCK = "Transmute Rock"
    TREE_STRIDE = "Tree Stride"
    WALL_OF_STONE = "Wall of Stone"
    WRATH_OF_NATURE = "Wrath of Nature"

class DruidLevel6Spells(str, Enum):
    BONES_OF_THE_EARTH = "Bones of the Earth"
    CONJURE_FEY = "Conjure Fey"
    DRUID_GROVE = "Druid Grove"
    ELMINSTERS_EFFULGENT_SPHERES = "Elminster's Effulgent Spheres"
    FIND_THE_PATH = "Find the Path"
    FLESH_TO_STONE = "Flesh to Stone"
    HEAL = "Heal"
    HEROES_FEAST = "Heroes' Feast"
    INVESTITURE_OF_FLAME = "Investiture of Flame"
    INVESTITURE_OF_ICE = "Investiture of Ice"
    INVESTITURE_OF_STONE = "Investiture of Stone"
    INVESTITURE_OF_WIND = "Investiture of Wind"
    MOVE_EARTH = "Move Earth"
    PRIMORDIAL_WARD = "Primordial Ward"
    SUNBEAM = "Sunbeam"
    TRANSPORT_VIA_PLANTS = "Transport via Plants"
    WALL_OF_THORNS = "Wall of Thorns"
    WIND_WALK = "Wind Walk"

class DruidLevel7Spells(str, Enum):
    DRACONIC_TRANSFORMATION = "Draconic Transformation"
    FIRE_STORM = "Fire Storm"
    MIRAGE_ARCANE = "Mirage Arcane"
    PLANE_SHIFT = "Plane Shift"
    REGENERATE = "Regenerate"
    REVERSE_GRAVITY = "Reverse Gravity"
    SYMBOL = "Symbol"
    WHIRLWIND = "Whirlwind"

class DruidLevel8Spells(str, Enum):
    ANIMAL_SHAPES = "Animal Shapes"
    ANTIPATHY_SYMPATHY = "Antipathy/Sympathy"
    BEFUDDLEMENT = "Befuddlement"
    CONTROL_WEATHER = "Control Weather"
    EARTHQUAKE = "Earthquake"
    FEEBLEMIND = "Feeblemind"
    INCENDIARY_CLOUD = "Incendiary Cloud"
    SUNBURST = "Sunburst"
    TSUNAMI = "Tsunami"

class DruidLevel9Spells(str, Enum):
    FORESIGHT = "Foresight"
    SHAPECHANGE = "Shapechange"
    STORM_OF_VENGEANCE = "Storm of Vengeance"
    TRUE_RESURRECTION = "True Resurrection"

class PaladinLevel1Spells(str, Enum):
    BLESS = "Bless"
    CEREMONY = "Ceremony"
    COMMAND = "Command"
    COMPELLED_DUEL = "Compelled Duel"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_EVIL_AND_GOOD = "Detect Evil and Good"
    DETECT_MAGIC = "Detect Magic"
    DETECT_POISON_AND_DISEASE = "Detect Poison and Disease"
    DIVINE_FAVOR = "Divine Favor"
    DIVINE_SMITE = "Divine Smite"
    HEROISM = "Heroism"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    PURIFY_FOOD_AND_DRINK = "Purify Food and Drink"
    SEARING_SMITE = "Searing Smite"
    SHIELD_OF_FAITH = "Shield of Faith"
    THUNDEROUS_SMITE = "Thunderous Smite"
    WARDAWAY = "Wardaway"
    WRATHFUL_SMITE = "Wrathful Smite"

class PaladinLevel2Spells(str, Enum):
    AID = "Aid"
    BRANDING_SMITE = "Branding Smite"
    FIND_STEED = "Find Steed"
    GENTLE_REPOSE = "Gentle Repose"
    LESSER_RESTORATION = "Lesser Restoration"
    LOCATE_OBJECT = "Locate Object"
    MAGIC_WEAPON = "Magic Weapon"
    PRAYER_OF_HEALING = "Prayer of Healing"
    PROTECTION_FROM_POISON = "Protection from Poison"
    SEARING_ORB = "Searing Orb"
    SHINING_SMITE = "Shining Smite"
    WARDING_BOND = "Warding Bond"
    ZONE_OF_TRUTH = "Zone of Truth"

class PaladinLevel3Spells(str, Enum):
    AURA_OF_VITALITY = "Aura of Vitality"
    BLINDING_SMITE = "Blinding Smite"
    CREATE_FOOD_AND_WATER = "Create Food and Water"
    CRUSADERS_MANTLE = "Crusader's Mantle"
    DAYLIGHT = "Daylight"
    DISPEL_MAGIC = "Dispel Magic"
    ELEMENTAL_WEAPON = "Elemental Weapon"
    MAGIC_CIRCLE = "Magic Circle"
    REMOVE_CURSE = "Remove Curse"
    REVIVIFY = "Revivify"

class PaladinLevel4Spells(str, Enum):
    AURA_OF_LIFE = "Aura of Life"
    AURA_OF_PURITY = "Aura of Purity"
    BANISHMENT = "Banishment"
    DEATH_WARD = "Death Ward"
    FIND_GREATER_STEED = "Find Greater Steed"
    LOCATE_CREATURE = "Locate Creature"
    STAGGERING_SMITE = "Staggering Smite"

class PaladinLevel5Spells(str, Enum):
    BANISHING_SMITE = "Banishing Smite"
    CIRCLE_OF_POWER = "Circle of Power"
    DESTRUCTIVE_WAVE = "Destructive Wave"
    DISPEL_EVIL_AND_GOOD = "Dispel Evil and Good"
    GEAS = "Geas"
    GREATER_RESTORATION = "Greater Restoration"
    HOLY_WEAPON = "Holy Weapon"
    RAISE_DEAD = "Raise Dead"
    SUMMON_CELESTIAL = "Summon Celestial"

class RangerLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    ALARM = "Alarm"
    ANIMAL_FRIENDSHIP = "Animal Friendship"
    BEAST_BOND = "Beast Bond"
    BUZZING_BEE = "Buzzing Bee"
    CURE_WOUNDS = "Cure Wounds"
    DETECT_MAGIC = "Detect Magic"
    DETECT_POISON_AND_DISEASE = "Detect Poison and Disease"
    ENSNARING_STRIKE = "Ensnaring Strike"
    ENTANGLE = "Entangle"
    FOG_CLOUD = "Fog Cloud"
    GOODBERRY = "Goodberry"
    HAIL_OF_THORNS = "Hail of Thorns"
    HUNTERS_MARK = "Hunter's Mark"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    SNARE = "Snare"
    SPEAK_WITH_ANIMALS = "Speak with Animals"
    ZEPHYR_STRIKE = "Zephyr Strike"

class RangerLevel2Spells(str, Enum):
    AID = "Aid"
    AIR_BUBBLE = "Air Bubble"
    ANIMAL_MESSENGER = "Animal Messenger"
    BARKSKIN = "Barkskin"
    BEAST_SENSE = "Beast Sense"
    CORDON_OF_ARROWS = "Cordon of Arrows"
    DARKVISION = "Darkvision"
    ENHANCE_ABILITY = "Enhance Ability"
    FIND_TRAPS = "Find Traps"
    GUST_OF_WIND = "Gust of Wind"
    HEALING_SPIRIT = "Healing Spirit"
    LESSER_RESTORATION = "Lesser Restoration"
    LOCATE_ANIMALS_OR_PLANTS = "Locate Animals or Plants"
    LOCATE_OBJECT = "Locate Object"
    MAGIC_WEAPON = "Magic Weapon"
    PASS_WITHOUT_TRACE = "Pass without Trace"
    PROTECTION_FROM_POISON = "Protection from Poison"
    SILENCE = "Silence"
    SPIKE_GROWTH = "Spike Growth"
    SUMMON_BEAST = "Summon Beast"
    TORTOISE_SHELL = "Tortoise Shell"

class RangerLevel3Spells(str, Enum):
    ASHARDALONS_STRIDE = "Ashardalon's Stride"
    CONJURE_ANIMALS = "Conjure Animals"
    CONJURE_BARRAGE = "Conjure Barrage"
    DAYLIGHT = "Daylight"
    DISPEL_MAGIC = "Dispel Magic"
    ELEMENTAL_WEAPON = "Elemental Weapon"
    FLAME_ARROWS = "Flame Arrows"
    LIGHTNING_ARROW = "Lightning Arrow"
    MELD_INTO_STONE = "Meld into Stone"
    NONDETECTION = "Nondetection"
    PLANT_GROWTH = "Plant Growth"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    REVIVIFY = "Revivify"
    SPEAK_WITH_PLANTS = "Speak with Plants"
    SUMMON_FEY = "Summon Fey"
    WATER_BREATHING = "Water Breathing"
    WATER_WALK = "Water Walk"
    WIND_WALL = "Wind Wall"

class RangerLevel4Spells(str, Enum):
    CONJURE_WOODLAND_BEINGS = "Conjure Woodland Beings"
    DOMINATE_BEAST = "Dominate Beast"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    GRASPING_VINE = "Grasping Vine"
    GUARDIAN_OF_NATURE = "Guardian of Nature"
    LOCATE_CREATURE = "Locate Creature"
    STICKS_TO_SNAKES = "Sticks to Snakes"
    STONESKIN = "Stoneskin"
    SUMMON_ELEMENTAL = "Summon Elemental"

class RangerLevel5Spells(str, Enum):
    ALUSTRIELS_MOONCLOAK = "Alustriel's Mooncloak"
    COMMUNE_WITH_NATURE = "Commune with Nature"
    CONJURE_VOLLEY = "Conjure Volley"
    GREATER_RESTORATION = "Greater Restoration"
    STEEL_WIND_STRIKE = "Steel Wind Strike"
    SWIFT_QUIVER = "Swift Quiver"
    TREE_STRIDE = "Tree Stride"
    WRATH_OF_NATURE = "Wrath of Nature"

class WarlockLevel0Spells(str, Enum):
    BLADE_WARD = "Blade Ward"
    CHILL_TOUCH = "Chill Touch"
    CREATE_BONFIRE = "Create Bonfire"
    ELDRITCH_BLAST = "Eldritch Blast"
    FRIENDS = "Friends"
    FROSTBITE = "Frostbite"
    INFESTATION = "Infestation"
    MAGE_HAND = "Mage Hand"
    MAGIC_STONE = "Magic Stone"
    MIND_SLIVER = "Mind Sliver"
    MINOR_ILLUSION = "Minor Illusion"
    POISON_SPRAY = "Poison Spray"
    PRESTIDIGITATION = "Prestidigitation"
    THUNDERCLAP = "Thunderclap"
    TOLL_THE_DEAD = "Toll the Dead"
    TRUE_STRIKE = "True Strike"

class WarlockLevel1Spells(str, Enum):
    ARMOR_OF_AGATHYS = "Armor of Agathys"
    ARMS_OF_HADAR = "Arms of Hadar"
    BANE = "Bane"
    CAUSE_FEAR = "Cause Fear"
    CHARM_PERSON = "Charm Person"
    COMPREHEND_LANGUAGES = "Comprehend Languages"
    DETECT_MAGIC = "Detect Magic"
    DISTORT_VALUE = "Distort Value"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    HELLISH_REBUKE = "Hellish Rebuke"
    HEX = "Hex"
    ILLUSORY_SCRIPT = "Illusory Script"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    SPEAK_WITH_ANIMALS = "Speak with Animals"
    TASHAS_HIDEOUS_LAUGHTER = "Tasha's Hideous Laughter"
    UNSEEN_SERVANT = "Unseen Servant"
    WITCH_BOLT = "Witch Bolt"

class WarlockLevel2Spells(str, Enum):
    BORROWED_KNOWLEDGE = "Borrowed Knowledge"
    CLOUD_OF_DAGGERS = "Cloud of Daggers"
    CROWN_OF_MADNESS = "Crown of Madness"
    DARKNESS = "Darkness"
    EARTHBIND = "Earthbind"
    ENTHRALL = "Enthrall"
    FLOCK_OF_FAMILIARS = "Flock of Familiars"
    HOLD_PERSON = "Hold Person"
    INVISIBILITY = "Invisibility"
    MIND_SPIKE = "Mind Spike"
    MIRROR_IMAGE = "Mirror Image"
    MISTY_STEP = "Misty Step"
    RAY_OF_ENFEEBLEMENT = "Ray of Enfeeblement"
    SHADOW_BLADE = "Shadow Blade"
    SPIDER_CLIMB = "Spider Climb"
    SPRAY_OF_CARDS = "Spray of Cards"
    SUGGESTION = "Suggestion"
    WARP_SENSE = "Warp Sense"

class WarlockLevel3Spells(str, Enum):
    ANTAGONIZE = "Antagonize"
    COUNTERSPELL = "Counterspell"
    DISPEL_MAGIC = "Dispel Magic"
    ENEMIES_ABOUND = "Enemies Abound"
    FEAR = "Fear"
    FLY = "Fly"
    GASEOUS_FORM = "Gaseous Form"
    HUNGER_OF_HADAR = "Hunger of Hadar"
    HYPNOTIC_PATTERN = "Hypnotic Pattern"
    INCITE_GREED = "Incite Greed"
    MAGIC_CIRCLE = "Magic Circle"
    MAJOR_IMAGE = "Major Image"
    REMOVE_CURSE = "Remove Curse"
    SUMMON_FEY = "Summon Fey"
    SUMMON_LESSER_DEMONS = "Summon Lesser Demons"
    SUMMON_UNDEAD = "Summon Undead"
    TONGUES = "Tongues"
    VAMPIRIC_TOUCH = "Vampiric Touch"

class WarlockLevel4Spells(str, Enum):
    BACKLASH = "Backlash"
    BANISHMENT = "Banishment"
    BLIGHT = "Blight"
    CHARM_MONSTER = "Charm Monster"
    DIMENSION_DOOR = "Dimension Door"
    DOOMTIDE = "Doomtide"
    ELEMENTAL_BANE = "Elemental Bane"
    GALDERS_SPEEDY_COURIER = "Galder's Speedy Courier"
    GATE_SEAL = "Gate Seal"
    HALLUCINATORY_TERRAIN = "Hallucinatory Terrain"
    RAULOTHIMS_PSYCHIC_LANCE = "Raulothim's Psychic Lance"
    SHADOW_OF_MOIL = "Shadow of Moil"
    SICKENING_RADIANCE = "Sickening Radiance"
    SPIRIT_OF_DEATH = "Spirit of Death"
    SUMMON_ABERRATION = "Summon Aberration"

class WarlockLevel5Spells(str, Enum):
    CONTACT_OTHER_PLANE = "Contact Other Plane"
    DANSE_MACABRE = "Danse Macabre"
    DREAM = "Dream"
    ENERVATION = "Enervation"
    FAR_STEP = "Far Step"
    HOLD_MONSTER = "Hold Monster"
    INFERNAL_CALLING = "Infernal Calling"
    JALLARZIS_STORM_OF_RADIANCE = "Jallarzi's Storm of Radiance"
    MISLEAD = "Mislead"
    NEGATIVE_ENERGY_FLOOD = "Negative Energy Flood"
    PLANAR_BINDING = "Planar Binding"
    SCRYING = "Scrying"
    SYNAPTIC_STATIC = "Synaptic Static"
    TELEPORTATION_CIRCLE = "Teleportation Circle"
    WALL_OF_LIGHT = "Wall of Light"

class WarlockLevel6Spells(str, Enum):
    ARCANE_GATE = "Arcane Gate"
    CIRCLE_OF_DEATH = "Circle of Death"
    CREATE_UNDEAD = "Create Undead"
    EYEBITE = "Eyebite"
    INVESTITURE_OF_FLAME = "Investiture of Flame"
    INVESTITURE_OF_ICE = "Investiture of Ice"
    INVESTITURE_OF_STONE = "Investiture of Stone"
    INVESTITURE_OF_WIND = "Investiture of Wind"
    MENTAL_PRISON = "Mental Prison"
    SCATTER = "Scatter"
    SOUL_CAGE = "Soul Cage"
    SUMMON_FIEND = "Summon Fiend"
    TASHAS_BUBBLING_CAULDRON = "Tasha's Bubbling Cauldron"
    TRUE_SEEING = "True Seeing"

class WarlockLevel7Spells(str, Enum):
    CROWN_OF_STARS = "Crown of Stars"
    ETHEREALNESS = "Etherealness"
    FINGER_OF_DEATH = "Finger of Death"
    FORCECAGE = "Forcecage"
    PLANE_SHIFT = "Plane Shift"
    POWER_WORD_PAIN = "Power Word Pain"
    VOID_STAR = "Void Star"

class WarlockLevel8Spells(str, Enum):
    BEFUDDLEMENT = "Befuddlement"
    DEMIPLANE = "Demiplane"
    DOMINATE_MONSTER = "Dominate Monster"
    FEEBLEMIND = "Feeblemind"
    GLIBNESS = "Glibness"
    MADDENING_DARKNESS = "Maddening Darkness"
    POWER_WORD_STUN = "Power Word Stun"

class WarlockLevel9Spells(str, Enum):
    ASTRAL_PROJECTION = "Astral Projection"
    BLADE_OF_DISASTER = "Blade of Disaster"
    FORESIGHT = "Foresight"
    GATE = "Gate"
    IMPRISONMENT = "Imprisonment"
    POWER_WORD_KILL = "Power Word Kill"
    PSYCHIC_SCREAM = "Psychic Scream"
    TRUE_POLYMORPH = "True Polymorph"
    WEIRD = "Weird"

class AbjurationLevel0Spells(str, Enum):
    BLADE_WARD = "Blade Ward"
    RESISTANCE = "Resistance"

class AbjurationLevel1Spells(str, Enum):
    ABSORB_ELEMENTS = "Absorb Elements"
    ALARM = "Alarm"
    ARMOR_OF_AGATHYS = "Armor of Agathys"
    CEREMONY = "Ceremony"
    CURE_WOUNDS = "Cure Wounds"
    HEALING_WORD = "Healing Word"
    MAGE_ARMOR = "Mage Armor"
    PROTECTION_FROM_EVIL_AND_GOOD = "Protection from Evil and Good"
    SANCTUARY = "Sanctuary"
    SHIELD = "Shield"
    SHIELD_OF_FAITH = "Shield of Faith"
    SNARE = "Snare"
    WARDAWAY = "Wardaway"

class AbjurationLevel2Spells(str, Enum):
    AID = "Aid"
    ARCANE_LOCK = "Arcane Lock"
    ARCANE_VIGOR = "Arcane Vigor"
    ELMINSTERS_ELUSION = "Elminster's Elusion"
    LESSER_RESTORATION = "Lesser Restoration"
    PASS_WITHOUT_TRACE = "Pass without Trace"
    PRAYER_OF_HEALING = "Prayer of Healing"
    PROTECTION_FROM_POISON = "Protection from Poison"
    TORTOISE_SHELL = "Tortoise Shell"
    WARDING_BOND = "Warding Bond"

class AbjurationLevel3Spells(str, Enum):
    AURA_OF_VITALITY = "Aura of Vitality"
    BEACON_OF_HOPE = "Beacon of Hope"
    COUNTERSPELL = "Counterspell"
    DISPEL_MAGIC = "Dispel Magic"
    GLYPH_OF_WARDING = "Glyph of Warding"
    INTELLECT_FORTRESS = "Intellect Fortress"
    MAGIC_CIRCLE = "Magic Circle"
    MASS_HEALING_WORD = "Mass Healing Word"
    NONDETECTION = "Nondetection"
    PROTECTION_FROM_ENERGY = "Protection from Energy"
    REMOVE_CURSE = "Remove Curse"

class AbjurationLevel4Spells(str, Enum):
    AURA_OF_LIFE = "Aura of Life"
    AURA_OF_PURITY = "Aura of Purity"
    BACKLASH = "Backlash"
    BANISHMENT = "Banishment"
    DEATH_WARD = "Death Ward"
    FREEDOM_OF_MOVEMENT = "Freedom of Movement"
    GATE_SEAL = "Gate Seal"
    MORDENKAINENS_PRIVATE_SANCTUM = "Mordenkainen's Private Sanctum"
    OTILUKES_RESILIENT_SPHERE = "Otiluke's Resilient Sphere"

class AbjurationLevel5Spells(str, Enum):
    ALUSTRIELS_MOONCLOAK = "Alustriel's Mooncloak"
    ANTILIFE_SHELL = "Antilife Shell"
    CIRCLE_OF_POWER = "Circle of Power"
    DISPEL_EVIL_AND_GOOD = "Dispel Evil and Good"
    GREATER_RESTORATION = "Greater Restoration"
    HALLOW = "Hallow"
    MASS_CURE_WOUNDS = "Mass Cure Wounds"
    PLANAR_BINDING = "Planar Binding"

class AbjurationLevel6Spells(str, Enum):
    CONTINGENCY = "Contingency"
    DRUID_GROVE = "Druid Grove"
    FIZBANS_PLATINUM_SHIELD = "Fizban's Platinum Shield"
    FORBIDDANCE = "Forbiddance"
    GLOBE_OF_INVULNERABILITY = "Globe of Invulnerability"
    GUARDS_AND_WARDS = "Guards and Wards"
    HEAL = "Heal"
    PRIMORDIAL_WARD = "Primordial Ward"

class AbjurationLevel7Spells(str, Enum):
    SYMBOL = "Symbol"

class AbjurationLevel8Spells(str, Enum):
    ANTIMAGIC_FIELD = "Antimagic Field"
    HOLY_AURA = "Holy Aura"
    MIND_BLANK = "Mind Blank"

class AbjurationLevel9Spells(str, Enum):
    IMPRISONMENT = "Imprisonment"
    INVULNERABILITY = "Invulnerability"
    MASS_HEAL = "Mass Heal"
    PRISMATIC_WALL = "Prismatic Wall"

class ConjurationLevel0Spells(str, Enum):
    CREATE_BONFIRE = "Create Bonfire"
    INFESTATION = "Infestation"
    MAGE_HAND = "Mage Hand"
    PRODUCE_FLAME = "Produce Flame"
    SWORD_BURST = "Sword Burst"

class ConjurationLevel1Spells(str, Enum):
    ARMS_OF_HADAR = "Arms of Hadar"
    BUZZING_BEE = "Buzzing Bee"
    ENSNARING_STRIKE = "Ensnaring Strike"
    ENTANGLE = "Entangle"
    FIND_FAMILIAR = "Find Familiar"
    FOG_CLOUD = "Fog Cloud"
    GOODBERRY = "Goodberry"
    GREASE = "Grease"
    HAIL_OF_THORNS = "Hail of Thorns"
    ICE_KNIFE = "Ice Knife"
    TENSERS_FLOATING_DISK = "Tenser's Floating Disk"
    UNSEEN_SERVANT = "Unseen Servant"

class ConjurationLevel2Spells(str, Enum):
    AIR_BUBBLE = "Air Bubble"
    CLOUD_OF_DAGGERS = "Cloud of Daggers"
    DERYANS_HELPFUL_HOMUNCULI = "Deryan's Helpful Homunculi"
    DUST_DEVIL = "Dust Devil"
    FIND_STEED = "Find Steed"
    FLAMING_SPHERE = "Flaming Sphere"
    FLOCK_OF_FAMILIARS = "Flock of Familiars"
    HEALING_SPIRIT = "Healing Spirit"
    HOMUNCULUS_SERVANT = "Homunculus Servant"
    MISTY_STEP = "Misty Step"
    SPRAY_OF_CARDS = "Spray of Cards"
    SUMMON_BEAST = "Summon Beast"
    VORTEX_WARP = "Vortex Warp"
    WEB = "Web"

class ConjurationLevel3Spells(str, Enum):
    CALL_LIGHTNING = "Call Lightning"
    CONJURE_ANIMALS = "Conjure Animals"
    CONJURE_BARRAGE = "Conjure Barrage"
    CONJURE_CONSTRUCTS = "Conjure Constructs"
    CREATE_FOOD_AND_WATER = "Create Food and Water"
    GALDERS_TOWER = "Galder's Tower"
    HUNGER_OF_HADAR = "Hunger of Hadar"
    SLEET_STORM = "Sleet Storm"
    SPIRIT_GUARDIANS = "Spirit Guardians"
    STINKING_CLOUD = "Stinking Cloud"
    SUMMON_FEY = "Summon Fey"
    SUMMON_LESSER_DEMONS = "Summon Lesser Demons"
    SUMMON_SHADOWSPAWN = "Summon Shadowspawn"
    SYLUNES_VIPER = "Sylune's Viper"
    THUNDER_STEP = "Thunder Step"
    TIDAL_WAVE = "Tidal Wave"

class ConjurationLevel4Spells(str, Enum):
    CONJURE_MINOR_ELEMENTALS = "Conjure Minor Elementals"
    CONJURE_WOODLAND_BEINGS = "Conjure Woodland Beings"
    DIMENSION_DOOR = "Dimension Door"
    DOOMTIDE = "Doomtide"
    EVARDS_BLACK_TENTACLES = "Evard's Black Tentacles"
    FIND_GREATER_STEED = "Find Greater Steed"
    GALDERS_SPEEDY_COURIER = "Galder's Speedy Courier"
    GIANT_INSECT = "Giant Insect"
    GRASPING_VINE = "Grasping Vine"
    GUARDIAN_OF_FAITH = "Guardian of Faith"
    LEOMUNDS_SECRET_CHEST = "Leomund's Secret Chest"
    MORDENKAINENS_FAITHFUL_HOUND = "Mordenkainen's Faithful Hound"
    SUMMON_ABERRATION = "Summon Aberration"
    SUMMON_CONSTRUCT = "Summon Construct"
    SUMMON_ELEMENTAL = "Summon Elemental"
    SUMMON_GREATER_DEMON = "Summon Greater Demon"
    WATERY_SPHERE = "Watery Sphere"

class ConjurationLevel5Spells(str, Enum):
    BANISHING_SMITE = "Banishing Smite"
    CLOUDKILL = "Cloudkill"
    CONJURE_ELEMENTAL = "Conjure Elemental"
    CONJURE_VOLLEY = "Conjure Volley"
    FAR_STEP = "Far Step"
    INFERNAL_CALLING = "Infernal Calling"
    INSECT_PLAGUE = "Insect Plague"
    STEEL_WIND_STRIKE = "Steel Wind Strike"
    SUMMON_CELESTIAL = "Summon Celestial"
    SUMMON_DRACONIC_SPIRIT = "Summon Draconic Spirit"
    SUMMON_DRAGON = "Summon Dragon"
    TELEPORTATION_CIRCLE = "Teleportation Circle"
    TREE_STRIDE = "Tree Stride"

class ConjurationLevel6Spells(str, Enum):
    ARCANE_GATE = "Arcane Gate"
    CONJURE_FEY = "Conjure Fey"
    DRAWMIJS_INSTANT_SUMMONS = "Drawmij's Instant Summons"
    HEROES_FEAST = "Heroes' Feast"
    PLANAR_ALLY = "Planar Ally"
    SCATTER = "Scatter"
    SUMMON_FIEND = "Summon Fiend"
    TASHAS_BUBBLING_CAULDRON = "Tasha's Bubbling Cauldron"
    TRANSPORT_VIA_PLANTS = "Transport via Plants"
    WALL_OF_THORNS = "Wall of Thorns"
    WORD_OF_RECALL = "Word of Recall"

class ConjurationLevel7Spells(str, Enum):
    CONJURE_CELESTIAL = "Conjure Celestial"
    DREAM_OF_THE_BLUE_VEIL = "Dream of the Blue Veil"
    ETHEREALNESS = "Etherealness"
    MORDENKAINENS_MAGNIFICENT_MANSION = "Mordenkainen's Magnificent Mansion"
    PLANE_SHIFT = "Plane Shift"
    TELEPORT = "Teleport"
    TEMPLE_OF_THE_GODS = "Temple of the Gods"

class ConjurationLevel8Spells(str, Enum):
    DEMIPLANE = "Demiplane"
    INCENDIARY_CLOUD = "Incendiary Cloud"
    MAZE = "Maze"
    MIGHTY_FORTRESS = "Mighty Fortress"
    TSUNAMI = "Tsunami"

class ConjurationLevel9Spells(str, Enum):
    BLADE_OF_DISASTER = "Blade of Disaster"
    GATE = "Gate"
    STORM_OF_VENGEANCE = "Storm of Vengeance"
    WISH = "Wish"

class DivinationLevel0Spells(str, Enum):
    GUIDANCE = "Guidance"
    TRUE_STRIKE = "True Strike"

class DivinationLevel1Spells(str, Enum):
    BEAST_BOND = "Beast Bond"
    COMPREHEND_LANGUAGES = "Comprehend Languages"
    DETECT_EVIL_AND_GOOD = "Detect Evil and Good"
    DETECT_MAGIC = "Detect Magic"
    DETECT_POISON_AND_DISEASE = "Detect Poison and Disease"
    HUNTERS_MARK = "Hunter's Mark"
    IDENTIFY = "Identify"
    SPEAK_WITH_ANIMALS = "Speak with Animals"

class DivinationLevel2Spells(str, Enum):
    AUGURY = "Augury"
    BEAST_SENSE = "Beast Sense"
    BORROWED_KNOWLEDGE = "Borrowed Knowledge"
    DETECT_THOUGHTS = "Detect Thoughts"
    FIND_TRAPS = "Find Traps"
    LOCATE_ANIMALS_OR_PLANTS = "Locate Animals or Plants"
    LOCATE_OBJECT = "Locate Object"
    MIND_SPIKE = "Mind Spike"
    SEE_INVISIBILITY = "See Invisibility"
    WARP_SENSE = "Warp Sense"

class DivinationLevel3Spells(str, Enum):
    CLAIRVOYANCE = "Clairvoyance"
    SENDING = "Sending"
    TONGUES = "Tongues"

class DivinationLevel4Spells(str, Enum):
    ARCANE_EYE = "Arcane Eye"
    DIVINATION = "Divination"
    LOCATE_CREATURE = "Locate Creature"

class DivinationLevel5Spells(str, Enum):
    COMMUNE = "Commune"
    COMMUNE_WITH_NATURE = "Commune with Nature"
    CONTACT_OTHER_PLANE = "Contact Other Plane"
    LEGEND_LORE = "Legend Lore"
    RARYS_TELEPATHIC_BOND = "Rary's Telepathic Bond"
    SCRYING = "Scrying"

class DivinationLevel6Spells(str, Enum):
    FIND_THE_PATH = "Find the Path"
    TRUE_SEEING = "True Seeing"

class DivinationLevel7Spells(str, Enum):
    pass

class DivinationLevel8Spells(str, Enum):
    TELEPATHY = "Telepathy"

class DivinationLevel9Spells(str, Enum):
    FORESIGHT = "Foresight"

class EnchantmentLevel0Spells(str, Enum):
    ENCODE_THOUGHTS = "Encode Thoughts"
    FRIENDS = "Friends"
    MIND_SLIVER = "Mind Sliver"
    VICIOUS_MOCKERY = "Vicious Mockery"

class EnchantmentLevel1Spells(str, Enum):
    ANIMAL_FRIENDSHIP = "Animal Friendship"
    BANE = "Bane"
    BLESS = "Bless"
    CHARM_PERSON = "Charm Person"
    COMMAND = "Command"
    COMPELLED_DUEL = "Compelled Duel"
    DISSONANT_WHISPERS = "Dissonant Whispers"
    HEROISM = "Heroism"
    HEX = "Hex"
    INSIDIOUS_RHYTHM = "Insidious Rhythm"
    SILVERY_BARBS = "Silvery Barbs"
    SLEEP = "Sleep"
    TASHAS_HIDEOUS_LAUGHTER = "Tasha's Hideous Laughter"

class EnchantmentLevel2Spells(str, Enum):
    ANIMAL_MESSENGER = "Animal Messenger"
    CALM_EMOTIONS = "Calm Emotions"
    CROWN_OF_MADNESS = "Crown of Madness"
    ENTHRALL = "Enthrall"
    GIFT_OF_GAB = "Gift of Gab"
    HOLD_PERSON = "Hold Person"
    JIMS_GLOWING_COIN = "Jim's Glowing Coin"
    SUGGESTION = "Suggestion"
    TASHAS_MIND_WHIP = "Tasha's Mind Whip"
    ZONE_OF_TRUTH = "Zone of Truth"

class EnchantmentLevel3Spells(str, Enum):
    ANTAGONIZE = "Antagonize"
    CATNAP = "Catnap"
    ENEMIES_ABOUND = "Enemies Abound"
    FAST_FRIENDS = "Fast Friends"
    INCITE_GREED = "Incite Greed"
    MOTIVATIONAL_SPEECH = "Motivational Speech"

class EnchantmentLevel4Spells(str, Enum):
    CHARM_MONSTER = "Charm Monster"
    COMPULSION = "Compulsion"
    CONFUSION = "Confusion"
    DOMINATE_BEAST = "Dominate Beast"
    RAULOTHIMS_PSYCHIC_LANCE = "Raulothim's Psychic Lance"
    STAGGERING_SMITE = "Staggering Smite"

class EnchantmentLevel5Spells(str, Enum):
    DOMINATE_PERSON = "Dominate Person"
    GEAS = "Geas"
    HOLD_MONSTER = "Hold Monster"
    MODIFY_MEMORY = "Modify Memory"
    SYNAPTIC_STATIC = "Synaptic Static"
    YOLANDES_REGAL_PRESENCE = "Yolande's Regal Presence"

class EnchantmentLevel6Spells(str, Enum):
    DIRGE = "Dirge"
    LEOMUNDS_LAMENTABLE_BELABORMENT = "Leomund's Lamentable Belaborment"
    MASS_SUGGESTION = "Mass Suggestion"
    OTTOS_IRRESISTIBLE_DANCE = "Otto's Irresistible Dance"

class EnchantmentLevel7Spells(str, Enum):
    POWER_WORD_FORTIFY = "Power Word Fortify"
    POWER_WORD_PAIN = "Power Word Pain"

class EnchantmentLevel8Spells(str, Enum):
    ANTIPATHY_SYMPATHY = "Antipathy/Sympathy"
    BEFUDDLEMENT = "Befuddlement"
    DOMINATE_MONSTER = "Dominate Monster"
    FEEBLEMIND = "Feeblemind"
    GLIBNESS = "Glibness"
    POWER_WORD_STUN = "Power Word Stun"

class EnchantmentLevel9Spells(str, Enum):
    POWER_WORD_HEAL = "Power Word Heal"
    POWER_WORD_KILL = "Power Word Kill"
    PSYCHIC_SCREAM = "Psychic Scream"

class EvocationLevel0Spells(str, Enum):
    ACID_SPLASH = "Acid Splash"
    BOOMING_BLADE = "Booming Blade"
    ELDRITCH_BLAST = "Eldritch Blast"
    FIRE_BOLT = "Fire Bolt"
    FROSTBITE = "Frostbite"
    GREEN_FLAME_BLADE = "Green-Flame Blade"
    LIGHT = "Light"
    LIGHTNING_LURE = "Lightning Lure"
    RAY_OF_FROST = "Ray of Frost"
    SACRED_FLAME = "Sacred Flame"
    SHOCKING_GRASP = "Shocking Grasp"
    SORCEROUS_BURST = "Sorcerous Burst"
    STARRY_WISP = "Starry Wisp"
    THUNDERCLAP = "Thunderclap"
    WORD_OF_RADIANCE = "Word of Radiance"

class EvocationLevel1Spells(str, Enum):
    BURNING_HANDS = "Burning Hands"
    CHAOS_BOLT = "Chaos Bolt"
    CHROMATIC_ORB = "Chromatic Orb"
    DIVINE_SMITE = "Divine Smite"
    EARTH_TREMOR = "Earth Tremor"
    FAERIE_FIRE = "Faerie Fire"
    FROST_FINGERS = "Frost Fingers"
    GUIDING_BOLT = "Guiding Bolt"
    HELLISH_REBUKE = "Hellish Rebuke"
    JIMS_MAGIC_MISSILE = "Jim's Magic Missile"
    MAGIC_MISSILE = "Magic Missile"
    SEARING_SMITE = "Searing Smite"
    SPELLFIRE_FLARE = "Spellfire Flare"
    TASHAS_CAUSTIC_BREW = "Tasha's Caustic Brew"
    THUNDEROUS_SMITE = "Thunderous Smite"
    THUNDERWAVE = "Thunderwave"
    WITCH_BOLT = "Witch Bolt"

class EvocationLevel2Spells(str, Enum):
    AGANAZZARS_SCORCHER = "Aganazzar's Scorcher"
    BRANDING_SMITE = "Branding Smite"
    CONTINUAL_FLAME = "Continual Flame"
    DARKNESS = "Darkness"
    FLAME_BLADE = "Flame Blade"
    GUST_OF_WIND = "Gust of Wind"
    MELFS_ACID_ARROW = "Melf's Acid Arrow"
    MOONBEAM = "Moonbeam"
    RIMES_BINDING_ICE = "Rime's Binding Ice"
    SCORCHING_RAY = "Scorching Ray"
    SEARING_ORB = "Searing Orb"
    SHATTER = "Shatter"
    SNILLOCS_SNOWBALL_SWARM = "Snilloc's Snowball Swarm"
    SPIRITUAL_WEAPON = "Spiritual Weapon"
    WARDING_WIND = "Warding Wind"

class EvocationLevel3Spells(str, Enum):
    ASTRAL_FLOOD = "Astral Flood"
    BLINDING_SMITE = "Blinding Smite"
    CACOPHONIC_SHIELD = "Cacophonic Shield"
    CRUSADERS_MANTLE = "Crusader's Mantle"
    DAYLIGHT = "Daylight"
    FIREBALL = "Fireball"
    LAERALS_SILVER_LANCE = "Laeral's Silver Lance"
    LEOMUNDS_TINY_HUT = "Leomund's Tiny Hut"
    LIGHTNING_BOLT = "Lightning Bolt"
    MELFS_MINUTE_METEORS = "Melf's Minute Meteors"
    WALL_OF_SAND = "Wall of Sand"
    WALL_OF_WATER = "Wall of Water"
    WIND_WALL = "Wind Wall"

class EvocationLevel4Spells(str, Enum):
    FIRE_SHIELD = "Fire Shield"
    FOUNT_OF_MOONLIGHT = "Fount of Moonlight"
    ICE_STORM = "Ice Storm"
    SICKENING_RADIANCE = "Sickening Radiance"
    SPELLFIRE_STORM = "Spellfire Storm"
    STORM_SPHERE = "Storm Sphere"
    VITRIOLIC_SPHERE = "Vitriolic Sphere"
    WALL_OF_FIRE = "Wall of Fire"

class EvocationLevel5Spells(str, Enum):
    BIGBYS_HAND = "Bigby's Hand"
    CONE_OF_COLD = "Cone of Cold"
    DAWN = "Dawn"
    DESTRUCTIVE_WAVE = "Destructive Wave"
    FLAME_STRIKE = "Flame Strike"
    HOLY_WEAPON = "Holy Weapon"
    IMMOLATION = "Immolation"
    JALLARZIS_STORM_OF_RADIANCE = "Jallarzi's Storm of Radiance"
    MAELSTROM = "Maelstrom"
    WALL_OF_FORCE = "Wall of Force"
    WALL_OF_LIGHT = "Wall of Light"
    WALL_OF_STONE = "Wall of Stone"
    WRATH_OF_NATURE = "Wrath of Nature"

class EvocationLevel6Spells(str, Enum):
    BLADE_BARRIER = "Blade Barrier"
    CHAIN_LIGHTNING = "Chain Lightning"
    ELMINSTERS_EFFULGENT_SPHERES = "Elminster's Effulgent Spheres"
    OTILUKES_FREEZING_SPHERE = "Otiluke's Freezing Sphere"
    SUNBEAM = "Sunbeam"
    WALL_OF_ICE = "Wall of Ice"

class EvocationLevel7Spells(str, Enum):
    CROWN_OF_STARS = "Crown of Stars"
    DELAYED_BLAST_FIREBALL = "Delayed Blast Fireball"
    DIVINE_WORD = "Divine Word"
    FIRE_STORM = "Fire Storm"
    FORCECAGE = "Forcecage"
    MORDENKAINENS_SWORD = "Mordenkainen's Sword"
    PRISMATIC_SPRAY = "Prismatic Spray"
    WHIRLWIND = "Whirlwind"

class EvocationLevel8Spells(str, Enum):
    HOLY_STAR_OF_MYSTRA = "Holy Star of Mystra"
    MADDENING_DARKNESS = "Maddening Darkness"
    SUNBURST = "Sunburst"

class EvocationLevel9Spells(str, Enum):
    METEOR_SWARM = "Meteor Swarm"

class IllusionLevel0Spells(str, Enum):
    DANCING_LIGHTS = "Dancing Lights"
    MINOR_ILLUSION = "Minor Illusion"

class IllusionLevel1Spells(str, Enum):
    COLOR_SPRAY = "Color Spray"
    DISGUISE_SELF = "Disguise Self"
    DISTORT_VALUE = "Distort Value"
    ILLUSORY_SCRIPT = "Illusory Script"
    SILENT_IMAGE = "Silent Image"

class IllusionLevel2Spells(str, Enum):
    BLUR = "Blur"
    INVISIBILITY = "Invisibility"
    MAGIC_MOUTH = "Magic Mouth"
    MIRROR_IMAGE = "Mirror Image"
    NATHAIRS_MISCHIEF = "Nathair's Mischief"
    NYSTULS_MAGIC_AURA = "Nystul's Magic Aura"
    PHANTASMAL_FORCE = "Phantasmal Force"
    SHADOW_BLADE = "Shadow Blade"
    SILENCE = "Silence"

class IllusionLevel3Spells(str, Enum):
    FEAR = "Fear"
    HYPNOTIC_PATTERN = "Hypnotic Pattern"
    MAJOR_IMAGE = "Major Image"
    PHANTOM_STEED = "Phantom Steed"

class IllusionLevel4Spells(str, Enum):
    GREATER_INVISIBILITY = "Greater Invisibility"
    HALLUCINATORY_TERRAIN = "Hallucinatory Terrain"
    PHANTASMAL_KILLER = "Phantasmal Killer"

class IllusionLevel5Spells(str, Enum):
    CREATION = "Creation"
    DREAM = "Dream"
    MISLEAD = "Mislead"
    SEEMING = "Seeming"

class IllusionLevel6Spells(str, Enum):
    MENTAL_PRISON = "Mental Prison"
    PROGRAMMED_ILLUSION = "Programmed Illusion"

class IllusionLevel7Spells(str, Enum):
    MIRAGE_ARCANE = "Mirage Arcane"
    PROJECT_IMAGE = "Project Image"
    SIMULACRUM = "Simulacrum"

class IllusionLevel8Spells(str, Enum):
    ILLUSORY_DRAGON = "Illusory Dragon"

class IllusionLevel9Spells(str, Enum):
    WEIRD = "Weird"

class NecromancyLevel0Spells(str, Enum):
    CHILL_TOUCH = "Chill Touch"
    POISON_SPRAY = "Poison Spray"
    SAPPING_STING = "Sapping Sting"
    SPARE_THE_DYING = "Spare the Dying"
    TOLL_THE_DEAD = "Toll the Dead"

class NecromancyLevel1Spells(str, Enum):
    CAUSE_FEAR = "Cause Fear"
    FALSE_LIFE = "False Life"
    INFLICT_WOUNDS = "Inflict Wounds"
    RAY_OF_SICKNESS = "Ray of Sickness"
    WRATHFUL_SMITE = "Wrathful Smite"

class NecromancyLevel2Spells(str, Enum):
    DEATH_ARMOR = "Death Armor"
    GENTLE_REPOSE = "Gentle Repose"
    RAY_OF_ENFEEBLEMENT = "Ray of Enfeeblement"
    WITHER_AND_BLOOM = "Wither and Bloom"

class NecromancyLevel3Spells(str, Enum):
    ANIMATE_DEAD = "Animate Dead"
    BESTOW_CURSE = "Bestow Curse"
    FEIGN_DEATH = "Feign Death"
    LIFE_TRANSFERENCE = "Life Transference"
    REVIVIFY = "Revivify"
    SPEAK_WITH_DEAD = "Speak with Dead"
    SPIRIT_SHROUD = "Spirit Shroud"
    SUMMON_UNDEAD = "Summon Undead"
    VAMPIRIC_TOUCH = "Vampiric Touch"

class NecromancyLevel4Spells(str, Enum):
    BLIGHT = "Blight"
    SHADOW_OF_MOIL = "Shadow of Moil"
    SPIRIT_OF_DEATH = "Spirit of Death"

class NecromancyLevel5Spells(str, Enum):
    CONTAGION = "Contagion"
    DANSE_MACABRE = "Danse Macabre"
    ENERVATION = "Enervation"
    NEGATIVE_ENERGY_FLOOD = "Negative Energy Flood"
    RAISE_DEAD = "Raise Dead"
    REINCARNATE = "Reincarnate"

class NecromancyLevel6Spells(str, Enum):
    CIRCLE_OF_DEATH = "Circle of Death"
    CREATE_UNDEAD = "Create Undead"
    EYEBITE = "Eyebite"
    HARM = "Harm"
    MAGIC_JAR = "Magic Jar"
    SOUL_CAGE = "Soul Cage"

class NecromancyLevel7Spells(str, Enum):
    FINGER_OF_DEATH = "Finger of Death"
    RESURRECTION = "Resurrection"
    VOID_STAR = "Void Star"

class NecromancyLevel8Spells(str, Enum):
    ABI_DALZIMS_HORRID_WILTING = "Abi-Dalzim's Horrid Wilting"
    CLONE = "Clone"

class NecromancyLevel9Spells(str, Enum):
    ASTRAL_PROJECTION = "Astral Projection"
    TRUE_RESURRECTION = "True Resurrection"

class TransmutationLevel0Spells(str, Enum):
    CONTROL_FLAMES = "Control Flames"
    DRUIDCRAFT = "Druidcraft"
    ELEMENTALISM = "Elementalism"
    GUST = "Gust"
    MAGIC_STONE = "Magic Stone"
    MENDING = "Mending"
    MESSAGE = "Message"
    MOLD_EARTH = "Mold Earth"
    PRESTIDIGITATION = "Prestidigitation"
    PRIMAL_SAVAGERY = "Primal Savagery"
    SHAPE_WATER = "Shape Water"
    SHILLELAGH = "Shillelagh"
    THAUMATURGY = "Thaumaturgy"
    THORN_WHIP = "Thorn Whip"

class TransmutationLevel1Spells(str, Enum):
    CATAPULT = "Catapult"
    CREATE_OR_DESTROY_WATER = "Create or Destroy Water"
    DIVINE_FAVOR = "Divine Favor"
    EXPEDITIOUS_RETREAT = "Expeditious Retreat"
    FEATHER_FALL = "Feather Fall"
    JUMP = "Jump"
    LONGSTRIDER = "Longstrider"
    PURIFY_FOOD_AND_DRINK = "Purify Food and Drink"
    ZEPHYR_STRIKE = "Zephyr Strike"

class TransmutationLevel2Spells(str, Enum):
    ALTER_SELF = "Alter Self"
    BARKSKIN = "Barkskin"
    BLINDNESS_DEAFNESS = "Blindness/Deafness"
    CORDON_OF_ARROWS = "Cordon of Arrows"
    DARKVISION = "Darkvision"
    DRAGONS_BREATH = "Dragon's Breath"
    EARTHBIND = "Earthbind"
    ENHANCE_ABILITY = "Enhance Ability"
    ENLARGE_REDUCE = "Enlarge/Reduce"
    HEAT_METAL = "Heat Metal"
    KINETIC_JAUNT = "Kinetic Jaunt"
    KNOCK = "Knock"
    LEVITATE = "Levitate"
    MAGIC_WEAPON = "Magic Weapon"
    MAXIMILLIANS_EARTHEN_GRASP = "Maximillian's Earthen Grasp"
    PYROTECHNICS = "Pyrotechnics"
    ROPE_TRICK = "Rope Trick"
    SHINING_SMITE = "Shining Smite"
    SKYWRITE = "Skywrite"
    SPIDER_CLIMB = "Spider Climb"
    SPIKE_GROWTH = "Spike Growth"

class TransmutationLevel3Spells(str, Enum):
    ASHARDALONS_STRIDE = "Ashardalon's Stride"
    BLINK = "Blink"
    ELEMENTAL_WEAPON = "Elemental Weapon"
    ERUPTING_EARTH = "Erupting Earth"
    FLAME_ARROWS = "Flame Arrows"
    FLY = "Fly"
    GASEOUS_FORM = "Gaseous Form"
    HASTE = "Haste"
    LIGHTNING_ARROW = "Lightning Arrow"
    MELD_INTO_STONE = "Meld into Stone"
    PLANT_GROWTH = "Plant Growth"
    SLOW = "Slow"
    SPEAK_WITH_PLANTS = "Speak with Plants"
    TINY_SERVANT = "Tiny Servant"
    WATER_BREATHING = "Water Breathing"
    WATER_WALK = "Water Walk"

class TransmutationLevel4Spells(str, Enum):
    CONTROL_WATER = "Control Water"
    ELEMENTAL_BANE = "Elemental Bane"
    FABRICATE = "Fabricate"
    GUARDIAN_OF_NATURE = "Guardian of Nature"
    POLYMORPH = "Polymorph"
    STICKS_TO_SNAKES = "Sticks to Snakes"
    STONE_SHAPE = "Stone Shape"
    STONESKIN = "Stoneskin"

class TransmutationLevel5Spells(str, Enum):
    ANIMATE_OBJECTS = "Animate Objects"
    AWAKEN = "Awaken"
    CONTROL_WINDS = "Control Winds"
    CREATE_SPELLJAMMING_HELM = "Create Spelljamming Helm"
    PASSWALL = "Passwall"
    SKILL_EMPOWERMENT = "Skill Empowerment"
    SONGALS_ELEMENTAL_SUFFUSION = "Songal's Elemental Suffusion"
    SWIFT_QUIVER = "Swift Quiver"
    TELEKINESIS = "Telekinesis"
    TRANSMUTE_ROCK = "Transmute Rock"

class TransmutationLevel6Spells(str, Enum):
    BONES_OF_THE_EARTH = "Bones of the Earth"
    CREATE_HOMUNCULUS = "Create Homunculus"
    DISINTEGRATE = "Disintegrate"
    FLESH_TO_STONE = "Flesh to Stone"
    INVESTITURE_OF_FLAME = "Investiture of Flame"
    INVESTITURE_OF_ICE = "Investiture of Ice"
    INVESTITURE_OF_STONE = "Investiture of Stone"
    INVESTITURE_OF_WIND = "Investiture of Wind"
    MOVE_EARTH = "Move Earth"
    TASHAS_OTHERWORLDLY_GUISE = "Tasha's Otherworldly Guise"
    TENSERS_TRANSFORMATION = "Tenser's Transformation"
    WIND_WALK = "Wind Walk"

class TransmutationLevel7Spells(str, Enum):
    CREATE_MAGEN = "Create Magen"
    DRACONIC_TRANSFORMATION = "Draconic Transformation"
    REGENERATE = "Regenerate"
    REVERSE_GRAVITY = "Reverse Gravity"
    SEQUESTER = "Sequester"
    SIMBULS_SYNOSTODWEOMER = "Simbul's Synostodweomer"

class TransmutationLevel8Spells(str, Enum):
    ANIMAL_SHAPES = "Animal Shapes"
    CONTROL_WEATHER = "Control Weather"
    EARTHQUAKE = "Earthquake"

class TransmutationLevel9Spells(str, Enum):
    MASS_POLYMORPH = "Mass Polymorph"
    SHAPECHANGE = "Shapechange"
    TIME_STOP = "Time Stop"
    TRUE_POLYMORPH = "True Polymorph"
